export const DISCIPLINE_CATEGORIES = [
  { id: "health-med", label: "Health & Medical Sciences" },
  { id: "allied-ph", label: "Allied Health & Public Health" },
  { id: "law-biz", label: "Law & Business" },
  { id: "engineering", label: "Engineering" },
  { id: "sci-tech", label: "Sciences & Tech" },
  { id: "social-hum", label: "Social Sciences & Humanities" },
];

const L6_CLINICAL = ["100 (Pre-clinical)", "200 (Pre-clinical)", "300 (Pre-clinical)", "400 (Clinical)", "500 (Clinical)", "600 (Clinical / Internship)"];
const L5 = ["100 Level", "200 Level", "300 Level", "400 Level", "500 Level"];
const L4 = ["100 Level", "200 Level", "300 Level", "400 Level"];
const RESIDENCY = ["Resident Year 1", "Resident Year 2", "Resident Year 3", "Resident Year 4", "Fellowship"];

export const MEDICAL_PROGRAMS = [
  // ── Health & Medical Sciences ──────────────────────────────────────
  {
    id: "medicine",
    label: "Medicine & Surgery (MBBS)",
    icon: "🩺",
    color: "#ef4444",
    category: "health-med",
    levels: L6_CLINICAL,
    subjects: ["Anatomy", "Physiology", "Biochemistry", "Pharmacology", "Pathology", "Microbiology", "Community Medicine", "Internal Medicine", "Surgery", "Obstetrics & Gynaecology", "Paediatrics", "Psychiatry"],
  },
  {
    id: "anatomy",
    label: "Anatomy (B.Sc)",
    icon: "🦴",
    color: "#ec4899",
    category: "health-med",
    levels: L4,
    subjects: ["Gross Anatomy", "Histology", "Embryology", "Neuroanatomy", "Cytology", "Osteology", "Comparative Anatomy", "Anthropology"],
  },
  {
    id: "physiology",
    label: "Physiology (B.Sc)",
    icon: "🫀",
    color: "#10b981",
    category: "health-med",
    levels: L4,
    subjects: ["Cell Physiology", "Systemic Physiology", "Neurophysiology", "Endocrine Physiology", "Renal Physiology", "Cardiovascular Physiology", "Respiratory Physiology", "Gastrointestinal Physiology"],
  },
  {
    id: "pharmacology",
    label: "Pharmacology (B.Sc)",
    icon: "💊",
    color: "#a855f7",
    category: "health-med",
    levels: L4,
    subjects: ["Pharmacokinetics", "Pharmacodynamics", "Autonomic Pharmacology", "Clinical Pharmacology", "Toxicology", "Chemotherapy", "Neuropharmacology", "Cardiovascular Pharmacology"],
  },
  {
    id: "pathology",
    label: "Pathology (B.Sc)",
    icon: "🔬",
    color: "#f43f5e",
    category: "health-med",
    levels: L4,
    subjects: ["General Pathology", "Systemic Pathology", "Histopathology", "Chemical Pathology", "Haematological Pathology", "Forensic Pathology", "Immunopathology", "Molecular Pathology"],
  },
  {
    id: "microbiology",
    label: "Microbiology (B.Sc)",
    icon: "🦠",
    color: "#14b8a6",
    category: "health-med",
    levels: L4,
    subjects: ["General Microbiology", "Bacteriology", "Virology", "Mycology", "Parasitology", "Immunology", "Industrial Microbiology", "Epidemiology"],
  },
  {
    id: "nursing",
    label: "Nursing Science (BNSc)",
    icon: "💉",
    color: "#22c55e",
    category: "health-med",
    levels: L5,
    subjects: ["Anatomy & Physiology", "Medical-Surgical Nursing", "Community Health Nursing", "Maternal & Child Health Nursing", "Mental Health Nursing", "Nursing Foundations", "Pharmacology for Nurses", "Nursing Research"],
  },
  {
    id: "radiography",
    label: "Radiography & Radiological Sciences",
    icon: "📡",
    color: "#8b5cf6",
    category: "health-med",
    levels: L5,
    subjects: ["Radiation Physics", "Anatomy for Radiographers", "Radiographic Positioning", "Medical Imaging", "Radiotherapy", "Ultrasound", "MRI Physics", "Radiation Protection"],
  },
  {
    id: "dentistry",
    label: "Dentistry (BDS)",
    icon: "🦷",
    color: "#06b6d4",
    category: "health-med",
    levels: ["200 (Pre-clinical)", "300 (Pre-clinical)", "400 (Clinical)", "500 (Clinical)", "600 (Clinical)"],
    subjects: ["Oral Anatomy", "Oral Physiology", "Dental Materials", "Oral Pathology", "Oral Surgery", "Restorative Dentistry", "Orthodontics", "Paediatric Dentistry", "Periodontology", "Prosthodontics"],
  },
  {
    id: "physiotherapy",
    label: "Physiotherapy (B.PT)",
    icon: "💪",
    color: "#f59e0b",
    category: "health-med",
    levels: L5,
    subjects: ["Anatomy", "Physiology", "Kinesiology", "Electrotherapy", "Exercise Therapy", "Orthopaedic Physiotherapy", "Neurological Physiotherapy", "Cardiopulmonary Physiotherapy"],
  },
  {
    id: "biochemistry",
    label: "Biochemistry (B.Sc)",
    icon: "🧪",
    color: "#a855f7",
    category: "health-med",
    levels: L4,
    subjects: ["Biomolecules", "Enzymology", "Metabolism", "Clinical Biochemistry", "Molecular Biology", "Nutritional Biochemistry", "Medical Biochemistry", "Biotechnology"],
  },
  {
    id: "basic-sciences",
    label: "Basic Sciences (Pre-clinical)",
    icon: "🧬",
    color: "#38bdf8",
    category: "health-med",
    levels: ["100 Level", "200 Level"],
    subjects: ["Cell Biology", "General Chemistry", "Organic Chemistry", "Physics for Life Sciences", "Introductory Anatomy", "Introductory Physiology", "Genetics", "Biostatistics"],
  },

  // ── Allied Health & Public Health ──────────────────────────────────
  {
    id: "mls",
    label: "Medical Laboratory Science (MLS)",
    icon: "🔬",
    color: "#3b82f6",
    category: "allied-ph",
    levels: L5,
    subjects: ["Clinical Biochemistry", "Haematology", "Medical Microbiology", "Histopathology", "Immunology", "Parasitology", "Virology", "Blood Transfusion Science"],
  },
  {
    id: "optometry",
    label: "Optometry (OD)",
    icon: "👁️",
    color: "#0ea5e9",
    category: "allied-ph",
    levels: L6_CLINICAL,
    subjects: ["Ocular Anatomy", "Clinical Optics", "Visual Science", "Ocular Pharmacology", "Contact Lens Practice", "Binocular Vision", "Ocular Disease", "Low Vision Rehabilitation"],
  },
  {
    id: "nutrition",
    label: "Nutrition & Dietetics",
    icon: "🥗",
    color: "#84cc16",
    category: "allied-ph",
    levels: L4,
    subjects: ["Human Nutrition", "Clinical Nutrition", "Diet Therapy", "Food Science", "Community Nutrition", "Nutritional Biochemistry", "Food Service Management", "Nutrition Assessment"],
  },
  {
    id: "env-health",
    label: "Environmental Health Science",
    icon: "🌍",
    color: "#16a34a",
    category: "allied-ph",
    levels: L4,
    subjects: ["Epidemiology", "Occupational Health", "Environmental Sanitation", "Water & Waste Management", "Food Hygiene", "Vector Control", "Environmental Toxicology", "Health Promotion"],
  },
  {
    id: "prosthetics",
    label: "Prosthetics & Orthotics",
    icon: "🦾",
    color: "#64748b",
    category: "allied-ph",
    levels: L4,
    subjects: ["Biomechanics", "Orthotic Design", "Prosthetic Design", "Materials Science", "Clinical Assessment", "Rehabilitation Engineering", "Gait Analysis", "Workshop Practice"],
  },
  {
    id: "speech-therapy",
    label: "Speech-Language Therapy",
    icon: "🗣️",
    color: "#f97316",
    category: "allied-ph",
    levels: L4,
    subjects: ["Communication Disorders", "Swallowing Disorders", "Phonetics & Phonology", "Language Development", "Neurogenic Speech Disorders", "Audiology Basics", "Fluency Disorders", "Clinical Practicum"],
  },
  {
    id: "audiology",
    label: "Audiology",
    icon: "👂",
    color: "#eab308",
    category: "allied-ph",
    levels: L4,
    subjects: ["Hearing Assessment", "Vestibular Disorders", "Acoustics & Psychoacoustics", "Aural Rehabilitation", "Paediatric Audiology", "Hearing Aids", "Electrophysiology", "Ear Anatomy & Physiology"],
  },
  {
    id: "public-health",
    label: "Public Health",
    icon: "🌐",
    color: "#0d9488",
    category: "allied-ph",
    levels: L4,
    subjects: ["Epidemiology", "Biostatistics", "Health Policy", "Environmental Health", "Health Promotion", "Global Health", "Disease Prevention", "Research Methods"],
  },
  {
    id: "community-health",
    label: "Community Health",
    icon: "🏘️",
    color: "#65a30d",
    category: "allied-ph",
    levels: L4,
    subjects: ["Primary Healthcare", "Health Education", "Community Diagnosis", "Immunization Programs", "Maternal & Child Health", "Disease Surveillance", "Health Systems", "Field Practice"],
  },
  {
    id: "anaesthesia-tech",
    label: "Anaesthesia Technology",
    icon: "😷",
    color: "#0891b2",
    category: "allied-ph",
    levels: L4,
    subjects: ["Perioperative Care", "Airway Management", "Anaesthetic Pharmacology", "Patient Monitoring", "Anaesthesia Equipment", "Critical Care Basics", "Pain Management", "Clinical Posting"],
  },
  {
    id: "health-info",
    label: "Health Information Management",
    icon: "📋",
    color: "#7c3aed",
    category: "allied-ph",
    levels: L4,
    subjects: ["Medical Records", "Health Informatics", "Health Statistics", "ICD Coding", "Health Data Management", "Health Law & Ethics", "Information Systems", "Quality Assurance"],
  },
  {
    id: "cytotechnology",
    label: "Cytotechnology",
    icon: "🔬",
    color: "#db2777",
    category: "allied-ph",
    levels: L4,
    subjects: ["Cytopathology", "Screening Techniques", "Cell Biology", "Gynaecological Cytology", "Non-Gynaecological Cytology", "Fine Needle Aspiration", "Laboratory Techniques", "Histology Basics"],
  },
  {
    id: "biomedical-eng",
    label: "Biomedical Engineering",
    icon: "⚕️",
    color: "#4f46e5",
    category: "allied-ph",
    levels: L5,
    subjects: ["Medical Devices", "Instrumentation", "Biomechanics", "Biomaterials", "Physiological Modelling", "Medical Imaging Systems", "Clinical Engineering", "Circuit Analysis"],
  },
  {
    id: "haematology",
    label: "Haematology & Blood Transfusion Science",
    icon: "🩸",
    color: "#dc2626",
    category: "allied-ph",
    levels: L4,
    subjects: ["Blood Banking", "Transfusion Medicine", "Haematological Disorders", "Coagulation", "Immunohaematology", "Laboratory Haematology", "Blood Components", "Quality Control"],
  },
  {
    id: "parasitology",
    label: "Parasitology & Entomology",
    icon: "🦟",
    color: "#059669",
    category: "allied-ph",
    levels: L4,
    subjects: ["Medical Entomology", "Helminthology", "Protozoology", "Vector Biology", "Parasitic Diseases", "Tropical Medicine", "Epidemiology of Parasites", "Diagnostic Parasitology"],
  },

  // ── Law & Business ─────────────────────────────────────────────────
  {
    id: "law",
    label: "Law (LL.B)",
    icon: "⚖️",
    color: "#fbbf24",
    category: "law-biz",
    levels: L5,
    subjects: ["Constitutional Law", "Criminal Law", "Contract Law", "Tort Law", "Land Law", "Commercial Law", "Law of Evidence", "Jurisprudence"],
  },
  {
    id: "accounting",
    label: "Accounting",
    icon: "📊",
    color: "#34d399",
    category: "law-biz",
    levels: L4,
    subjects: ["Financial Accounting", "Auditing", "Cost Accounting", "Management Accounting", "Taxation", "Corporate Reporting", "Public Sector Accounting", "Accounting Information Systems"],
  },
  {
    id: "business-admin",
    label: "Business Administration",
    icon: "💼",
    color: "#60a5fa",
    category: "law-biz",
    levels: L4,
    subjects: ["Management", "Marketing", "Organizational Behaviour", "Business Finance", "Human Resource Management", "Operations Management", "Business Policy", "Entrepreneurship"],
  },
  {
    id: "economics",
    label: "Economics",
    icon: "📈",
    color: "#2dd4bf",
    category: "law-biz",
    levels: L4,
    subjects: ["Microeconomics", "Macroeconomics", "Econometrics", "Development Economics", "Public Finance", "International Economics", "Monetary Economics", "Economic History"],
  },
  {
    id: "banking-finance",
    label: "Banking & Finance",
    icon: "🏦",
    color: "#818cf8",
    category: "law-biz",
    levels: L4,
    subjects: ["Corporate Finance", "Investment Analysis", "Money & Banking", "Financial Markets", "Risk Management", "Portfolio Management", "International Finance", "Financial Statement Analysis"],
  },

  // ── Engineering ────────────────────────────────────────────────────
  {
    id: "mech-eng",
    label: "Mechanical Engineering",
    icon: "⚙️",
    color: "#94a3b8",
    category: "engineering",
    levels: L5,
    subjects: ["Thermodynamics", "Machine Design", "Fluid Mechanics", "Engineering Mechanics", "Materials Science", "Heat Transfer", "Manufacturing Processes", "Control Engineering"],
  },
  {
    id: "elect-eng",
    label: "Electrical Engineering",
    icon: "⚡",
    color: "#facc15",
    category: "engineering",
    levels: L5,
    subjects: ["Circuits", "Power Systems", "Electromagnetics", "Electronics", "Control Systems", "Electric Machines", "Signal Processing", "Power Electronics"],
  },
  {
    id: "civil-eng",
    label: "Civil Engineering",
    icon: "🏗️",
    color: "#fb923c",
    category: "engineering",
    levels: L5,
    subjects: ["Structural Design", "Construction", "Geotechnics", "Fluid Mechanics", "Surveying", "Transportation Engineering", "Concrete Technology", "Hydrology"],
  },

  // ── Sciences & Tech ────────────────────────────────────────────────
  {
    id: "computer-science",
    label: "Computer Science",
    icon: "💻",
    color: "#22d3ee",
    category: "sci-tech",
    levels: L4,
    subjects: ["Programming", "Data Structures", "Algorithms", "Databases", "Operating Systems", "Computer Networks", "Software Engineering", "Discrete Mathematics"],
  },

  // ── Social Sciences & Humanities ───────────────────────────────────
  {
    id: "political-science",
    label: "Political Science",
    icon: "🏛️",
    color: "#c084fc",
    category: "social-hum",
    levels: L4,
    subjects: ["Government", "International Relations", "Political Theory", "Comparative Politics", "Public Administration", "Nigerian Politics", "Political Economy", "Research Methods"],
  },
  {
    id: "mass-comm",
    label: "Mass Communication",
    icon: "📰",
    color: "#f472b6",
    category: "social-hum",
    levels: L4,
    subjects: ["Journalism", "Public Relations", "Broadcasting", "Media Law & Ethics", "Advertising", "Media Writing", "Photojournalism", "Development Communication"],
  },
  {
    id: "psychology",
    label: "Psychology",
    icon: "🧠",
    color: "#a78bfa",
    category: "social-hum",
    levels: L4,
    subjects: ["Clinical Psychology", "Cognitive Psychology", "Developmental Psychology", "Abnormal Psychology", "Social Psychology", "Research Methods", "Physiological Psychology", "Psychometrics"],
  },

  // ── Postgraduate ───────────────────────────────────────────────────
  {
    id: "dermatology",
    label: "Dermatology (Postgraduate)",
    icon: "🧬",
    color: "#f43f5e",
    category: "health-med",
    levels: RESIDENCY,
    subjects: ["Basic Dermatology", "Dermatopathology", "Cutaneous Surgery", "Cosmetic Dermatology", "Pediatric Dermatology", "Dermatologic Immunology", "Tropical Dermatology", "Photodermatology"],
  },
  {
    id: "paediatrics",
    label: "Paediatrics (Postgraduate)",
    icon: "👶",
    color: "#6366f1",
    category: "health-med",
    levels: RESIDENCY,
    subjects: ["Neonatology", "General Paediatrics", "Paediatric Cardiology", "Paediatric Infectious Diseases", "Paediatric Oncology", "Paediatric Neurology", "Paediatric Endocrinology", "Adolescent Medicine"],
  },
];

export function getProgram(id) {
  return MEDICAL_PROGRAMS.find((p) => p.id === id) || MEDICAL_PROGRAMS[0];
}

export function getProgramSubjects(programId) {
  const program = getProgram(programId);
  return program ? program.subjects : [];
}

export const MEDICAL_BADGES = [
  { id: "anatomy_master", icon: "🦴", label: "Anatomy Master", desc: "Complete 50 Anatomy questions correctly" },
  { id: "pharma_pro", icon: "💊", label: "Pharma Pro", desc: "Complete 50 Pharmacology questions correctly" },
  { id: "clinical_reasoner", icon: "🧠", label: "Clinical Reasoner", desc: "Solve 10 clinical case simulations" },
  { id: "osce_ready", icon: "🏥", label: "OSCE Ready", desc: "Complete 5 OSCE practice stations" },
  { id: "drug_expert", icon: "💉", label: "Drug Expert", desc: "Review 50 drug reference entries" },
  { id: "lab_wizard", icon: "🧪", label: "Lab Wizard", desc: "Master 20 lab value interpretations" },
  { id: "first_diagnosis", icon: "🔍", label: "First Diagnosis", desc: "Complete your first clinical case" },
  { id: "differential_dx", icon: "⚖️", label: "Differential Thinker", desc: "List 3+ differentials in a clinical case" },
  { id: "rotation_survivor", icon: "🏥", label: "Rotation Survivor", desc: "Complete a full clinical rotation study path" },
  { id: "code_blue", icon: "🚨", label: "Code Blue", desc: "Score 100% on an emergency medicine quiz" },
];

export const MEDICAL_TABS = [
  "today", "practice", "clinical-cases", "osce", "aitutor", "drug-ref", "lab-values", "analytics", "research-hub",
];

export const MEDICAL_TAB_LABELS = {
  today: "🏠 Home",
  practice: "📚 Q-Bank",
  "clinical-cases": "🩺 Clinical Cases",
  osce: "🏥 OSCE Prep",
  aitutor: "🤖 AI Tutor",
  "drug-ref": "💊 Drug Reference",
  "lab-values": "🧪 Lab Values",
  analytics: "📊 Progress",
  "research-hub": "📁 My Circle",
  classroom: "🏫 Classroom",
  bank: "🏦 Question Bank",
  flashcards: "🃏 Flashcards",
  lecturers: "👨‍⚕️ Clinicians",
  leaderboard: "🏆 Leaderboard",
  gamification: "⚔️ Arena",
  studygroups: "👥 Study Groups",
  notes: "📝 Notes",
  achievements: "🏅 Badges",
  timetable: "🗓️ Schedule",
  discuss: "💬 Discussion",
  settings: "⚙️ Settings",
  profile: "👤 Profile",
  notifications: "🔔 Notifications",
  "teacher-questions": "📝 My Questions",
  "campus-comm": "📢 Announcements",
  premium: "💎 Premium",
  "medical-calculators": "🧮 Med Calculators",
};
