/**
 * Comprehensive list of Nigerian tertiary institutions.
 * type: "university" | "polytechnic" | "college"
 * Mirror of src/lib/nigerianInstitutions.js (frontend) — server deploys
 * standalone to Railway so it cannot import from src/.
 */
export const NIGERIAN_INSTITUTIONS = [
  // ── Federal Universities ───────────────────────────────────────────
  { name: "Ahmadu Bello University", type: "university", city: "Zaria" },
  { name: "University of Abuja", type: "university", city: "Gwagwalada" },
  { name: "Bayero University, Kano", type: "university", city: "Kano" },
  { name: "University of Benin", type: "university", city: "Benin City" },
  { name: "University of Calabar", type: "university", city: "Calabar" },
  { name: "University of Ibadan", type: "university", city: "Ibadan" },
  { name: "University of Ilorin", type: "university", city: "Ilorin" },
  { name: "University of Jos", type: "university", city: "Jos" },
  { name: "University of Lagos", type: "university", city: "Lagos" },
  { name: "University of Maiduguri", type: "university", city: "Maiduguri" },
  { name: "University of Nigeria, Nsukka", type: "university", city: "Nsukka" },
  { name: "University of Port Harcourt", type: "university", city: "Port Harcourt" },
  { name: "University of Uyo", type: "university", city: "Uyo" },
  { name: "Usmanu Danfodiyo University", type: "university", city: "Sokoto" },
  { name: "Nnamdi Azikiwe University", type: "university", city: "Awka" },
  { name: "Obafemi Awolowo University", type: "university", city: "Ile-Ife" },
  { name: "University of Africa, Toru-Orua", type: "university", city: "Toru-Orua" },
  { name: "National Open University of Nigeria", type: "university", city: "Abuja" },
  { name: "Nigerian Defence Academy", type: "university", city: "Kaduna" },
  { name: "Nigeria Police Academy", type: "university", city: "Wudil" },
  { name: "Nigerian Maritime University", type: "university", city: "Okerenkoko" },
  { name: "Nigerian Army University", type: "university", city: "Biu" },
  { name: "Air Force Institute of Technology", type: "university", city: "Kaduna" },
  { name: "Admiralty University of Nigeria", type: "university", city: "Ibusa" },
  { name: "Federal University of Technology, Akure", type: "university", city: "Akure" },
  { name: "Federal University of Technology, Minna", type: "university", city: "Minna" },
  { name: "Federal University of Technology, Owerri", type: "university", city: "Owerri" },
  { name: "Federal University of Technology, Babura", type: "university", city: "Babura" },
  { name: "Federal University of Technology, Ikot Abasi", type: "university", city: "Ikot Abasi" },
  { name: "Federal University of Agriculture, Abeokuta", type: "university", city: "Abeokuta" },
  { name: "Joseph Sarwuan Tarka University, Makurdi", type: "university", city: "Makurdi" },
  { name: "Michael Okpara University of Agriculture", type: "university", city: "Umudike" },
  { name: "Federal University of Petroleum Resources", type: "university", city: "Effurun" },
  { name: "Federal University of Health Sciences, Azare", type: "university", city: "Azare" },
  { name: "Federal University of Health Sciences, Ila-Orangun", type: "university", city: "Ila-Orangun" },
  { name: "Federal University of Health Sciences, Otukpo", type: "university", city: "Otukpo" },
  { name: "Federal University of Health Sciences, Kwale", type: "university", city: "Kwale" },
  { name: "David Umahi Federal University of Health Sciences", type: "university", city: "Uburu" },
  { name: "Federal University of Transportation", type: "university", city: "Daura" },
  { name: "Federal University, Birnin Kebbi", type: "university", city: "Birnin Kebbi" },
  { name: "Federal University, Dutse", type: "university", city: "Dutse" },
  { name: "Federal University, Dutsin-Ma", type: "university", city: "Dutsin-Ma" },
  { name: "Federal University, Gashua", type: "university", city: "Gashua" },
  { name: "Federal University, Gusau", type: "university", city: "Gusau" },
  { name: "Federal University, Kashere", type: "university", city: "Kashere" },
  { name: "Federal University, Lafia", type: "university", city: "Lafia" },
  { name: "Federal University, Lokoja", type: "university", city: "Lokoja" },
  { name: "Alex Ekwueme Federal University, Ndufu-Alike", type: "university", city: "Ndufu-Alike" },
  { name: "Federal University, Otuoke", type: "university", city: "Otuoke" },
  { name: "Federal University, Oye-Ekiti", type: "university", city: "Oye-Ekiti" },
  { name: "Federal University, Wukari", type: "university", city: "Wukari" },
  { name: "Adeyemi Federal University of Education", type: "university", city: "Ondo" },
  { name: "Alvan Ikoku Federal University of Education", type: "university", city: "Owerri" },

  // ── State Universities ─────────────────────────────────────────────
  { name: "Abia State University", type: "university", city: "Uturu" },
  { name: "Adamawa State University", type: "university", city: "Mubi" },
  { name: "Akwa Ibom State University", type: "university", city: "Ikot Akpaden" },
  { name: "Ambrose Alli University", type: "university", city: "Ekpoma" },
  { name: "Bauchi State University", type: "university", city: "Gadau" },
  { name: "Bayelsa Medical University", type: "university", city: "Yenagoa" },
  { name: "Benue State University", type: "university", city: "Makurdi" },
  { name: "Borno State University", type: "university", city: "Maiduguri" },
  { name: "Bukar Abba Ibrahim University", type: "university", city: "Damaturu" },
  { name: "Chukwuemeka Odumegwu Ojukwu University", type: "university", city: "Uli" },
  { name: "Cross River University of Technology", type: "university", city: "Calabar" },
  { name: "Delta State University, Abraka", type: "university", city: "Abraka" },
  { name: "Delta State University of Science and Technology", type: "university", city: "Ozoro" },
  { name: "Dennis Osadebay University", type: "university", city: "Asaba" },
  { name: "University of Delta", type: "university", city: "Agbor" },
  { name: "Ebonyi State University", type: "university", city: "Abakaliki" },
  { name: "Edo State University, Uzairue", type: "university", city: "Iyamho" },
  { name: "Ekiti State University", type: "university", city: "Ado-Ekiti" },
  { name: "Enugu State University of Science and Technology", type: "university", city: "Enugu" },
  { name: "Enugu State University of Medical and Applied Sciences", type: "university", city: "Igbo-Eno" },
  { name: "Gombe State University", type: "university", city: "Gombe" },
  { name: "Gombe State University of Science and Technology", type: "university", city: "Kumo" },
  { name: "Ibrahim Badamasi Babangida University", type: "university", city: "Lapai" },
  { name: "Ignatius Ajuru University of Education", type: "university", city: "Port Harcourt" },
  { name: "Imo State University", type: "university", city: "Owerri" },
  { name: "Kaduna State University", type: "university", city: "Kaduna" },
  { name: "Kano University of Science and Technology", type: "university", city: "Wudil" },
  { name: "Kebbi State University of Science and Technology", type: "university", city: "Aliero" },
  { name: "Prince Abubakar Audu University", type: "university", city: "Anyigba" },
  { name: "Kogi State University, Kabba", type: "university", city: "Kabba" },
  { name: "Confluence University of Science and Technology", type: "university", city: "Osara" },
  { name: "Kwara State University", type: "university", city: "Malete" },
  { name: "Ladoke Akintola University of Technology", type: "university", city: "Ogbomoso" },
  { name: "Lagos State University", type: "university", city: "Ojo" },
  { name: "Lagos State University of Science and Technology", type: "university", city: "Ikorodu" },
  { name: "Lagos State University of Education", type: "university", city: "Epe" },
  { name: "Nasarawa State University, Keffi", type: "university", city: "Keffi" },
  { name: "Niger Delta University", type: "university", city: "Amassoma" },
  { name: "Olabisi Onabanjo University", type: "university", city: "Ago-Iwoye" },
  { name: "Olusegun Agagu University of Science and Technology", type: "university", city: "Okitipupa" },
  { name: "Osun State University", type: "university", city: "Osogbo" },
  { name: "Plateau State University", type: "university", city: "Bokkos" },
  { name: "Rivers State University", type: "university", city: "Port Harcourt" },
  { name: "Sokoto State University", type: "university", city: "Sokoto" },
  { name: "Sule Lamido University", type: "university", city: "Kafin Hausa" },
  { name: "Tai Solarin University of Education", type: "university", city: "Ijebu-Ode" },
  { name: "Taraba State University", type: "university", city: "Jalingo" },
  { name: "Technical University, Ibadan", type: "university", city: "Ibadan" },
  { name: "Umaru Musa Yar'adua University", type: "university", city: "Katsina" },
  { name: "University of Medical Sciences, Ondo", type: "university", city: "Ondo" },
  { name: "University of Ilesa", type: "university", city: "Ilesa" },
  { name: "Yusuf Maitama Sule University", type: "university", city: "Kano" },
  { name: "Sa'adatu Rimi University of Education", type: "university", city: "Kano" },
  { name: "Emmanuel Alayande University of Education", type: "university", city: "Oyo" },
  { name: "Bamidele Olumilua University of Education, Science and Technology", type: "university", city: "Ikere-Ekiti" },
  { name: "Shehu Shagari University of Education", type: "university", city: "Sokoto" },
  { name: "Zamfara State University", type: "university", city: "Talata Mafara" },
  { name: "King David University of Medical Sciences", type: "university", city: "Uburu" },

  // ── Private Universities ───────────────────────────────────────────
  { name: "Achievers University", type: "university", city: "Owo" },
  { name: "Adeleke University", type: "university", city: "Ede" },
  { name: "Afe Babalola University", type: "university", city: "Ado-Ekiti" },
  { name: "Ahman Pategi University", type: "university", city: "Patigi" },
  { name: "Ajayi Crowther University", type: "university", city: "Oyo" },
  { name: "Al-Hikmah University", type: "university", city: "Ilorin" },
  { name: "Al-Qalam University", type: "university", city: "Katsina" },
  { name: "Al-Ansar University", type: "university", city: "Maiduguri" },
  { name: "Al-Istiqama University", type: "university", city: "Kano" },
  { name: "American University of Nigeria", type: "university", city: "Yola" },
  { name: "Anchor University", type: "university", city: "Lagos" },
  { name: "Arthur Jarvis University", type: "university", city: "Akpabuyo" },
  { name: "Atiba University", type: "university", city: "Oyo" },
  { name: "Augustine University", type: "university", city: "Ilara" },
  { name: "Ave Maria University", type: "university", city: "Piyanko" },
  { name: "Babcock University", type: "university", city: "Ilishan-Remo" },
  { name: "Baze University", type: "university", city: "Abuja" },
  { name: "Bells University of Technology", type: "university", city: "Ota" },
  { name: "Benson Idahosa University", type: "university", city: "Benin City" },
  { name: "Bingham University", type: "university", city: "Karu" },
  { name: "Bowen University", type: "university", city: "Iwo" },
  { name: "British Canadian University", type: "university", city: "Obudu" },
  { name: "Caleb University", type: "university", city: "Imota" },
  { name: "Capital City University", type: "university", city: "Kano" },
  { name: "Caritas University", type: "university", city: "Enugu" },
  { name: "Chrisland University", type: "university", city: "Abeokuta" },
  { name: "Christopher University", type: "university", city: "Mowe" },
  { name: "Claretian University of Nigeria", type: "university", city: "Nekede" },
  { name: "Clifford University", type: "university", city: "Owerrinta" },
  { name: "Coal City University", type: "university", city: "Enugu" },
  { name: "Covenant University", type: "university", city: "Ota" },
  { name: "Crawford University", type: "university", city: "Igbesa" },
  { name: "Crescent University", type: "university", city: "Abeokuta" },
  { name: "Dominican University", type: "university", city: "Ibadan" },
  { name: "Edwin Clark University", type: "university", city: "Kiagbodo" },
  { name: "Elizade University", type: "university", city: "Ilara-Mokin" },
  { name: "European University of Nigeria", type: "university", city: "Duboyi" },
  { name: "Evangel University", type: "university", city: "Akaeze" },
  { name: "First Technical University", type: "university", city: "Ibadan" },
  { name: "Fountain University", type: "university", city: "Osogbo" },
  { name: "Godfrey Okoye University", type: "university", city: "Enugu" },
  { name: "Greenfield University", type: "university", city: "Kaduna" },
  { name: "Gregory University", type: "university", city: "Uturu" },
  { name: "Hallmark University", type: "university", city: "Ijebu-Itele" },
  { name: "Havilla University", type: "university", city: "Nde-Ikom" },
  { name: "Hezekiah University", type: "university", city: "Umudi" },
  { name: "Igbinedion University", type: "university", city: "Okada" },
  { name: "James Hope University", type: "university", city: "Lagos" },
  { name: "Joseph Ayo Babalola University", type: "university", city: "Ikeji-Arakeji" },
  { name: "Karl-Kumm University", type: "university", city: "Vom" },
  { name: "Kings University", type: "university", city: "Odeomu" },
  { name: "Koladaisi University", type: "university", city: "Ibadan" },
  { name: "Kwararafa University", type: "university", city: "Wukari" },
  { name: "Landmark University", type: "university", city: "Omu-Aran" },
  { name: "Lead City University", type: "university", city: "Ibadan" },
  { name: "Legacy University", type: "university", city: "Okija" },
  { name: "Madonna University", type: "university", city: "Elele" },
  { name: "Maryam Abacha American University of Nigeria", type: "university", city: "Kano" },
  { name: "McPherson University", type: "university", city: "Seriki Sotayo" },
  { name: "Mewar International University", type: "university", city: "Masaka" },
  { name: "Michael and Cecilia Ibru University", type: "university", city: "Ughelli" },
  { name: "Mountain Top University", type: "university", city: "Magboro" },
  { name: "Mudiame University", type: "university", city: "Irrua" },
  { name: "Nile University of Nigeria", type: "university", city: "Abuja" },
  { name: "NOK University", type: "university", city: "Kachia" },
  { name: "NorthWest University", type: "university", city: "Sokoto" },
  { name: "Novena University", type: "university", city: "Ogume" },
  { name: "Obong University", type: "university", city: "Obong Ntak" },
  { name: "Oduduwa University", type: "university", city: "Ile-Ife" },
  { name: "PAMO University of Medical Sciences", type: "university", city: "Port Harcourt" },
  { name: "Pan-Atlantic University", type: "university", city: "Lagos" },
  { name: "Paul University", type: "university", city: "Awka" },
  { name: "Peter University", type: "university", city: "Achina" },
  { name: "Precious Cornerstone University", type: "university", city: "Ibadan" },
  { name: "Redeemer's University", type: "university", city: "Ede" },
  { name: "Renaissance University", type: "university", city: "Enugu" },
  { name: "Rhema University", type: "university", city: "Aba" },
  { name: "Ritman University", type: "university", city: "Ikot Ekpene" },
  { name: "Salem University", type: "university", city: "Lokoja" },
  { name: "Samuel Adegboyega University", type: "university", city: "Ogwa" },
  { name: "Shanahan University", type: "university", city: "Onitsha" },
  { name: "Skyline University Nigeria", type: "university", city: "Kano" },
  { name: "Southwestern University", type: "university", city: "Okun-Owa" },
  { name: "Summit University", type: "university", city: "Offa" },
  { name: "Tansian University", type: "university", city: "Umunya" },
  { name: "Thomas Adewumi University", type: "university", city: "Oko-Irese" },
  { name: "Trinity University", type: "university", city: "Lagos" },
  { name: "University of Mkar", type: "university", city: "Mkar" },
  { name: "Veritas University", type: "university", city: "Abuja" },
  { name: "Wellspring University", type: "university", city: "Benin City" },
  { name: "Wesley University", type: "university", city: "Ondo" },
  { name: "Western Delta University", type: "university", city: "Oghara" },
  { name: "Westland University", type: "university", city: "Iwo" },
  { name: "Wigwe University", type: "university", city: "Isiokpo" },

  // ── Federal Polytechnics & Colleges of Technology ─────────────────
  { name: "Auchi Polytechnic", type: "polytechnic", city: "Auchi" },
  { name: "Federal Polytechnic, Ado-Ekiti", type: "polytechnic", city: "Ado-Ekiti" },
  { name: "Federal Polytechnic, Ayede", type: "polytechnic", city: "Ayede" },
  { name: "Federal Polytechnic, Bali", type: "polytechnic", city: "Bali" },
  { name: "Federal Polytechnic, Bauchi", type: "polytechnic", city: "Bauchi" },
  { name: "Federal Polytechnic, Bida", type: "polytechnic", city: "Bida" },
  { name: "Federal Polytechnic, Damaturu", type: "polytechnic", city: "Damaturu" },
  { name: "Federal Polytechnic, Daura", type: "polytechnic", city: "Daura" },
  { name: "Federal Polytechnic, Ede", type: "polytechnic", city: "Ede" },
  { name: "Federal Polytechnic, Ekowe", type: "polytechnic", city: "Ekowe" },
  { name: "Federal Polytechnic, Idah", type: "polytechnic", city: "Idah" },
  { name: "Federal Polytechnic, Ilaro", type: "polytechnic", city: "Ilaro" },
  { name: "Federal Polytechnic, Ile-Oluji", type: "polytechnic", city: "Ile-Oluji" },
  { name: "Federal Polytechnic, Kaltungo", type: "polytechnic", city: "Kaltungo" },
  { name: "Federal Polytechnic, Kaura Namoda", type: "polytechnic", city: "Kaura Namoda" },
  { name: "Federal Polytechnic, Monguno", type: "polytechnic", city: "Monguno" },
  { name: "Federal Polytechnic, Mubi", type: "polytechnic", city: "Mubi" },
  { name: "Federal Polytechnic, Nassarawa", type: "polytechnic", city: "Nassarawa" },
  { name: "Federal Polytechnic, Nekede", type: "polytechnic", city: "Owerri" },
  { name: "Federal Polytechnic, Offa", type: "polytechnic", city: "Offa" },
  { name: "Federal Polytechnic, Ohodo", type: "polytechnic", city: "Ohodo" },
  { name: "Federal Polytechnic, Oko", type: "polytechnic", city: "Oko" },
  { name: "Federal Polytechnic, Ugep", type: "polytechnic", city: "Ugep" },
  { name: "Federal Polytechnic, Ukana", type: "polytechnic", city: "Ukana" },
  { name: "Federal Polytechnic, Wannune", type: "polytechnic", city: "Wannune" },
  { name: "Federal Polytechnic of Oil and Gas, Bonny", type: "polytechnic", city: "Bonny" },
  { name: "Hussaini Adamu Federal Polytechnic", type: "polytechnic", city: "Kazaure" },
  { name: "Kaduna Polytechnic", type: "polytechnic", city: "Kaduna" },
  { name: "Nigerian Army Institute of Technology", type: "polytechnic", city: "Makurdi" },
  { name: "Petroleum Training Institute", type: "polytechnic", city: "Effurun" },
  { name: "Waziri Umaru Federal Polytechnic", type: "polytechnic", city: "Birnin Kebbi" },
  { name: "Yaba College of Technology", type: "polytechnic", city: "Lagos" },

  // ── State Polytechnics ─────────────────────────────────────────────
  { name: "Abdul-Gusau Polytechnic", type: "polytechnic", city: "Talata Mafara" },
  { name: "Abia State Polytechnic", type: "polytechnic", city: "Aba" },
  { name: "Abraham Adesanya Polytechnic", type: "polytechnic", city: "Ijebu-Igbo" },
  { name: "Adamawa State Polytechnic", type: "polytechnic", city: "Yola" },
  { name: "Akwa Ibom State Polytechnic", type: "polytechnic", city: "Ikot Osurua" },
  { name: "Benue State Polytechnic", type: "polytechnic", city: "Ugbokolo" },
  { name: "Captain Elechi Amadi Polytechnic", type: "polytechnic", city: "Port Harcourt" },
  { name: "Delta State Polytechnic, Ogwashi-Uku", type: "polytechnic", city: "Ogwashi-Uku" },
  { name: "Delta State Polytechnic, Otefe-Oghara", type: "polytechnic", city: "Otefe-Oghara" },
  { name: "Delta State Polytechnic, Ozoro", type: "polytechnic", city: "Ozoro" },
  { name: "D.S. Adegbenro ICT Polytechnic", type: "polytechnic", city: "Itori" },
  { name: "Edo State Polytechnic", type: "polytechnic", city: "Usen" },
  { name: "Enugu State Polytechnic", type: "polytechnic", city: "Iwollo" },
  { name: "Gateway ICT Polytechnic", type: "polytechnic", city: "Saapade" },
  { name: "Gombe State Polytechnic", type: "polytechnic", city: "Bajoga" },
  { name: "Hassan Usman Katsina Polytechnic", type: "polytechnic", city: "Katsina" },
  { name: "Imo State Polytechnic", type: "polytechnic", city: "Umuagwo" },
  { name: "Institute of Management and Technology", type: "polytechnic", city: "Enugu" },
  { name: "Jigawa State Polytechnic", type: "polytechnic", city: "Dutse" },
  { name: "Kano State Polytechnic", type: "polytechnic", city: "Kano" },
  { name: "Kebbi State Polytechnic", type: "polytechnic", city: "Dakingari" },
  { name: "Ken Saro-Wiwa Polytechnic", type: "polytechnic", city: "Bori" },
  { name: "Kogi State Polytechnic", type: "polytechnic", city: "Lokoja" },
  { name: "Kwara State Polytechnic", type: "polytechnic", city: "Ilorin" },
  { name: "Moshood Abiola Polytechnic", type: "polytechnic", city: "Abeokuta" },
  { name: "Nasarawa State Polytechnic", type: "polytechnic", city: "Lafia" },
  { name: "Niger State Polytechnic", type: "polytechnic", city: "Zungeru" },
  { name: "Nuhu Bamalli Polytechnic", type: "polytechnic", city: "Zaria" },
  { name: "Ogun State Institute of Technology", type: "polytechnic", city: "Igbesa" },
  { name: "Osun State College of Technology", type: "polytechnic", city: "Esa-Oke" },
  { name: "Osun State Polytechnic", type: "polytechnic", city: "Iree" },
  { name: "Oyo State College of Agriculture and Technology", type: "polytechnic", city: "Igboora" },
  { name: "Plateau State Polytechnic", type: "polytechnic", city: "Barkin Ladi" },
  { name: "Ramat Polytechnic", type: "polytechnic", city: "Maiduguri" },
  { name: "Rufus Giwa Polytechnic", type: "polytechnic", city: "Owo" },
  { name: "Sokoto State Polytechnic", type: "polytechnic", city: "Sokoto" },
  { name: "Taraba State Polytechnic", type: "polytechnic", city: "Jalingo" },
  { name: "The Polytechnic, Ibadan", type: "polytechnic", city: "Ibadan" },

  // ── Private Polytechnics ───────────────────────────────────────────
  { name: "Allover Central Polytechnic", type: "polytechnic", city: "Ota" },
  { name: "Best Solution Polytechnic", type: "polytechnic", city: "Akure" },
  { name: "Bolmor Polytechnic", type: "polytechnic", city: "Ibadan" },
  { name: "Calvary Polytechnic", type: "polytechnic", city: "Owo" },
  { name: "Citi Polytechnic", type: "polytechnic", city: "Abuja" },
  { name: "Covenant Polytechnic", type: "polytechnic", city: "Aba" },
  { name: "Crown Polytechnic", type: "polytechnic", city: "Ado-Ekiti" },
  { name: "Dorben Polytechnic", type: "polytechnic", city: "Abuja" },
  { name: "Eastern Polytechnic", type: "polytechnic", city: "Port Harcourt" },
  { name: "Fidei Polytechnic", type: "polytechnic", city: "Gboko" },
  { name: "Grace Polytechnic", type: "polytechnic", city: "Surulere" },
  { name: "Graceland Polytechnic", type: "polytechnic", city: "Offa" },
  { name: "Heritage Polytechnic", type: "polytechnic", city: "Ikot Udota" },
  { name: "Ibadan City Polytechnic", type: "polytechnic", city: "Ibadan" },
  { name: "Igbajo Polytechnic", type: "polytechnic", city: "Igbajo" },
  { name: "Interlink Polytechnic", type: "polytechnic", city: "Ijebu-Jesa" },
  { name: "Kings Polytechnic", type: "polytechnic", city: "Ubiaja" },
  { name: "Lagos City Polytechnic", type: "polytechnic", city: "Ikeja" },
  { name: "Nacabs Polytechnic", type: "polytechnic", city: "Akwanga" },
  { name: "Nogak Polytechnic", type: "polytechnic", city: "Ikom" },
  { name: "Redeemers College of Technology and Management", type: "polytechnic", city: "Mowe" },
  { name: "Ronik Polytechnic", type: "polytechnic", city: "Lagos" },
  { name: "Shaka Polytechnic", type: "polytechnic", city: "Benin City" },
  { name: "Sure Foundation Polytechnic", type: "polytechnic", city: "Ikot Akai" },
  { name: "Temple Gate Polytechnic", type: "polytechnic", city: "Aba" },
  { name: "Tower Polytechnic", type: "polytechnic", city: "Ibadan" },
  { name: "Uma Ukpai Polytechnic", type: "polytechnic", city: "Asaga" },
  { name: "Valley View Polytechnic", type: "polytechnic", city: "Ohafia" },
  { name: "Wolex Polytechnic", type: "polytechnic", city: "Lagos" },

  // ── Colleges of Health Sciences, Schools of Nursing & Midwifery ────
  { name: "College of Health Technology, Calabar", type: "college", city: "Calabar" },
  { name: "Kwara State College of Health Technology", type: "college", city: "Offa" },
  { name: "Lagos State College of Health Technology", type: "college", city: "Yaba" },
  { name: "Ogun State College of Health Technology", type: "college", city: "Ilese-Ijebu" },
  { name: "Oyo State College of Health Science and Technology", type: "college", city: "Ibadan" },
  { name: "School of Health Technology, Aluu", type: "college", city: "Port Harcourt" },
  { name: "School of Health Technology, Jahun", type: "college", city: "Jahun" },
  { name: "School of Health Technology, Kankia", type: "college", city: "Kankia" },
  { name: "School of Health Technology, Makarfi", type: "college", city: "Zaria" },
  { name: "Federal College of Dental Technology and Therapy", type: "college", city: "Enugu" },
  { name: "Federal School of Occupational Therapy", type: "college", city: "Yaba" },
  { name: "Nigerian Army College of Nursing", type: "college", city: "Yaba" },
  { name: "School of Nursing, ABU Teaching Hospital", type: "college", city: "Zaria" },
  { name: "School of Nursing, University of Benin Teaching Hospital", type: "college", city: "Benin City" },
  { name: "School of Nursing, University College Hospital", type: "college", city: "Ibadan" },
  { name: "School of Nursing, Lagos University Teaching Hospital", type: "college", city: "Idi-Araba" },
  { name: "School of Nursing, Obafemi Awolowo University Teaching Hospital", type: "college", city: "Ile-Ife" },
  { name: "School of Nursing, University of Nigeria Teaching Hospital", type: "college", city: "Enugu" },
  { name: "School of Nursing, University of Ilorin Teaching Hospital", type: "college", city: "Ilorin" },
  { name: "School of Nursing, Jos University Teaching Hospital", type: "college", city: "Jos" },
  { name: "School of Nursing, Abeokuta", type: "college", city: "Abeokuta" },
  { name: "School of Nursing, Akure", type: "college", city: "Akure" },
  { name: "School of Nursing, Asaba", type: "college", city: "Asaba" },
  { name: "School of Nursing, Bauchi", type: "college", city: "Bauchi" },
  { name: "School of Nursing, Benin City", type: "college", city: "Benin City" },
  { name: "School of Nursing, Birnin Kudu", type: "college", city: "Birnin Kudu" },
  { name: "School of Nursing, Calabar", type: "college", city: "Calabar" },
  { name: "School of Nursing, Eleyele", type: "college", city: "Ibadan" },
  { name: "School of Nursing, Gusau", type: "college", city: "Gusau" },
  { name: "School of Nursing, Ijebu-Ode", type: "college", city: "Ijebu-Ode" },
  { name: "School of Nursing, Ilaro", type: "college", city: "Ilaro" },
  { name: "School of Nursing, Jalingo", type: "college", city: "Jalingo" },
  { name: "School of Nursing, Kano", type: "college", city: "Kano" },
  { name: "School of Nursing, Katsina", type: "college", city: "Katsina" },
  { name: "School of Nursing, Lafia", type: "college", city: "Lafia" },
  { name: "School of Nursing, Maiduguri", type: "college", city: "Maiduguri" },
  { name: "School of Nursing, Makurdi", type: "college", city: "Makurdi" },
  { name: "School of Nursing, Obangede", type: "college", city: "Obangede" },
  { name: "School of Nursing, Owerri", type: "college", city: "Owerri" },
  { name: "School of Nursing, Port Harcourt", type: "college", city: "Port Harcourt" },
  { name: "School of Nursing, Sokoto", type: "college", city: "Sokoto" },
  { name: "School of Nursing, Umuahia", type: "college", city: "Umuahia" },
  { name: "School of Nursing, Uyo", type: "college", city: "Uyo" },
  { name: "School of Nursing, Vom", type: "college", city: "Vom" },
  { name: "School of Nursing, Warri", type: "college", city: "Warri" },
  { name: "School of Nursing, Yenagoa", type: "college", city: "Yenagoa" },
  { name: "School of Nursing, Yola", type: "college", city: "Yola" },
  { name: "School of Midwifery, Asaba", type: "college", city: "Asaba" },
  { name: "School of Midwifery, Benin City", type: "college", city: "Benin City" },
  { name: "School of Midwifery, Lagos", type: "college", city: "Lagos" },
  { name: "School of Psychiatric Nursing, Aro", type: "college", city: "Abeokuta" },
  { name: "School of Psychiatric Nursing, Yaba", type: "college", city: "Yaba" },
  { name: "College of Nursing Sciences, Amichi", type: "college", city: "Amichi" },
  { name: "Ekiti State College of Nursing", type: "college", city: "Ado-Ekiti" },
  { name: "Osun State College of Nursing", type: "college", city: "Osogbo" },
  { name: "ECWA School of Nursing", type: "college", city: "Egbe" },

  // ── Colleges of Education ──────────────────────────────────────────
  { name: "Abia State College of Education", type: "college", city: "Arochukwu" },
  { name: "Adamu Augie College of Education", type: "college", city: "Argungu" },
  { name: "Adamu Tafawa Balewa College of Education", type: "college", city: "Kangere" },
  { name: "Akwa Ibom State College of Education", type: "college", city: "Afaha Nsit" },
  { name: "Aminu Saleh College of Education", type: "college", city: "Azare" },
  { name: "College of Education, Agbor", type: "college", city: "Agbor" },
  { name: "College of Education, Akamkpa", type: "college", city: "Akamkpa" },
  { name: "College of Education, Akwanga", type: "college", city: "Akwanga" },
  { name: "College of Education, Billiri", type: "college", city: "Billiri" },
  { name: "College of Education, Ekiadolor", type: "college", city: "Benin City" },
  { name: "College of Education, Gindiri", type: "college", city: "Gindiri" },
  { name: "College of Education, Ikwo", type: "college", city: "Ikwo" },
  { name: "College of Education, Ila-Orangun", type: "college", city: "Ila-Orangun" },
  { name: "College of Education, Ilesa", type: "college", city: "Ilesa" },
  { name: "College of Education, Jalingo", type: "college", city: "Jalingo" },
  { name: "College of Education, Maru", type: "college", city: "Maru" },
  { name: "College of Education, Minna", type: "college", city: "Minna" },
  { name: "College of Education, Oju", type: "college", city: "Oju" },
  { name: "College of Education, Warri", type: "college", city: "Warri" },
  { name: "College of Education, Waka-Biu", type: "college", city: "Biu" },
  { name: "Enugu State College of Education (Technical)", type: "college", city: "Enugu" },
  { name: "FCT College of Education", type: "college", city: "Zuba" },
  { name: "Federal College of Education, Abeokuta", type: "college", city: "Abeokuta" },
  { name: "Federal College of Education (Special), Oyo", type: "college", city: "Oyo" },
  { name: "Federal College of Education (Technical), Akoka", type: "college", city: "Lagos" },
  { name: "Federal College of Education (Technical), Asaba", type: "college", city: "Asaba" },
  { name: "Federal College of Education (Technical), Gombe", type: "college", city: "Gombe" },
  { name: "Federal College of Education (Technical), Gusau", type: "college", city: "Gusau" },
  { name: "Federal College of Education (Technical), Omoku", type: "college", city: "Omoku" },
  { name: "Federal College of Education (Technical), Potiskum", type: "college", city: "Potiskum" },
  { name: "Federal College of Education (Technical), Umunze", type: "college", city: "Umunze" },
  { name: "Federal College of Education, Eha-Amufu", type: "college", city: "Eha-Amufu" },
  { name: "Federal College of Education, Kano", type: "college", city: "Kano" },
  { name: "Federal College of Education, Katsina", type: "college", city: "Katsina" },
  { name: "Federal College of Education, Kontagora", type: "college", city: "Kontagora" },
  { name: "Federal College of Education, Obudu", type: "college", city: "Obudu" },
  { name: "Federal College of Education, Okene", type: "college", city: "Okene" },
  { name: "Federal College of Education, Yola", type: "college", city: "Yola" },
  { name: "Federal College of Education, Zaria", type: "college", city: "Zaria" },
  { name: "Isah Kaita College of Education", type: "college", city: "Dutsin-Ma" },
  { name: "Jigawa State College of Education", type: "college", city: "Gumel" },
  { name: "Kaduna State College of Education", type: "college", city: "Gidan Waya" },
  { name: "Kashim Ibrahim College of Education", type: "college", city: "Maiduguri" },
  { name: "Kwara State College of Education", type: "college", city: "Ilorin" },
  { name: "Michael Otedola College of Primary Education", type: "college", city: "Noforija" },
  { name: "Mufutau Lanihun College of Education", type: "college", city: "Ibadan" },
  { name: "Nwafor Orizu College of Education", type: "college", city: "Nsugbe" },
  { name: "Shehu Shagari College of Education", type: "college", city: "Sokoto" },
  { name: "Umar Suleiman College of Education", type: "college", city: "Gashua" },
];
