const fs = require('fs');
const q = [
{"n":1,"q":"Vertebrates belong to which Sub-Phylum?","o":["A. Vertebrata (Craniata)","B. Urochordata","C. Cephalochordata","D. Hemichordata"],"a":"A. Vertebrata (Craniata)","e":"Vertebrates are placed in the Sub-Phylum Vertebrata, also called Craniata because they possess a cranium (brain box). They are the most advanced group of animals in Phylum Chordata."},
{"n":2,"q":"Which structure replaces the notochord in adult vertebrates?","o":["A. Vertebral column (backbone)","B. Cranium","C. Spinal cord","D. Exoskeleton"],"a":"A. Vertebral column (backbone)","e":"In vertebrates, the vertebral column (backbone) made of vertebrae replaces the notochord. The notochord is only present during the embryonic stage."},
{"n":3,"q":"The heart of Class Pisces (bony fishes) has how many chambers?","o":["A. Two chambers","B. Three chambers","C. Four chambers","D. One chamber"],"a":"A. Two chambers","e":"Fishes have a two-chambered heart consisting of one atrium and one ventricle. This is a key distinguishing feature compared to amphibians (3) and birds/mammals (4)."},
{"n":4,"q":"What organ in bony fishes controls buoyancy?","o":["A. Swim bladder","B. Lateral line","C. Operculum","D. Ampullae of Lorenzini"],"a":"A. Swim bladder","e":"The swim bladder in bony fishes controls buoyancy by regulating the amount of gas inside it, allowing the fish to rise or sink to different depths without expending energy."},
{"n":5,"q":"Class Amphibia are described as 'poikilothermic.' This means they are:","o":["A. Cold-blooded (body temperature varies with environment)","B. Warm-blooded (constant body temperature)","C. Semi-warm-blooded","D. Unable to thermoregulate completely"],"a":"A. Cold-blooded (body temperature varies with environment)","e":"Poikilothermic (also called ectothermic) means the animal's body temperature changes with the environmental temperature. Amphibians, fishes, and reptiles are all cold-blooded (poikilothermic)."},
{"n":6,"q":"Which type of fertilization occurs in most amphibians?","o":["A. External fertilization","B. Internal fertilization","C. Parthenogenesis","D. Self-fertilization"],"a":"A. External fertilization","e":"Most amphibians practice external fertilization, where eggs are fertilized outside the body, typically in water. This is why amphibians must return to water to reproduce."},
{"n":7,"q":"What is the larval stage of a frog called?","o":["A. Tadpole","B. Caterpillar","C. Nauplius","D. Nymph"],"a":"A. Tadpole","e":"The larval stage of a frog is called a tadpole. It is fully aquatic, breathes through gills, and has a tail. It undergoes metamorphosis to develop into the adult frog with lungs and limbs."},
{"n":8,"q":"Reptiles are described as 'fully terrestrial.' Which adaptation makes their eggs independent of water?","o":["A. Amniotic egg with leathery shell and protective membranes","B. External fertilization","C. Metamorphosis stage","D. Cutaneous respiration"],"a":"A. Amniotic egg with leathery shell and protective membranes","e":"The amniotic egg has protective membranes (amnion, chorion, allantois) and a leathery shell that prevents desiccation. This allows reptiles to reproduce on land without needing water."},
{"n":9,"q":"Which class of vertebrates has pneumatic (hollow) bones?","o":["A. Aves (Birds)","B. Mammalia","C. Reptilia","D. Amphibia"],"a":"A. Aves (Birds)","e":"Birds (Aves) have pneumatic bones containing air cavities. This significantly reduces body weight, making flight easier. The air spaces are connected to the air sac system."},
{"n":10,"q":"Which sub-group of mammals lays eggs instead of giving birth to live young?","o":["A. Monotremes","B. Marsupials","C. Placentals","D. Cetaceans"],"a":"A. Monotremes","e":"Monotremes are the only egg-laying mammals. Examples include the platypus and echidna. Most other mammals are either marsupials (give birth to very undeveloped young) or placentals (give birth to well-developed young)."},
{"n":11,"q":"What type of circulatory system do all vertebrates possess?","o":["A. Open circulatory system","B. Closed circulatory system with a ventral heart","C. Semi-closed circulatory system","D. No circulatory system"],"a":"B. Closed circulatory system with a ventral heart","e":"All vertebrates have a closed circulatory system where blood is confined within blood vessels. The heart is ventral (positioned on the underside), unlike invertebrates that may have dorsal hearts."},
{"n":12,"q":"In sharks, the skeleton is made of:","o":["A. Bone","B. Cartilage","C. Chitin","D. Calcium carbonate"],"a":"B. Cartilage","e":"Sharks belong to Class Chondrichthyes and have a cartilaginous skeleton (made of cartilage, not bone). Bony fishes (Class Osteichthyes) have skeletons made of bone."},
{"n":13,"q":"The lateral line system in fishes is used for:","o":["A. Digestion","B. Detecting water vibrations and pressure changes","C. Reproduction","D. Buoyancy regulation"],"a":"B. Detecting water vibrations and pressure changes","e":"The lateral line system is a sensory system found along the sides of fishes. It detects vibrations, pressure changes, and movement in the surrounding water, helping fish avoid predators and locate prey."},
{"n":14,"q":"Amphibians undergo which unique developmental process?","o":["A. Moulting","B. Metamorphosis","C. Parthenogenesis","D. Sporulation"],"a":"B. Metamorphosis","e":"Amphibians undergo metamorphosis — a remarkable transformation from the aquatic larval stage (tadpole with gills and tail) to the adult form (lungs and limbs). This is a defining characteristic of Class Amphibia."},
{"n":15,"q":"The tympanic membrane visible on a frog is functionally equivalent to what structure in humans?","o":["A. Nose","B. Eardrum","C. Eye lens","D. Throat"],"a":"B. Eardrum","e":"The tympanic membrane in frogs is equivalent to the human eardrum. It is a visible circular disc behind the eye that detects sound vibrations and is part of the frog's hearing apparatus."},
{"n":16,"q":"Reptiles maintain their body temperature mainly through:","o":["A. Internal metabolic heat (endothermy)","B. Behavioural thermoregulation (e.g., basking in sunlight)","C. Sweating","D. Shivering"],"a":"B. Behavioural thermoregulation (e.g., basking in sunlight)","e":"Although reptiles are ectothermic (cold-blooded), they regulate body temperature through behaviour — for example, basking in the sun to warm up or moving to shade to cool down. This is called behavioural thermoregulation."},
{"n":17,"q":"Birds respire using lungs AND which additional structures?","o":["A. Gills","B. Air sacs (double respiration system)","C. Swim bladder","D. Book lungs"],"a":"B. Air sacs (double respiration system)","e":"Birds have a highly efficient 'double respiration' system using lungs AND air sacs. Air flows through the lungs in one direction (unidirectional flow) during both inhalation and exhalation, making gas exchange very efficient for the high energy demands of flight."},
{"n":18,"q":"What is the function of the uropygial gland in birds?","o":["A. Digestion of food","B. Preening (waterproofing and maintaining feathers)","C. Flight control","D. Sound production"],"a":"B. Preening (waterproofing and maintaining feathers)","e":"The uropygial gland (preen gland) is located at the base of a bird's tail. Birds use their beak to spread oil from this gland over their feathers during preening, which waterproofs and maintains feather structure."},
{"n":19,"q":"Mammals are uniquely characterized by the presence of:","o":["A. Scales","B. Mammary glands that produce milk","C. Feathers","D. Two-chambered heart"],"a":"B. Mammary glands that produce milk","e":"The presence of mammary glands is the defining characteristic of Class Mammalia. These glands produce milk to nourish offspring, providing them with nutrition and immunity. This is unique to mammals."},
{"n":20,"q":"In mammals, what separates the thoracic and abdominal cavities?","o":["A. Sternum","B. Diaphragm","C. Ribcage","D. Pelvis"],"a":"B. Diaphragm","e":"The diaphragm is a muscular sheet that separates the thorax (chest cavity) from the abdomen. It plays a crucial role in breathing by contracting and relaxing to change the volume of the chest cavity, drawing air in and out of the lungs."},
{"n":21,"q":"Warm-blooded animals that maintain a constant body temperature are described as:","o":["A. Poikilothermic","B. Ectothermic","C. Homeothermic (endothermic)","D. Exothermic"],"a":"C. Homeothermic (endothermic)","e":"Homeothermic (or endothermic) animals maintain a constant internal body temperature regardless of the external environment. Birds and mammals are warm-blooded. This requires more energy but allows activity in varied climates."},
{"n":22,"q":"What is unique about the heart of crocodiles among reptiles?","o":["A. Two-chambered","B. Three-chambered","C. Four-chambered (like birds and mammals)","D. No heart"],"a":"C. Four-chambered (like birds and mammals)","e":"Unlike other reptiles that have a three-chambered heart with incomplete separation, crocodiles have a fully four-chambered heart, similar to birds and mammals. This is thought to be an evolutionary adaptation related to their active predatory lifestyle."},
{"n":23,"q":"Which sensory organ in sharks detects electric fields produced by prey?","o":["A. Lateral line","B. Olfactory bulb","C. Ampullae of Lorenzini","D. Operculum"],"a":"C. Ampullae of Lorenzini","e":"The ampullae of Lorenzini are electroreceptor organs found in sharks and related cartilaginous fishes. They detect weak electric fields generated by the muscle contractions of nearby animals, helping sharks locate hidden prey."},
{"n":24,"q":"The forelimbs of birds are modified into:","o":["A. Flippers","B. Claws","C. Wings","D. Tentacles"],"a":"C. Wings","e":"In birds (Aves), the forelimbs are modified into wings — one of their most distinctive adaptations for flight. The wing structure consists of modified bones comparable to the human arm but restructured for aerodynamic efficiency."},
{"n":25,"q":"Which type of dentition do mammals have, where different teeth have different shapes and functions?","o":["A. Homodont dentition","B. Acrodont dentition","C. Heterodont dentition","D. Pleurodont dentition"],"a":"C. Heterodont dentition","e":"Mammals have heterodont dentition — their teeth are of different types (incisors, canines, premolars, molars) each adapted for specific functions such as cutting, tearing, or grinding food. This is distinct from reptiles which have homodont dentition."},
{"n":26,"q":"Freshwater fishes deal with osmotic challenges by:","o":["A. Drinking lots of water and excreting little urine","B. Absorbing salt from the water","C. Producing large amounts of dilute urine","D. Excreting excess salt through gills only"],"a":"C. Producing large amounts of dilute urine","e":"Freshwater fishes live in a hypotonic environment (less salty than their bodies), so water constantly enters their bodies by osmosis. To compensate, they produce large volumes of very dilute urine to expel the excess water."},
{"n":27,"q":"Which feature is present only during the embryonic stage of vertebrates and is replaced in adults?","o":["A. Vertebral column","B. Cranium","C. Notochord","D. Spinal cord"],"a":"C. Notochord","e":"The notochord is a flexible rod-like structure present in all chordate embryos. In vertebrates, it is replaced by the vertebral column (backbone) as the animal matures. It only persists in adults as remnants between vertebral discs."},
{"n":28,"q":"What is 'cutaneous respiration' as seen in amphibians?","o":["A. Breathing through gills","B. Breathing through lungs","C. Gas exchange through the moist skin","D. Breathing through the mouth only"],"a":"C. Gas exchange through the moist skin","e":"Cutaneous respiration is the process of gas exchange (oxygen and carbon dioxide) through the skin. In amphibians, the moist, thin, glandular skin is richly supplied with blood vessels and serves as an important respiratory surface, especially during hibernation or underwater."},
{"n":29,"q":"Which class of vertebrates includes the first animals to transition from aquatic to terrestrial life?","o":["A. Pisces","B. Reptilia","C. Amphibia","D. Aves"],"a":"C. Amphibia","e":"Amphibia represents the first vertebrates to successfully live on land, making them a transitional group between fully aquatic (fish) and fully terrestrial (reptiles) vertebrates. They still depend on water for reproduction and larval development."},
{"n":30,"q":"What is 'autotomy' as observed in lizards?","o":["A. Growing a new tail from birth","B. Regenerating lost limbs","C. The ability to voluntarily shed the tail as a defence mechanism","D. Changing skin colour"],"a":"C. The ability to voluntarily shed the tail as a defence mechanism","e":"Autotomy is the ability of lizards to voluntarily detach (shed) their tail when grabbed by a predator. The tail may wriggle to distract the predator while the lizard escapes. The tail can later regenerate, though usually made of cartilage."},
{"n":31,"q":"Marine fishes deal with salt concentration by:","o":["A. Producing dilute urine","B. Absorbing fresh water from food only","C. Drinking seawater and actively excreting excess salt through gills","D. Reducing all metabolic activity"],"a":"C. Drinking seawater and actively excreting excess salt through gills","e":"Marine fishes live in a hypertonic environment (saltier than their bodies), so they constantly lose water by osmosis. They drink large amounts of seawater and actively excrete excess salt through specialized cells in their gills and produce small amounts of concentrated urine."},
{"n":32,"q":"The 'keel' (enlarged sternum) in birds is important because it:","o":["A. Protects the heart","B. Stores food","C. Provides attachment for powerful pectoral (flight) muscles","D. Aids in egg laying"],"a":"C. Provides attachment for powerful pectoral (flight) muscles","e":"The keel is an extended projection of the sternum (breastbone) in birds. It provides a large surface area for the attachment of the powerful pectoral muscles responsible for the flapping wing movements used in flight. Flightless birds (like ostriches) have a reduced keel."},
// BATCH2
// BATCH3
// BATCH4
// BATCH5
// BATCH6
];
fs.writeFileSync('q200_raw.json', JSON.stringify(q));
console.log('Written', q.length, 'questions to q200_raw.json');
