[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate"]

[phases.start]
cmds = ["node src/index.js"]

[variables]
NODE_ENV = "production"
