// Script to add CHE-111 questions to data.js
const fs = require('fs');
const path = require('path');

const questions = [
  // SECTION A - Answer A (Questions 1-10)
  {
    q: "What is the IUPAC name for CH₄?",
    options: ["Methane", "Ethane", "Propane", "Butane"],
    answer: 0,
    explanation: "CH₄ has one carbon atom. In IUPAC nomenclature, one carbon = meth- + alkane suffix = Methane.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Which property of carbon allows it to form long chains and rings with itself?",
    options: ["Catenation", "Tetravalency", "Isomerism", "Aromaticity"],
    answer: 0,
    explanation: "Catenation is the unique ability of carbon to bond with other carbon atoms to form chains and rings of varying lengths.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "What is the functional group present in aldehydes?",
    options: ["–CHO", "–OH", "–COOH", "–NH₂"],
    answer: 0,
    explanation: "Aldehydes are characterised by the –CHO (formyl) group at the terminal end of the carbon chain.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The general formula of alkanes is:",
    options: ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙH₂ₙ₊₁OH"],
    answer: 0,
    explanation: "Alkanes are saturated hydrocarbons. The general formula is CₙH₂ₙ₊₂ (e.g. methane CH₄ with n=1 gives C₁H₄).",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "What does IUPAC stand for?",
    options: ["International Union of Pure and Applied Chemistry", "International Union of Petroleum and Applied Chemistry", "Integrated Union of Pure Applied Compounds", "International University of Pure and Applied Chemistry"],
    answer: 0,
    explanation: "IUPAC = International Union of Pure and Applied Chemistry, the body that sets systematic naming rules for chemical compounds.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC name for HCHO is:",
    options: ["Methanal", "Ethanal", "Propanal", "Methanol"],
    answer: 0,
    explanation: "HCHO has one carbon and an aldehyde group (–CHO). One carbon = meth- + al = Methanal. Its common name is formaldehyde.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Acyclic organic compounds are also called:",
    options: ["Open-chain/Aliphatic", "Aromatic", "Heterocyclic", "Homocyclic"],
    answer: 0,
    explanation: "Acyclic (open-chain) compounds are also known as aliphatic compounds; their carbon atoms form straight or branched chains rather than rings.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "In IUPAC naming, the prefix for two identical substituents is:",
    options: ["Di-", "Tri-", "Tetra-", "Mono-"],
    answer: 0,
    explanation: "When two identical substituents are present, the prefix di- is used (e.g. 2,3-dimethylbutane has two methyl groups).",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "What is the common name for CH₃OH?",
    options: ["Methyl alcohol / Wood spirit", "Ethyl alcohol", "Acetic acid", "Acetone"],
    answer: 0,
    explanation: "CH₃OH (methanol) is commonly called methyl alcohol or wood spirit because it was originally obtained by destructive distillation of wood.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Which of these is the highest priority functional group in IUPAC nomenclature?",
    options: ["Carboxylic acid", "Aldehyde", "Ketone", "Alcohol"],
    answer: 0,
    explanation: "The IUPAC priority order is: Carboxylic acid > Ester > Aldehyde > Ketone > Alcohol > Amine > Alkene/Alkyne > Alkane.",
    difficulty: "medium",
    year: 2026,
  },
  // SECTION B - Answer B (Questions 11-20)
  {
    q: "The IUPAC name for C₂H₅OH is:",
    options: ["Methanol", "Ethanol", "Propanol", "Butanol"],
    answer: 1,
    explanation: "C₂H₅OH has 2 carbons and an –OH group. Two carbons = eth- + ol = Ethanol. Commonly called grain alcohol.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Which functional group is responsible for the acidic properties of organic acids?",
    options: ["–OH", "–COOH", "–CHO", "–NH₂"],
    answer: 1,
    explanation: "The carboxyl group (–COOH) gives carboxylic acids their characteristic acidic properties by donating a proton (H⁺).",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC name for CH₃COCH₃ is:",
    options: ["Propanal", "Propanone", "Butanone", "Ethanone"],
    answer: 1,
    explanation: "CH₃COCH₃ has 3 carbons with a C=O in the middle (ketone). Propan- (3C) + one (ketone suffix) = Propanone. Common name: acetone.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "What is the IUPAC suffix for ketones?",
    options: ["-al", "-one", "-ol", "-oic acid"],
    answer: 1,
    explanation: "Ketones carry the suffix -one in IUPAC nomenclature (e.g. propanone, butanone). The -al suffix belongs to aldehydes.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "In the homologous series, each successive member differs by:",
    options: ["–CH₃ group", "–CH₂– group", "–CO– group", "–OH group"],
    answer: 1,
    explanation: "A homologous series has members that differ by one –CH₂– unit (methylene group). This causes a gradual change in physical properties.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The general formula of alcohols is:",
    options: ["CₙH₂ₙO", "CₙH₂ₙ₊₁OH", "CₙH₂ₙO₂", "CₙH₂ₙ₊₁COOH"],
    answer: 1,
    explanation: "Alcohols follow the general formula CₙH₂ₙ₊₁OH, which can also be written CₙH₂ₙ₊₂O (combining the alkyl group with –OH).",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Heterocyclic compounds contain rings made of:",
    options: ["Carbon atoms only", "Carbon and other atoms like O, N, S", "Only nitrogen atoms", "Only oxygen atoms"],
    answer: 1,
    explanation: "Heterocyclic compounds have rings that include carbon PLUS at least one heteroatom (O, N, S, etc.), e.g. pyridine, furan, thiophene.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC name for CH₃CH₂CH₂OH is:",
    options: ["Ethanol", "Propan-1-ol", "Butan-1-ol", "Methanol"],
    answer: 1,
    explanation: "CH₃CH₂CH₂OH is a 3-carbon chain (propan-) with –OH on carbon 1 (terminal), giving Propan-1-ol.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "What is the common name for CH₃COOH?",
    options: ["Formaldehyde", "Acetic acid", "Acetone", "Benzene"],
    answer: 1,
    explanation: "CH₃COOH (ethanoic acid) is commonly called acetic acid. It is the main component of vinegar.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC name for CH₃CH₂CHO is:",
    options: ["Ethanal", "Propanal", "Butanal", "Methanal"],
    answer: 1,
    explanation: "CH₃CH₂CHO has 3 carbons (propan-) with an aldehyde group (–CHO) giving the suffix -al → Propanal.",
    difficulty: "easy",
    year: 2026,
  },
  // SECTION C - Answer C (Questions 21-35)
  {
    q: "Which of the following is an example of a haloalkane?",
    options: ["CH₃OH", "CH₃COOH", "CH₃CH₂Cl", "CH₃CHO"],
    answer: 2,
    explanation: "Haloalkanes contain a C–X bond where X is a halogen. CH₃CH₂Cl (chloroethane) fits this class; Cl is the halogen substituent.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The functional group of esters is:",
    options: ["–OH", "–CHO", "–COOR", "–CONH₂"],
    answer: 2,
    explanation: "Esters have the –COOR group (where R is an alkyl group). They are derived from carboxylic acids by reacting with alcohols.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "What is the IUPAC name for CH₃CH₂CH₃?",
    options: ["Methane", "Ethane", "Propane", "Butane"],
    answer: 2,
    explanation: "CH₃CH₂CH₃ has 3 carbons (prop-) and only single bonds (alkane, suffix -ane) → Propane.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Organic chemistry is defined as the study of:",
    options: ["Metal compounds", "Ionic compounds", "Carbon-containing compounds", "Noble gas compounds"],
    answer: 2,
    explanation: "Organic chemistry is the branch dealing with carbon-containing compounds. Carbon's tetravalency enables enormous structural diversity.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC suffix for carboxylic acids is:",
    options: ["-ene", "-ol", "-oic acid", "-one"],
    answer: 2,
    explanation: "Carboxylic acids end in -oic acid (e.g. ethanoic acid, propanoic acid). They contain the –COOH functional group.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Which compound has the formula CₙH₂ₙ?",
    options: ["Alkane", "Alkyne", "Alkene", "Alcohol"],
    answer: 2,
    explanation: "Alkenes follow the general formula CₙH₂ₙ. They contain at least one C=C double bond, giving 2 fewer hydrogens than alkanes.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "In 2-methylbutane, the main chain has how many carbons?",
    options: ["Two", "Three", "Four", "Five"],
    answer: 2,
    explanation: "2-Methylbutane: 'but-' = 4 carbons in the main (longest continuous) chain, with a methyl branch on carbon 2.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Ethers have the general functional group:",
    options: ["R–OH", "R–CHO", "R–O–R'", "R–NH₂"],
    answer: 2,
    explanation: "Ethers contain an oxygen atom flanked by two alkyl groups: R–O–R'. The simplest example is dimethyl ether (CH₃–O–CH₃).",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC name for CH₃–C≡CH is:",
    options: ["Propene", "Propane", "Propyne", "Butyne"],
    answer: 2,
    explanation: "CH₃–C≡CH has 3 carbons (prop-) and a triple bond (suffix -yne) → Propyne. The triple bond is on C1-C2.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Amides are identified by the functional group:",
    options: ["–NH₂", "–COOH", "–CONH₂", "–COOR"],
    answer: 2,
    explanation: "Amides contain the –CONH₂ group (or –CONHR, –CONR₂). They result from the reaction of carboxylic acids with amines.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC name for CH₂=CH₂ (ethylene) is:",
    options: ["Ethane", "Ethane", "Ethene", "Ethyne"],
    answer: 2,
    explanation: "CH₂=CH₂ has 2 carbons (eth-) and a double bond (suffix -ene) → Ethene. Common name: ethylene.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Which of these is NOT a reason for the large number of organic compounds?",
    options: ["Tetravalency", "Isomerism", "Metallic bonding", "Catenation"],
    answer: 2,
    explanation: "The large number of organic compounds results from catenation, tetravalency, isomerism, and multiple bonding — NOT metallic bonding, which is a property of metals.",
    difficulty: "medium",
    year: 2026,
  },
  {
    q: "What is the IUPAC name for methyl butanoate (CH₃CH₂CH₂COOCH₃)?",
    options: ["Ethyl propanoate", "Butyl methanoate", "Methyl butanoate", "Propyl ethanoate"],
    answer: 2,
    explanation: "CH₃CH₂CH₂COOCH₃: the acid part is butanoic acid (4C chain), the alcohol part is methanol → Methyl butanoate.",
    difficulty: "medium",
    year: 2026,
  },
  {
    q: "In 2-chlorobutane (CH₃CH₂CH(Cl)CH₃), on which carbon is the Cl?",
    options: ["Carbon 1", "Carbon 4", "Carbon 2", "Carbon 3"],
    answer: 2,
    explanation: "In 2-chlorobutane, the chlorine substituent is on carbon 2 of the butane chain. Numbering starts from the end giving Cl the lowest locant.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Phenols are characterised by:",
    options: ["–COOH attached to aromatic ring", "–CHO attached to ring", "Ar–OH (–OH on aromatic ring)", "–NH₂ on aliphatic chain"],
    answer: 2,
    explanation: "Phenols have a hydroxyl group (–OH) directly attached to an aromatic (benzene) ring. This makes them more acidic than ordinary alcohols.",
    difficulty: "easy",
    year: 2026,
  },
  // SECTION D - Answer D (Questions 36-50)
  {
    q: "The carbon atom in organic compounds forms how many covalent bonds?",
    options: ["One", "Two", "Three", "Four"],
    answer: 3,
    explanation: "Carbon is tetravalent — it forms exactly 4 covalent bonds (e.g. in CH₄ each C forms 4 C–H bonds). This is the basis of organic diversity.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "In IUPAC nomenclature, numbering starts from the end that gives:",
    options: ["The longest chain", "The highest number", "The highest number to functional group", "The lowest number to the functional group/substituent"],
    answer: 3,
    explanation: "Rule: number the chain from the end nearest to the principal functional group or substituent to give it the lowest possible locant.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC name for ethyl alcohol is:",
    options: ["Methanol", "Propanol", "Butanol", "Ethanol"],
    answer: 3,
    explanation: "Ethyl alcohol = C₂H₅OH. With 2 carbons (eth-) and –OH (-ol) → Ethanol. It is the alcohol found in beverages.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "What is the IUPAC name for CH₂=CH₂?",
    options: ["Ethane", "Ethyne", "Propene", "Ethene"],
    answer: 3,
    explanation: "CH₂=CH₂ has 2 carbons and a C=C double bond. Eth- (2C) + -ene (double bond) = Ethene.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Amines contain which functional group?",
    options: ["–COOH", "–CHO", "–C=O (ketone)", "–NH₂"],
    answer: 3,
    explanation: "Amines are derivatives of ammonia (NH₃) where one or more H is replaced by an alkyl group. The functional group is –NH₂ (primary amine).",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Which of the following has the highest boiling point in a homologous series?",
    options: ["Member with 1 carbon", "Member with 2 carbons", "Member with 3 carbons", "Member with higher molecular mass"],
    answer: 3,
    explanation: "In a homologous series, boiling point increases with molecular mass. Larger molecules have stronger van der Waals/London dispersion forces.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC name for C₆H₆ is:",
    options: ["Hexene", "Hexane", "Hexyne", "Benzene"],
    answer: 3,
    explanation: "C₆H₆ is benzene — an aromatic compound with a delocalized ring of 6 π electrons. Its IUPAC name is also 'benzene'.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "What type of compound is formed when carboxylic acids react with alcohols?",
    options: ["Ether", "Ketone", "Aldehyde", "Ester"],
    answer: 3,
    explanation: "Carboxylic acid + Alcohol → Ester + Water (esterification reaction). E.g. CH₃COOH + C₂H₅OH → CH₃COOC₂H₅ + H₂O.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The IUPAC suffix for aldehydes is:",
    options: ["-oic acid", "-one", "-ol", "-al"],
    answer: 3,
    explanation: "Aldehydes use the suffix -al (e.g. methanal, ethanal, propanal). This reflects the –CHO (aldehyde) functional group at the chain terminus.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "In IUPAC nomenclature, identical substituents appearing three times use which prefix?",
    options: ["Di-", "Mono-", "Tetra-", "Tri-"],
    answer: 3,
    explanation: "When three identical substituents are present, the prefix tri- is used (e.g. 2,3,4-trimethylpentane has 3 methyl groups).",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "Homocyclic (carbocyclic) compounds contain rings consisting of:",
    options: ["Only nitrogen", "Only oxygen", "C and heteroatoms", "Only carbon atoms"],
    answer: 3,
    explanation: "Homocyclic or carbocyclic compounds have rings made entirely of carbon atoms. Benzene (C₆H₆) is the classic example.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "The common name of propanone (CH₃COCH₃) is:",
    options: ["Formaldehyde", "Acetic acid", "Methanol", "Acetone"],
    answer: 3,
    explanation: "Propanone (CH₃COCH₃) is commonly known as acetone. It is widely used as a solvent in nail polish remover.",
    difficulty: "easy",
    year: 2026,
  },
  {
    q: "What is the IUPAC name of the compound with formula CH₃–CH(CH₃)–CH₂–CH₃?",
    options: ["2-Ethylpropane", "3-Methylbutane", "2-Ethylbutane", "2-Methylbutane"],
    answer: 3,
    explanation: "The longest chain is 4C (but-) with a methyl group on C2 → 2-Methylbutane. Always identify the longest chain first.",
    difficulty: "medium",
    year: 2026,
  },
  {
    q: "The priority of functional groups for IUPAC naming — which comes AFTER aldehyde in the priority order?",
    options: ["Ester", "Alcohol", "Amine", "Ketone"],
    answer: 3,
    explanation: "Priority order: Carboxylic acid > Ester > Aldehyde > Ketone > Alcohol > Amine > Alkene. So Ketone comes right after Aldehyde.",
    difficulty: "medium",
    year: 2026,
  },
  {
    q: "Which of the following statements about a homologous series is CORRECT?",
    options: ["Members have different functional groups", "Members have no general formula", "Members have identical physical properties", "Successive members differ by a –CH₂– unit"],
    answer: 3,
    explanation: "A homologous series shares the same functional group, has a general formula, shows gradual change in physical properties, and each successive member differs by –CH₂–.",
    difficulty: "easy",
    year: 2026,
  },
];

const che111Subject = {
  id: "che111",
  label: "CHE 111",
  icon: "🧪",
  accent: "#f97316",
  description: "Introductory Organic Chemistry - IUPAC nomenclature, functional groups, and organic compound classification.",
  questions: questions,
};

// Read existing data.js
const dataPath = path.join(__dirname, '..', 'src', 'data.js');
let content = fs.readFileSync(dataPath, 'utf8');

// Find the position to insert (before the closing bracket of SUBJECTS array)
// Look for the pattern "  },\n];" at the end of the subjects array
const match = content.match(/(\s*\},\s*\]\;\n\nexport const XP_PER_CORRECT)/);
if (!match) {
  console.error('Could not find insertion point');
  process.exit(1);
}

// Create the new subject entry
const newSubjectStr = `  },
  ${JSON.stringify(che111Subject, null, 2).split('\n').map((line, i) => i === 0 ? line : '  ' + line).join('\n')},
];`;

// Replace the closing bracket with new subject + closing bracket
content = content.replace(match[1], newSubjectStr + ';\n\nexport const XP_PER_CORRECT');

// Write back
fs.writeFileSync(dataPath, content);
console.log(`Added ${questions.length} CHE-111 questions to data.js`);
