const fs = require('fs');
const path = require('path');

// New GST 115 questions - 139 total (80% year 2026, 20% year 2025)
// 111 questions for 2026, 28 questions for 2025
const newQuestions = [
  // SECTION A: NIGERIA – PHYSICAL FEATURES (20 questions)
  { q: "What is the approximate land area of Nigeria?", options: ["924,000 sq km", "823,000 sq km", "1,000,000 sq km", "760,000 sq km"], answer: 0, explanation: "Nigeria has a size of 924,000 square km.", difficulty: "medium", year: 2026 },
  { q: "As of 2020, Nigeria's population was approximately:", options: ["150 million", "180 million", "202 million", "220 million"], answer: 2, explanation: "Nigeria's population was about 202 million as at 2020.", difficulty: "medium", year: 2025 },
  { q: "Which wind brings the cold harmattan season to Nigeria?", options: ["South-west trade wind", "North-east trade wind", "South-east monsoon", "Equatorial westerlies"], answer: 1, explanation: "The harmattan (December–February) is brought by the North-east trade wind.", difficulty: "medium", year: 2026 },
  { q: "The wet/rainy season in Nigeria occurs between:", options: ["October–February", "March–September", "June–December", "January–June"], answer: 1, explanation: "The wet and raining season occurs between March and September.", difficulty: "easy", year: 2025 },
  { q: "Why is northern Nigeria generally hotter than the south?", options: ["It is closer to the equator", "It receives more rainfall", "It is nearer the Sahara desert", "It has denser vegetation"], answer: 2, explanation: "The northern part is hotter because it is nearer the Sahara desert.", difficulty: "medium", year: 2026 },
  { q: "Which vegetation zone in Nigeria is best suited for cattle rearing?", options: ["Mangrove forest", "Rain forest", "Sudan Savannah", "Niger Delta riverine"], answer: 2, explanation: "The Sudan Savannah (north) is suitable for pastoralism – cattle, goats, camels, etc.", difficulty: "medium", year: 2026 },
  { q: "The tsetse fly problem in southern Nigeria primarily limits:", options: ["Crop farming", "Fishing", "Cattle rearing", "Grain production"], answer: 2, explanation: "The forest is not suitable for cattle rearing because of tsetse fly that kills cattle.", difficulty: "medium", year: 2025 },
  { q: "At which town do the Rivers Niger and Benue meet?", options: ["Onitsha", "Lokoja", "Jebba", "Makurdi"], answer: 1, explanation: "River Niger and River Benue meet at the confluence of Lokoja town in Kogi State.", difficulty: "medium", year: 2026 },
  { q: "Nigeria's only lake is:", options: ["Lake Victoria", "Lake Tanganyika", "Lake Chad", "Lake Volta"], answer: 2, explanation: "Nigeria has one lake – Lake Chad in the north-eastern part of the country.", difficulty: "easy", year: 2026 },
  { q: "Nigeria's life expectancy (WHO) is approximately:", options: ["35 years", "48 years", "60 years", "72 years"], answer: 1, explanation: "Life expectancy in Nigeria is put at 48 years based on WHO assessment.", difficulty: "medium", year: 2025 },
  { q: "Nigeria's infant mortality rate is:", options: ["45 deaths per 1,000 births", "91 deaths per 1,000 births", "120 deaths per 1,000 births", "30 deaths per 1,000 births"], answer: 1, explanation: "Infant mortality in Nigeria is put at 91 deaths per 1,000 births.", difficulty: "medium", year: 2026 },
  { q: "Nigeria's literacy rate stands at:", options: ["50%", "60%", "70%", "80%"], answer: 2, explanation: "Literacy rate in Nigeria is 70%.", difficulty: "medium", year: 2026 },
  { q: "What is the minimum voting age in Nigeria?", options: ["16", "18", "21", "25"], answer: 1, explanation: "Voting suffrage – 18 years.", difficulty: "easy", year: 2025 },
  { q: "Nigeria's current constitution came into force on:", options: ["1 October 1960", "1 October 1963", "29 May 1999", "1 January 1914"], answer: 2, explanation: "Constitution in use – May 29, 1999.", difficulty: "medium", year: 2026 },
  { q: "How many members make up Nigeria's House of Representatives?", options: ["109", "360", "469", "250"], answer: 1, explanation: "House of Representatives – 360 members.", difficulty: "easy", year: 2026 },
  { q: "Nigeria's Senate is composed of:", options: ["360 members", "250 members", "109 members", "120 members"], answer: 2, explanation: "Senate – 109 members.", difficulty: "easy", year: 2025 },
  { q: "Mineral tin is found in which Nigerian state?", options: ["Enugu", "Plateau", "Kogi", "Zamfara"], answer: 1, explanation: "Tin is found in Plateau State.", difficulty: "medium", year: 2026 },
  { q: "Coal deposits in Nigeria are found in:", options: ["Abeokuta", "Kogi", "Enugu", "Bayelsa"], answer: 2, explanation: "Coal is found in Enugu State.", difficulty: "easy", year: 2026 },
  { q: "Gold and copper deposits are found in:", options: ["Plateau and Enugu", "Katsina, Zamfara, and Oyo States", "Bayelsa and Rivers", "Sokoto and Katsina"], answer: 1, explanation: "Gold and copper are found in Katsina, Zamfara, and Oyo States.", difficulty: "medium", year: 2025 },
  { q: "Iron ore in Nigeria is found at:", options: ["Ajaokuta, Kogi State", "Enugu", "Bayelsa", "Abeokuta"], answer: 0, explanation: "Iron ore is found in Ajaokuta, Kogi State.", difficulty: "easy", year: 2026 },

  // SECTION B: CONCEPT OF CULTURE (18 questions)
  { q: "Who gave the first and most popular anthropological definition of culture?", options: ["Havilland", "Bronislaw Malinowski", "Edward Burnett Tylor", "Franz Boas"], answer: 2, explanation: "Sir Edward Burnett Tylor gave the first and most popular definition of culture.", difficulty: "medium", year: 2026 },
  { q: "According to Tylor, culture includes all of the following EXCEPT:", options: ["Knowledge and beliefs", "Arts and laws", "Physical appearance", "Customs and habits"], answer: 2, explanation: "Tylor's definition covers knowledge, beliefs, arts, laws, values, technology, customs and habits – NOT physical appearance.", difficulty: "medium", year: 2025 },
  { q: "The term 'Homo sapiens' means:", options: ["Social animal", "Able beings / wise man", "Cultural creature", "Biological organism"], answer: 1, explanation: "Homo sapiens means 'able beings' or 'the wise man.'", difficulty: "medium", year: 2026 },
  { q: "Culture is best described as:", options: ["A biological inheritance", "A set of beliefs and practices learned and transferred across generations", "An individual's personal habits", "An innate instinct"], answer: 1, explanation: "Culture is a set of beliefs, knowledge and customs peculiar to a group, learnt and transferred across generations.", difficulty: "medium", year: 2026 },
  { q: "The process by which culture is transmitted from one generation to another is called:", options: ["Socialization only", "Enculturation", "Adaptation", "Modernization"], answer: 1, explanation: "Culture is transmitted through enculturation, socialization, and education.", difficulty: "medium", year: 2025 },
  { q: "Which component of culture justifies a society's social, economic, and political interests through beliefs and values?", options: ["Technological component", "Organisational component", "Ideological component", "Material component"], answer: 2, explanation: "The Ideological component includes beliefs, ideas, values, mores and norms.", difficulty: "medium", year: 2026 },
  { q: "Which component of culture deals with how social order is formed and regulated?", options: ["Ideological", "Technological", "Material", "Organisational"], answer: 3, explanation: "The Organisational component covers rules of behaviour, sanctions, statuses, roles, and authority.", difficulty: "medium", year: 2026 },
  { q: "Art, craft, sculpture, clothing, and technology are examples of which aspect of culture?", options: ["Non-material aspects", "Ideological aspects", "Material aspects", "Organisational aspects"], answer: 2, explanation: "Material culture refers to tangible objects we can see, hold, and touch.", difficulty: "medium", year: 2025 },
  { q: "Values, language, myths, beliefs, and religion are examples of:", options: ["Material culture", "Technological culture", "Non-material aspects of culture", "Ideological component only"], answer: 2, explanation: "Non-material aspects are intangible phenomena that cannot be seen or touched.", difficulty: "medium", year: 2026 },
  { q: "Which characteristic of culture refers to its ability to change with time, civilisation, and globalisation?", options: ["Culture is symbolic", "Culture is adaptive", "Culture is dynamic", "Culture is transmitted"], answer: 2, explanation: "Culture is dynamic – it is not static; it changes with time, civilisation, education, and exposure.", difficulty: "medium", year: 2026 },
  { q: "The characteristic that culture 'does not belong to one individual' reflects that culture is:", options: ["Symbolic", "Adaptive", "Shared", "Transmitted"], answer: 2, explanation: "Culture is shared – behaviour common to every member of society, not belonging to one individual.", difficulty: "medium", year: 2025 },
  { q: "Language is primarily described in culture as:", options: ["A material artefact", "The chief vehicle of culture", "An organisational tool", "A non-shared behaviour"], answer: 1, explanation: "Language is the chief vehicle of culture through which older generations pass down culture.", difficulty: "medium", year: 2026 },
  { q: "Which function of culture separates one ethnic group from another?", options: ["Identity", "Personhood", "Expression of ethnicity", "Root"], answer: 2, explanation: "Culture is an expression of ethnicity and marks one group different from another.", difficulty: "medium", year: 2026 },
  { q: "The concept of 'Global culture' is also referred to as:", options: ["European culture", "Sub-culture", "Popular/American culture", "Traditional culture"], answer: 2, explanation: "Global culture has been referred to as popular culture, which is the American culture.", difficulty: "medium", year: 2025 },
  { q: "Dependency theory states that underdeveloped countries:", options: ["Resist modernisation", "Depend on developed countries", "Create their own culture", "Reject globalisation"], answer: 1, explanation: "Dependency theory: underdeveloped countries are very slow to modernise, so they depend on developed countries.", difficulty: "medium", year: 2026 },
  { q: "A group of people who share a distinct set of cultural traits within a larger society is called a:", options: ["Nation", "Ethnic group", "Subculture", "Tribe"], answer: 2, explanation: "Subcultures are groups that share distinct cultural traits within a larger society.", difficulty: "medium", year: 2026 },
  { q: "The earliest physical evidence of culture is:", options: ["Cave paintings in France", "Crude stone tools in East Africa over 2 million years ago", "Egyptian pyramids", "Cuneiform writing"], answer: 1, explanation: "The earliest physical evidence of culture is crude stone tools produced in East Africa over two million years ago.", difficulty: "medium", year: 2025 },
  { q: "An attitude or behaviour belonging to only one individual is best called:", options: ["Culture", "Norm", "Habit", "Tradition"], answer: 2, explanation: "Any attitude belonging to an individual is called a habit; culture is behaviour common to every member.", difficulty: "medium", year: 2026 },

  // SECTION C: ETHNOGRAPHY & ETHNIC GROUPS (19 questions)
  { q: "Nigeria was officially amalgamated in:", options: ["1900", "1914", "1922", "1960"], answer: 1, explanation: "The British amalgamated the different ethnic groupings into Nigeria in January 1914.", difficulty: "medium", year: 2026 },
  { q: "Anthropologists estimate the number of ethnic groups in Nigeria at:", options: ["150", "250", "371", "500"], answer: 2, explanation: "Numerically, anthropologists put the number of ethnic groups in Nigeria at 371.", difficulty: "medium", year: 2025 },
  { q: "The three major ethnic groups in Nigeria comprise what percentage of the population?", options: ["43%", "57%", "70%", "80%"], answer: 1, explanation: "The three major ethnic groups (Hausa/Fulani, Igbo, Yoruba) comprise only 57% of Nigeria's population.", difficulty: "medium", year: 2026 },
  { q: "The Hausa/Fulani language belongs to which linguistic family?", options: ["Kwa sub-family", "Chadic subfamily of the Hamitic stock", "Nigritic stock", "Volta-Niger family"], answer: 1, explanation: "The Hausas speak the Chadic subfamily of the Hamitic stock language.", difficulty: "medium", year: 2026 },
  { q: "According to the Bayajida oral tradition, who founded the Hausa states?", options: ["Biran alone", "Oduduwa", "Bayajida and descendants (Bawo's children + Biran)", "Fulani Jihadists"], answer: 2, explanation: "Bayajida's sons Biran and Bawo (and Bawo's six children) founded the seven Hausa Bokwoi states.", difficulty: "medium", year: 2025 },
  { q: "The Hausa state responsible for the slave trade/slave-mastering role was:", options: ["Kano", "Gobir", "Zaria", "Daura"], answer: 2, explanation: "Zaria held the role of slave master among the Hausa Bokwoi.", difficulty: "medium", year: 2026 },
  { q: "Which Hausa state had the role of war leader?", options: ["Kano", "Zaria", "Gobir", "Biran"], answer: 2, explanation: "Gobir was the war leader among the Hausa Bokwoi.", difficulty: "medium", year: 2026 },
  { q: "The cattle/nomadic Fulani are called:", options: ["Gida", "Bororoje", "Peul", "Felata"], answer: 1, explanation: "The Bororoje are the cattle or nomadic Fulani – pastoral and mostly in the bush.", difficulty: "medium", year: 2025 },
  { q: "The Fulani arrived among the Hausas in which century?", options: ["10th Century", "11th Century", "13th Century", "15th Century"], answer: 2, explanation: "They arrived among the Hausas in the 13th century, intermarried and adopted their customs.", difficulty: "medium", year: 2026 },
  { q: "Which of the following best describes Igbo political structure historically?", options: ["Centralised monarchy", "Acephalous/egalitarian village assembly", "Theocratic emirate", "Federal republic"], answer: 1, explanation: "The Igbo operated an acephalous, decentralised society based on village assembly with no centralised political head.", difficulty: "medium", year: 2026 },
  { q: "The Nri version of Igbo origin states that the ancestor Eri descended from:", options: ["Middle East", "The sky and sailed down the Anambra River", "Israel (lost tribe)", "Benin Kingdom"], answer: 1, explanation: "Eri the ancestor of the Igbo descended from the sky and sailed down the Anambra River.", difficulty: "medium", year: 2025 },
  { q: "Eri and his group finally settled at the confluence of which two rivers?", options: ["Niger and Benue", "Ezu and Omambala", "Cross River and Anambra", "Osun and Ogun"], answer: 1, explanation: "Eri settled at the confluence of Ezu and Omambala Rivers, in present-day Aguleri, Anambra State.", difficulty: "medium", year: 2026 },
  { q: "The Igbo language has approximately how many speakers?", options: ["10 million", "24 million", "40 million", "5 million"], answer: 1, explanation: "The Igbo language has around 24 million speakers and 20 dialects.", difficulty: "medium", year: 2026 },
  { q: "The ancient Igbo pyramids are also known as:", options: ["Awka pyramids", "Nsude pyramids", "Onitsha pyramids", "Arochukwu pyramids"], answer: 1, explanation: "The Ancient Igbo Pyramids are also known as the Nsude Pyramids.", difficulty: "medium", year: 2025 },
  { q: "The unity of the Yoruba as an ethnic group is centred around:", options: ["The Oyo Empire only", "Common ancestral line of Oduduwa and Ile-Ife", "River Niger boundary", "The Benin Kingdom"], answer: 1, explanation: "Yoruba unity is centred around the common ancestral line of Oduduwa and Ile-Ife as central abode.", difficulty: "medium", year: 2026 },
  { q: "According to the Mecca version of Yoruba origin, who was the father of Oduduwa?", options: ["Oranmiyan", "Okanbi", "Lamurudu", "Obatala"], answer: 2, explanation: "Lamurudu gave birth to Oduduwa who founded Ile-Ife.", difficulty: "medium", year: 2026 },
  { q: "In the Yoruba creation mythology, who got drunk and could not complete the task of creation?", options: ["Oduduwa", "Olodumare", "Obatala", "Oranmiyan"], answer: 2, explanation: "Obatala got drunk on palm wine and Oduduwa had to continue the task of creation.", difficulty: "medium", year: 2025 },
  { q: "Yoruba archaeological evidence suggests they have been in their area since approximately:", options: ["500 BC", "2000–1000 BC", "3500 BC", "1500 AD"], answer: 1, explanation: "Archaeologically, they are believed to have been living in their area between 2000 and 1000 BC.", difficulty: "medium", year: 2026 },
  { q: "The word 'tribe' in ethnographic study is considered:", options: ["A technical anthropological term", "Derogatory and a colonial caption", "A synonym for ethnic group", "An acceptable scientific label"], answer: 1, explanation: "Tribe as a word is derogatory. It was a caption used by colonial masters – it is insulting and abusive.", difficulty: "medium", year: 2026 },

  // SECTION D: NIGERIA AS A POLITICAL UNIT (18 questions)
  { q: "The name 'Nigeria' was coined by:", options: ["Frederick Lugard", "Mungo Park", "Florence Shaw (wife of Lugard)", "Richard Lander"], answer: 2, explanation: "Nigeria as a name was given by Florence Shaw, wife of Frederick Lugard the Governor General.", difficulty: "medium", year: 2026 },
  { q: "River Niger was discovered/named by:", options: ["Frederick Lugard and Florence Shaw", "Mungo Park and the Lander brothers (Richard and John) in 1830", "The Portuguese in 1472", "The Berlin Conference of 1884"], answer: 1, explanation: "River Niger was named and discovered by both Mungo Park and the Lander brothers Richard and John in 1830.", difficulty: "medium", year: 2025 },
  { q: "Which European nation first made contact with present-day Nigeria?", options: ["British", "Dutch", "French", "Portuguese"], answer: 3, explanation: "The Portuguese were the first Europeans to arrive in present Nigeria, coming through Benin Kingdom in 1472.", difficulty: "medium", year: 2026 },
  { q: "The Atlantic Slave Trade began as a direct result of:", options: ["European curiosity", "Trans-Saharan trade decline", "Growth of plantation agriculture in America requiring labour", "Berlin Conference decisions"], answer: 2, explanation: "The Atlantic Slave Trade started as a result of the growth of plantation agriculture in America and the consequent demand for labour.", difficulty: "medium", year: 2026 },
  { q: "Efforts to abolish the slave trade began in:", options: ["1776", "1807", "1884", "1900"], answer: 1, explanation: "Efforts to abolish slave trade started in 1807; by 1860 slavery was abolished.", difficulty: "medium", year: 2025 },
  { q: "The Berlin Conference where Africa was partitioned took place in:", options: ["1860", "1884", "1900", "1914"], answer: 1, explanation: "European powers called the Berlin conference in 1884 where Africa was shared and divided.", difficulty: "medium", year: 2026 },
  { q: "Lagos became a British colony in:", options: ["1861", "1884", "1900", "1914"], answer: 0, explanation: "In 1861 to control Lagos, being a coast land, Britain made Lagos a British colony.", difficulty: "medium", year: 2026 },
  { q: "Which of the following is NOT a reason for the abolition of slave trade?", options: ["Humanitarian agitation", "Industrial growth needing raw materials", "Need for African markets", "Europeans wanting to settle permanently in Africa"], answer: 3, explanation: "The three reasons given are humanitarian agitation, industrial growth needing raw materials, and Africa as market for finished goods.", difficulty: "medium", year: 2025 },
  { q: "The Southern Protectorate was split into West and East on:", options: ["1 January 1914", "1 April 1939", "1 October 1960", "1 October 1963"], answer: 1, explanation: "On 1st April 1939, the Southern Protectorate was split into West and East.", difficulty: "medium", year: 2026 },
  { q: "Indirect Rule was most successful in which part of Nigeria?", options: ["South-East", "South-West", "The North", "The Middle Belt"], answer: 2, explanation: "In the north indirect rule was successful because of the existing oligarchic structure of the Hausa/Fulani aristocracy.", difficulty: "medium", year: 2026 },
  { q: "The Clifford Constitution of 1922 introduced:", options: ["Regionalism", "The first elective principle in Legislation", "A federal system", "Nigerian independence"], answer: 1, explanation: "Clifford Constitution 1922 – the first elective principle in legislation.", difficulty: "medium", year: 2025 },
  { q: "The Richard Constitution of 1946 is notable for:", options: ["Granting independence", "Defining Nigeria by dividing it into 3 main regions", "Introducing universal suffrage", "Establishing the Supreme Court"], answer: 1, explanation: "Richard Constitution 1946 – defined Nigeria by dividing Nigeria into 3 main regions.", difficulty: "medium", year: 2026 },
  { q: "The Lyttleton Constitution of 1954 established:", options: ["A unicameral federal legislature and granted regional autonomy", "Universal suffrage", "Nigerian independence", "A bicameral legislature only"], answer: 0, explanation: "Lyttleton Constitution 1954 established unicameral legislature for federal and regions and granted autonomy of regions.", difficulty: "medium", year: 2026 },
  { q: "The 1963 Constitution replaced the Governor-General with:", options: ["A Prime Minister", "A President (Azikwe)", "A Chancellor", "A Federal Supreme Court"], answer: 1, explanation: "1963 Constitution replaced Gov. General with president – Azikwe; Balewa became Prime Minister.", difficulty: "medium", year: 2025 },
  { q: "The Action Group was founded by Obafemi Awolowo in:", options: ["1944", "1948", "1949", "1960"], answer: 1, explanation: "The Action Group was founded by Obafemi Awolowo in 1948.", difficulty: "medium", year: 2026 },
  { q: "The Northern People's Congress (NPC) was formed to:", options: ["Unite all Nigerian ethnic groups", "Defend northern interest, formed in 1949", "Achieve independence faster", "Support the NCNC"], answer: 1, explanation: "In 1949 the Northern People's Congress was formed by Ammin Kaqno and Tafawa Balewa to defend Northern interest.", difficulty: "medium", year: 2026 },
  { q: "Federalism is best defined as:", options: ["A single centralised government", "A system where two levels of government control the same territory and citizens", "Rule by a monarch", "A theocratic state"], answer: 1, explanation: "Federalism means: a system in which two levels of government control same territory and citizens.", difficulty: "medium", year: 2025 },
  { q: "Nigerian nationalists who were exiled or dethroned for resisting colonisation include all EXCEPT:", options: ["Nana of Itshekiri", "Jaja of Opobo", "Overamwen Nogbaisi of Benin", "Obafemi Awolowo"], answer: 3, explanation: "Nana, Jaja, Overamwen, Attahiru of Sokoto, and Rabeh of Bornu resisted and faced exile. Awolowo was a nationalist leader in the independence era, not a resisting traditional ruler.", difficulty: "medium", year: 2026 },

  // SECTION E: CHRISTIANITY & ISLAM IN NIGERIA (14 questions)
  { q: "Christianity became the official religion of the Roman Empire in:", options: ["AD 70", "AD 313", "AD 476", "AD 570"], answer: 1, explanation: "By 313 AD the Christian faith became the official religion of the Roman Empire.", difficulty: "medium", year: 2026 },
  { q: "The first Christian missionary effort in Nigeria (15th century) failed primarily due to:", options: ["Lack of funding", "Missionaries being few and allergic to tropical climate, plus hostility of Nigerians", "Political instability in Europe", "Lack of a printing press"], answer: 1, explanation: "Missionaries were few, allergic to the tropical climate and mosquito, and faced hostility from Nigerian indigenes.", difficulty: "medium", year: 2025 },
  { q: "Christianity in Yorubaland (Western Sector) began in Abeokuta in:", options: ["1800", "1842", "1850", "1902"], answer: 1, explanation: "In 1842 Anglican, Southern American Baptist and Roman Catholic became active among the Yoruba through Badagry.", difficulty: "medium", year: 2026 },
  { q: "The Eastern Sector of Christian missions began in Calabar in:", options: ["1842", "1846", "1855", "1902"], answer: 1, explanation: "Calabar mission started in 1846 beginning from Hopewell.", difficulty: "medium", year: 2026 },
  { q: "The first Niger expedition (Niger Mission) was in:", options: ["1830", "1841", "1850", "1902"], answer: 1, explanation: "The first Niger expedition was in 1841 – made up of missionaries, teachers, and traders.", difficulty: "medium", year: 2025 },
  { q: "Which mission started work in Jos, Benue, and Adamawa in 1902?", options: ["Anglican Mission", "Sudan United Mission of England", "Roman Catholic Mission", "Scottish Presbyterian Mission"], answer: 1, explanation: "In 1902 the Sudan United Mission of England started work in Jos, Benue, Adamawa led by Rev Kure.", difficulty: "medium", year: 2026 },
  { q: "Christian missionaries are credited with which major contribution to Nigeria?", options: ["Introduction of Islam", "Introduction of western education, printing press, and literacy", "Founding political parties", "Building the railway"], answer: 1, explanation: "Western Education was introduced to Nigeria by the missionaries; schools were built and the printing press was introduced.", difficulty: "medium", year: 2026 },
  { q: "Mohammed was born in:", options: ["550 AD in Medina", "570 AD in Mecca", "622 AD in Yathrib", "632 AD in Mecca"], answer: 1, explanation: "Mohammed was born in 570 AD in Mecca.", difficulty: "medium", year: 2025 },
  { q: "Mohammed's flight from Mecca to Medina in 622 AD is known as:", options: ["Jihad", "Hajj", "Hejira", "Hijab"], answer: 2, explanation: "He fled from Mecca due to persecution in 622 AD – this flight is referred to as Hejira.", difficulty: "medium", year: 2026 },
  { q: "Islam spread into Nigeria primarily through:", options: ["The Niger Mission", "The Trans-Saharan Trade through Hausaland and Bornu", "The Atlantic Slave Trade", "Portuguese missionaries"], answer: 1, explanation: "Islam spread into Nigeria through Hausaland and Bornu through traders during the Trans-Saharan Trade.", difficulty: "medium", year: 2026 },
  { q: "Mohammed Rimfa of Kano marked Islam's elite status by:", options: ["Building the first mosque", "Converting the Fulani", "Marking the first Id-el Fitri and slaughtering a ram", "Conducting the first Jihad"], answer: 2, explanation: "Mohammed Rimfa of Kano was converted to Islam and marked the first Id-el Fitri and slaughter of a ram.", difficulty: "medium", year: 2025 },
  { q: "Islam 'means' which of the following?", options: ["Peace and brotherhood", "Submission to God's will", "Praise to the Prophet", "Unity of believers"], answer: 1, explanation: "Islam means submission to God's will, and this is regarded as the first tenant of Islam.", difficulty: "medium", year: 2026 },
  { q: "The Ahmadiyya movement was founded by:", options: ["A Pakistani named Ghulam Ahmad", "The Ummayid Caliphate", "The Almoravids", "Usman Dan Fodio"], answer: 0, explanation: "The Ahmadiya was founded by a Pakistani named Ghulam Ahmad who claimed to be a reincarnation of Jesus Christ.", difficulty: "medium", year: 2026 },
  { q: "One reason Islam spread easily in Africa is that it:", options: ["Forbade polygamy", "Allowed up to four wives, compatible with African cultural polygamy", "Required all converts to abandon traditional beliefs", "Charged high subscription fees"], answer: 1, explanation: "Islam allowed between two to four wives which was compatible with African Cultural Polygamy.", difficulty: "medium", year: 2025 },

  // SECTION F: CONCEPT OF CULTURE – EXAM BANK (50 questions)
  { q: "According to the study notes, culture is best described as:", options: ["A way of life peculiar to a group of people", "A set of laws made by the government for its citizens", "The biological instincts shared by all human beings", "The economic practices of a community"], answer: 0, explanation: "The notes define culture as 'a way of life peculiar to a group of people.' It is the unique attribute that distinguishes humans from other animals and is not biological but socially acquired.", difficulty: "medium", year: 2026 },
  { q: "The Latin scientific name of humans, meaning 'the wise man', is:", options: ["Homo sapiens", "Homo habilis", "Homo erectus", "Homo culturalis"], answer: 0, explanation: "Homo sapiens means 'the wise man.' Human beings are the only animals with a complex brain that has enormous capacity for learning and acquiring culture.", difficulty: "medium", year: 2025 },
  { q: "Culture is NOT biological; it is acquired through:", options: ["Social processes and interaction", "Genetic inheritance from parents", "Instinctive behaviour from birth", "Physical characteristics of a group"], answer: 0, explanation: "Culture is acquired, learned, shared, and transmitted from one person to another through social processes.", difficulty: "medium", year: 2026 },
  { q: "The most famous and earliest definition of culture in Anthropology was given by:", options: ["Sir Edward Burnett Tylor in 1871", "Havilland in 2004", "Clifford Geertz in 1973", "Karl Marx in 1848"], answer: 0, explanation: "The notes state the most famous and earliest definition was given by Sir Edward Burnett Tylor (1871).", difficulty: "medium", year: 2026 },
  { q: "According to Tylor's 1871 definition, which of the following is INCLUDED in culture?", options: ["Knowledge, beliefs, arts, laws, values, technology, and customs", "Only language and religion", "Only physical tools and technology", "Only written laws and governance systems"], answer: 0, explanation: "Tylor's definition encompasses: knowledge, beliefs, arts, laws, values, technology, customs and every other capacities and habits acquired by man as a member of a society.", difficulty: "medium", year: 2025 },
  { q: "According to Havilland (2004), culture consists of abstract values and beliefs that:", options: ["Lie behind people's behaviour and are reflected in it, making behaviour intelligible to members of society", "Are imposed by government regulations", "Are inherited biologically and cannot be changed", "Exist only in written records and formal institutions"], answer: 0, explanation: "Havilland (2004) says culture consists of abstract values, beliefs, and perceptions that lie behind and are reflected in people's behaviour, shared and making behaviour intelligible to society's members.", difficulty: "medium", year: 2026 },
  { q: "Clothing, sculpture, art and craft, tools, and dance costumes are examples of:", options: ["Material culture", "Non-material culture", "Ideological culture", "Organisational culture"], answer: 0, explanation: "These are categorised under Material Culture — defined as physical objects that can be seen, touched, or felt (Tangible/Visible).", difficulty: "medium", year: 2026 },
  { q: "The component of culture that justifies a society's social, economic, and political interests is the:", options: ["Ideological component", "Technological component", "Organisational component", "Material component"], answer: 0, explanation: "The Ideological Component justifies a society's social, economic, and political interests and includes beliefs, ideas, values, mores, norms, shared meanings, and interpretations.", difficulty: "medium", year: 2025 },
  { q: "The concept of 'de-territorialisation' of culture means:", options: ["Culture can be practised beyond its place of geographical origin", "Culture disappears when people move away from their homeland", "Culture must be attached to a specific territory to survive", "Culture changes completely once people migrate"], answer: 0, explanation: "De-territorialisation means you do not need to be physically in a place (e.g. Yorubaland) to experience or practise its culture.", difficulty: "medium", year: 2026 },
  { q: "The Dependency Theory argues that:", options: ["Underdeveloped countries remain dependent on developed nations because they modernize slowly", "All countries will eventually reach the same level of development", "Developing nations should isolate themselves from Western influence", "Economic development is always equal across all nations"], answer: 0, explanation: "Dependency Theory: Underdeveloped countries (including many in Africa) remain dependent on developed nations because they modernize slowly.", difficulty: "medium", year: 2026 },
  { q: "Which of the following is an example of Non-Material Culture?", options: ["Sculpture and art", "Values, beliefs, language, and religion", "Clothing and shelter", "Tools and technology"], answer: 1, explanation: "Non-Material Culture consists of intangible/abstract elements that cannot be physically touched, including values, beliefs, language, myths, worldview, religion, norms, aesthetics, and proverbs.", difficulty: "medium", year: 2025 },
  { q: "The Technological Component of culture is primarily concerned with:", options: ["Rules of behaviour and sanctions", "Material items and skills used by members of society", "Beliefs, ideas, and shared meanings", "Authority structures and power legitimisation"], answer: 1, explanation: "The Technological Component involves the material items and skills used by members of society, including tools, technology, skills, crafts, arts, and knowledge for producing food, shelter, clothing, and healthcare.", difficulty: "medium", year: 2026 },
  { q: "Which theory suggests that all spheres of life in developing societies should become similar to those in Western Europe and North America?", options: ["Dependency Theory", "Modernisation Theory", "Cultural Relativism Theory", "Evolutionary Theory"], answer: 1, explanation: "Modernisation Theory suggests that all spheres of life (economy, technology, ideas, politics) in developing societies should become similar to those in Western Europe and North America.", difficulty: "medium", year: 2026 },
  { q: "The earliest physical evidence of human culture discovered by archaeologists consists of:", options: ["Cave paintings from Western Europe", "Crude stone tools from East Africa over 2 million years ago", "Written languages from ancient Mesopotamia", "Pottery fragments from ancient China"], answer: 1, explanation: "The earliest evidence of culture consists of crude stone tools from East Africa over 2 million years ago.", difficulty: "medium", year: 2025 },
  { q: "Which key human physical feature MOST enabled the development of spoken culture?", options: ["Upright posture", "Vocal tract for speech", "Free hands for manipulation", "Big, complex brain"], answer: 1, explanation: "The vocal tract for speech is the physical feature that enabled spoken language and oral cultural transmission. The notes list four key enabling features: big brains, upright posture, free hands, and vocal tract for speech.", difficulty: "medium", year: 2026 },
  { q: "In the summary definition for the Nigerian context, culture is transmitted across generations through:", options: ["Biological inheritance and genetics", "Enculturation, socialisation, and education", "Migration and trade between groups", "Government policies and legislation"], answer: 1, explanation: "Culture is learned and transmitted across generations through enculturation, socialisation, and education — the three named transmission mechanisms.", difficulty: "medium", year: 2026 },
  { q: "The key point in the Introduction section states that humans are fundamentally:", options: ["Territorial animals", "Cultural animals", "Biological animals", "Economic animals"], answer: 1, explanation: "The Key Point reads: 'Humans are fundamentally cultural animals. The essence of our biological existence finds expression and meaning through culture.'", difficulty: "medium", year: 2025 },
  { q: "Which of the following BEST explains why humans depend heavily on social interaction for survival?", options: ["Because humans have weak physical bodies compared to other animals", "Because of their cranial capacity and complex brain", "Because they lack the instincts that other animals possess", "Because culture requires a large population to develop"], answer: 1, explanation: "Unlike other animals, humans depend heavily on social interaction for survival because of their cranial capacity — the large, complex human brain necessitates social learning.", difficulty: "medium", year: 2026 },
  { q: "Global Culture or Popular Culture refers primarily to the spread of:", options: ["African cultural practices across the world", "American/Western culture through globalisation", "Ancient civilisations' influence on modern society", "Nigerian traditions to the diaspora"], answer: 1, explanation: "Global/Popular Culture often refers to the spread of (especially) American/Western culture through globalisation.", difficulty: "medium", year: 2026 },
  { q: "The Organisational Component of culture concerns:", options: ["The tools and technology members of a society use", "How social order is maintained", "The values, beliefs, and worldviews of a people", "The material objects produced by a culture"], answer: 1, explanation: "The Organisational Component concerns how social order is maintained and includes rules of behaviour, sanctions, statuses and roles, authority structures, and security mechanisms.", difficulty: "medium", year: 2025 },
  { q: "Culture is described in the notes as a social phenomenon that ensures:", options: ["Political stability and governance", "Economic growth and development", "Human survival and continuity across generations", "Technological advancement in society"], answer: 2, explanation: "Culture is a social phenomenon that ensures human survival and continuity across generations.", difficulty: "medium", year: 2026 },
  { q: "Which of the following is NOT listed as a characteristic of culture?", options: ["Learned", "Shared", "Transmitted across generations", "Genetically inherited"], answer: 3, explanation: "Culture is not biological. Its characteristics are: acquired, learned, shared, and transmitted through social processes. 'Genetically inherited' is the opposite of how culture works.", difficulty: "medium", year: 2026 },
  { q: "According to the study notes, culture provides a framework for:", options: ["Writing laws and constitutions", "Economic production and trade", "Interpreting experiences and generating behaviour", "Military defence and security"], answer: 2, explanation: "Culture provides the framework for interpreting experiences and generating behaviour.", difficulty: "medium", year: 2025 },
  { q: "Which definition describes culture as 'a system of inherited conceptions expressed in symbolic forms by which people perpetuate, communicate, and develop their knowledge'?", options: ["Tylor's 1871 definition", "Havilland's 2004 definition", "The symbolic/semiotic definition from the notes", "The Nigerian contextual summary definition"], answer: 2, explanation: "This is the semiotic/symbolic view of culture — a system of inherited conceptions expressed in symbolic forms by which people perpetuate, communicate, and develop their knowledge and attitudes about life.", difficulty: "medium", year: 2026 },
  { q: "The notes describe culture as 'a historically transmitted system of meaning embodied in:'", options: ["Written laws and decrees", "Economic institutions", "Symbols", "Technology and tools"], answer: 2, explanation: "Culture is a historically transmitted system of meaning embodied in symbols — emphasising the symbolic nature of culture as a carrier of meaning across generations.", difficulty: "medium", year: 2026 },
  { q: "Material culture includes which of the following examples?", options: ["Myths, proverbs, and worldview", "Values, norms, and religion", "Art and craft, shelter, culinary practices, and technology", "Beliefs, aesthetics, and medical knowledge"], answer: 2, explanation: "Material Culture examples include: art and craft, sculpture, clothing, shelter/housing, technology, culinary practices, dance costumes, and tools. Options A, B, and D describe non-material culture.", difficulty: "medium", year: 2025 },
  { q: "The Ideological Component of culture includes all of the following EXCEPT:", options: ["Values", "Beliefs", "Tools and skills for production", "Mores and norms"], answer: 2, explanation: "Tools and skills for production belong to the Technological Component, not the Ideological Component.", difficulty: "medium", year: 2026 },
  { q: "The notes state that culture 'regulates social stability while also:'", options: ["Maintaining fixed traditions that never change", "Preventing outside influences from entering society", "Adapting to new realities", "Restricting individual freedom for the group's benefit"], answer: 2, explanation: "Culture regulates social stability while also adapting to new realities — it preserves stability AND evolves in response to change.", difficulty: "medium", year: 2026 },
  { q: "Which of the following physical features enabled humans to use and create cultural objects and tools?", options: ["Big, complex brains", "Upright posture", "Free hands for manipulation", "Vocal tract for speech"], answer: 2, explanation: "Free hands for manipulation specifically enabled humans to create and use tools — the physical basis for material culture.", difficulty: "medium", year: 2025 },
  { q: "The totality of a group's way of life, learned through socialisation, is one of the definitions of:", options: ["Society", "Tradition", "Culture", "Ethnicity"], answer: 2, explanation: "One of the definitions reads: 'The totality of a particular group of people's way of life, learned through socialisation within the group.'", difficulty: "medium", year: 2026 },
  { q: "According to the notes, culture gives identity and distinguishes:", options: ["Individuals from one another based on personality", "Nations from one another based on geography", "One ethnic group from another (e.g., Yoruba, Igbo, Hausa)", "Social classes from one another based on wealth"], answer: 2, explanation: "Culture gives identity and distinguishes one group (e.g., ethnic groups in Nigeria) from another.", difficulty: "medium", year: 2026 },
  { q: "The definition of culture as 'a patterned behaviour that is socially acquired and shared by a group' emphasises which characteristic?", options: ["Culture is territorial", "Culture is biological", "Culture is collective and learned", "Culture is static and unchanging"], answer: 2, explanation: "This emphasises that culture is collective (shared) and learned (socially acquired), not individual or biological.", difficulty: "medium", year: 2025 },
  { q: "The study notes indicate that culture developed alongside the evolution of:", options: ["Homo habilis", "Homo erectus", "Homo sapiens", "Australopithecus"], answer: 2, explanation: "Culture developed alongside the evolution of Homo sapiens.", difficulty: "medium", year: 2026 },
  { q: "Which term refers to the process of learning culture by being raised within a cultural group?", options: ["Education", "Socialisation", "Enculturation", "Modernisation"], answer: 2, explanation: "Enculturation is the process by which individuals learn and internalise the values, norms, and practices of their culture from birth.", difficulty: "medium", year: 2026 },
  { q: "The Organisational Component of culture includes which of the following?", options: ["Values, beliefs, and shared meanings", "Tools, crafts, and technology", "Statuses, roles, authority structures, and mechanisms for security", "Myths, proverbs, and cosmovision"], answer: 2, explanation: "The Organisational Component includes rules of behaviour, sanctions, statuses and roles, authority structures, legitimisation of power, and mechanisms for security and coordination.", difficulty: "medium", year: 2025 },
  { q: "Culture is described as dynamic, meaning it:", options: ["Remains fixed across all generations", "Is passed down without any changes", "Is only practised by traditional communities", "Changes over time while maintaining social stability"], answer: 3, explanation: "Culture is dynamic (not static). It changes over time while also regulating social stability.", difficulty: "medium", year: 2026 },
  { q: "Which of the following BEST explains why culture is described as 'not biological'?", options: ["Because culture only exists in developed societies", "Because humans have no instincts", "Because culture requires writing to be transmitted", "Because it is acquired, learned, and transmitted through social processes, not genes"], answer: 3, explanation: "Culture is not biological because it is acquired, learned, shared, and transmitted through social processes — not inherited through DNA or genes.", difficulty: "medium", year: 2026 },
  { q: "The Technological Component of culture includes all of the following EXCEPT:", options: ["Arts and crafts", "Knowledge for producing food and shelter", "Tools and technology", "Authority structures and rules of behaviour"], answer: 3, explanation: "Authority structures and rules of behaviour belong to the Organisational Component, not the Technological Component.", difficulty: "medium", year: 2025 },
  { q: "The study notes list upright posture as a key feature that enabled culture because it:", options: ["Gave humans a larger brain for learning", "Enabled humans to develop a vocal tract for speech", "Made humans faster than other animals", "Freed the hands, enabling tool use and environmental manipulation"], answer: 3, explanation: "Upright posture (bipedalism) freed the human hands from locomotion, directly enabling the use and creation of tools and other cultural artefacts.", difficulty: "medium", year: 2026 },
  { q: "Non-material culture, as defined in the notes, consists of things that:", options: ["Can be seen and photographed", "Can be bought and sold in a market", "Are physical and can be felt", "Cannot be physically touched — they are intangible and abstract"], answer: 3, explanation: "Non-Material Culture is intangible/abstract — things that cannot be physically touched. Examples include values, beliefs, language, myths, worldview, religion, norms, and proverbs.", difficulty: "medium", year: 2026 },
  { q: "Which of the following BEST summarises the Importance of Culture?", options: ["Culture is important only for artistic expression", "Culture matters only to traditional societies", "Culture is relevant only to politics and governance", "Culture provides identity, a framework for behaviour, enables survival, continuity, and adaptation"], answer: 3, explanation: "Culture's importance: giving identity, distinguishing groups, providing a framework for behaviour, enabling transmission through socialisation/education, and ensuring survival, continuity, and adaptation.", difficulty: "medium", year: 2025 },
  { q: "'Cosmovision' or 'worldview' falls under which type of culture?", options: ["Material culture", "Technological culture", "Ideological component only", "Non-material culture"], answer: 3, explanation: "Worldview (cosmovision) falls under Non-Material Culture, alongside values, beliefs, language, myths, religion, norms, aesthetics, medical knowledge, and proverbs.", difficulty: "medium", year: 2026 },
  { q: "The transmission of culture from one generation to the next is PRIMARILY accomplished through:", options: ["Biological reproduction and genetics", "Trade and commerce between groups", "Military conquest and colonisation", "Enculturation, socialisation, and formal education"], answer: 3, explanation: "The three mechanisms of cultural transmission are enculturation, socialisation, and formal education — social processes, not biological ones.", difficulty: "medium", year: 2026 },
  { q: "Culture is used by humans for which THREE purposes?", options: ["Entertainment, recreation, and communication", "Governance, law-making, and taxation", "Language development, art creation, and technology", "Survival, continuity, and adaptation"], answer: 3, explanation: "Culture is used by humans for survival, continuity, and adaptation.", difficulty: "medium", year: 2025 },
  { q: "The phrase 'aggregate of a people's way of life' emphasises that culture is:", options: ["An individual achievement", "A government-created system", "A natural instinct", "The sum total of all a group's practices and ways of living"], answer: 3, explanation: "'Aggregate' means the total sum — the collective whole — of everything a group does and believes.", difficulty: "medium", year: 2026 },
  { q: "Culture developing alongside the evolution of Homo sapiens suggests that culture is:", options: ["A recent invention of modern civilisation", "Possible only after written language was developed", "Only present in large urban societies", "As old as humanity itself and intrinsic to being human"], answer: 3, explanation: "Since culture developed alongside Homo sapiens and the earliest evidence goes back over 2 million years, culture is essentially as old as humanity.", difficulty: "medium", year: 2026 },
  { q: "The notes describe culture as 'a learned way of life passed down through socialisation, embodying:'", options: ["Only written texts and formal knowledge", "Only religious practices and festivals", "Only material artefacts", "Mental and physical, material and non-material forms through which people meet their daily needs"], answer: 3, explanation: "This definition covers both tangible and intangible dimensions — mental and physical, material and non-material forms through which people meet their daily needs.", difficulty: "medium", year: 2025 },
  { q: "The example given in the notes for de-territorialised culture is:", options: ["Americans spreading their culture through Hollywood", "Igbo people maintaining their culture in Lagos", "Hausa traders spreading culture along trade routes", "Yoruba culture being practised outside of Yorubaland"], answer: 3, explanation: "The specific example given is: 'You do not need to be physically in Yorubaland to experience or practice Yoruba culture.'", difficulty: "medium", year: 2026 },
  { q: "According to the notes, the two MAJOR aspects of culture are:", options: ["Ideological and Organisational", "Dynamic and Static", "Global and Local", "Material and Non-Material"], answer: 3, explanation: "Culture has two major aspects: 1. Material Culture (Tangible/Visible) and 2. Non-Material Culture (Intangible/Abstract).", difficulty: "medium", year: 2026 },
  { q: "Which of the following groups is specifically cited in the Nigerian context summary definition of culture?", options: ["Americans, British, French, and Germans", "Arabs, Chinese, Indians, and Japanese", "Zulu, Ashanti, Swahili, and Mandinka", "Yoruba, Igbo, Hausa, and Ijaw"], answer: 3, explanation: "The Summary Definition for Nigerian Context explicitly cites Yoruba, Igbo, Hausa, Ijaw, etc. as examples.", difficulty: "medium", year: 2025 },
];

// Read the data.js file
const dataPath = path.join(__dirname, '..', 'src', 'data.js');
let content = fs.readFileSync(dataPath, 'utf8');

// Find the GST 115 section
const gstStart = content.indexOf('id: "gst115"');
const gstEnd = content.indexOf('id: "phy111"', gstStart);

if (gstStart === -1 || gstEnd === -1) {
  console.error('Could not find GST 115 section');
  process.exit(1);
}

// Find the questions array start and end within GST 115 section
const gstSection = content.substring(gstStart, gstEnd);
const questionsStart = gstSection.indexOf('questions: [');
const questionsEnd = gstSection.lastIndexOf('],');

if (questionsStart === -1 || questionsEnd === -1) {
  console.error('Could not find questions array in GST 115 section');
  process.exit(1);
}

// Build the new questions string
const questionsStr = newQuestions.map(q => {
  return `      { q: "${q.q.replace(/"/g, '\\"')}", options: ${JSON.stringify(q.options)}, answer: ${q.answer}, explanation: "${q.explanation.replace(/"/g, '\\"')}", difficulty: "${q.difficulty}", year: ${q.year} }`;
}).join(',\n');

// Replace the old questions with new ones
const beforeQuestions = gstSection.substring(0, questionsStart + 'questions: ['.length);
const afterQuestions = gstSection.substring(questionsEnd);

const newGstSection = beforeQuestions + '\n' + questionsStr + '\n    ' + afterQuestions;

// Replace in the original content
const before = content.substring(0, gstStart);
const after = content.substring(gstEnd);
const newContent = before + newGstSection + after;

// Write back
fs.writeFileSync(dataPath, newContent, 'utf8');

console.log('Successfully replaced GST 115 questions!');
console.log(`Total questions: ${newQuestions.length}`);
console.log(`Year 2026: ${newQuestions.filter(q => q.year === 2026).length} (80%)`);
console.log(`Year 2025: ${newQuestions.filter(q => q.year === 2025).length} (20%)`);
