/**
 * Embedded lab reference database.
 * Educational reference only — ranges vary by lab, age, assay, and clinical
 * context. Always defer to the reporting laboratory's reference interval.
 *
 *   aliases   — extra search terms (abbreviations, synonyms)
 *   unit      — SI/display unit; `conv` = conventional-unit string where a
 *               standard conversion exists (e.g. creatinine µmol/L ↔ mg/dL)
 *   male/female — adult reference ranges (display strings)
 *   critical_low/high — flag thresholds (display strings, may be "")
 *   low/high  — concise causes for abnormal results ("" = rarely clinically used)
 *   note      — high-yield exam/clinical pearl
 *   numeric   — { lo, hi } in `unit` for the value checker (null if range is
 *               not numeric-parseable e.g. "Negative")
 */

// prettier-ignore
export const LAB_CATEGORIES = [
  { id: "hematology", label: "Hematology & CBC", icon: "🩸" },
  { id: "biochem", label: "Basic Chemistry & Electrolytes", icon: "⚡" },
  { id: "renal", label: "Renal", icon: "🫘" },
  { id: "liver", label: "Liver", icon: "🫁" },
  { id: "cardiac", label: "Cardiac", icon: "❤️" },
  { id: "lipid", label: "Lipids", icon: "🧈" },
  { id: "endocrine", label: "Endocrine & Metabolic", icon: "🦋" },
  { id: "inflammation", label: "Inflammation & Immunology", icon: "🔥" },
  { id: "coag", label: "Coagulation", icon: "🩹" },
  { id: "gas", label: "Blood Gas & Acid-Base", icon: "💨" },
  { id: "iron", label: "Iron Studies & Nutritional", icon: "🧲" },
  { id: "urine", label: "Urine & CSF", icon: "💧" },
  { id: "tumor", label: "Tumor Markers", icon: "🎗️" },
  { id: "therapeutic", label: "Therapeutic Drug Levels", icon: "💊" },
];

// prettier-ignore
export const LABS = [
  // ─── Hematology ────────────────────────────────────────────
  { parameter: "Hemoglobin", aliases: ["Hb", "Hgb"], category: "hematology", unit: "g/dL",
    male: "13.0–17.0", female: "12.0–15.5", critical_low: "<7", critical_high: ">20",
    conv: "g/L: ×10 (e.g. 130–170 g/L)",
    low: "Iron deficiency, chronic disease, B12/folate deficiency, blood loss, hemolysis, thalassemia, CKD",
    high: "Polycythemia vera, chronic hypoxia (COPD, altitude, smoking), dehydration",
    note: "Anemia workup branches on MCV: micro (<80) → iron/Thal; normo → chronic disease/renal; macro (>100) → B12/folate/alcohol/drugs.",
    numeric: { lo: 13, hi: 17 } },
  { parameter: "Hematocrit", aliases: ["Hct", "PCV"], category: "hematology", unit: "%",
    male: "40–52", female: "36–46", critical_low: "<20", critical_high: ">60",
    low: "Same causes as low hemoglobin", high: "Polycythemia, dehydration",
    note: "Roughly 3× the hemoglobin value.", numeric: { lo: 40, hi: 52 } },
  { parameter: "White Cell Count", aliases: ["WBC", "WCC", "TLC"], category: "hematology", unit: "×10⁹/L",
    male: "4.0–11.0", female: "4.0–11.0", critical_low: "<1.5", critical_high: ">30",
    conv: "cells/µL: ×1000 (e.g. 4,000–11,000)",
    low: "Viral infection, sepsis (overwhelming), chemotherapy, marrow failure, hypersplenism",
    high: "Bacterial infection, inflammation, steroids, leukemia, physiologic (stress, pregnancy)",
    note: "Left shift (bands) suggests acute bacterial infection; lymphocytosis → viral/pertussis/CLL.",
    numeric: { lo: 4, hi: 11 } },
  { parameter: "Neutrophils (absolute)", aliases: ["ANC"], category: "hematology", unit: "×10⁹/L",
    male: "2.0–7.5", female: "2.0–7.5", critical_low: "<0.5", critical_high: "—",
    low: "Neutropenia: viral, drugs (chemo, clozapine, carbimazole), B12/folate deficiency, sepsis",
    high: "Bacterial infection, inflammation, steroids, myeloproliferative",
    note: "ANC <0.5 = neutropenic sepsis risk — medical emergency with fever.",
    numeric: { lo: 2, hi: 7.5 } },
  { parameter: "Lymphocytes", aliases: [], category: "hematology", unit: "×10⁹/L",
    male: "1.5–4.0", female: "1.5–4.0", critical_low: "—", critical_high: "—",
    low: "HIV, steroids, immunosuppression, severe illness",
    high: "Viral infection (EBV, pertussis), CLL, acute lymphoblastic leukemia",
    note: "Atypical lymphocytes → think EBV/mononucleosis.", numeric: { lo: 1.5, hi: 4 } },
  { parameter: "Eosinophils", aliases: [], category: "hematology", unit: "×10⁹/L",
    male: "0.04–0.4", female: "0.04–0.4", critical_low: "—", critical_high: ">5.0",
    low: "Cushing's, steroids, acute stress (not clinically useful)",
    high: "Allergy/atopy, parasites, drug reactions, asthma, hypereosinophilic syndromes, adrenal insufficiency",
    note: "Think 'AA-PD': Allergy, Asthma, Parasites, Drugs.", numeric: { lo: 0.04, hi: 0.4 } },
  { parameter: "Platelets", aliases: ["Plt"], category: "hematology", unit: "×10⁹/L",
    male: "150–400", female: "150–400", critical_low: "<20 (bleeding risk)", critical_high: ">1000",
    low: "ITP, DIC, TTP/HUS, sepsis, drugs (heparin — HIT!), hypersplenism, marrow failure, viral",
    high: "Reactive (infection, iron deficiency, post-splenectomy), essential thrombocythemia",
    note: "<50 → surgical bleeding risk; <20 → spontaneous bleeding risk. Check film for clumping (EDTA pseudo-thrombocytopenia).",
    numeric: { lo: 150, hi: 400 } },
  { parameter: "MCV", aliases: ["Mean Corpuscular Volume"], category: "hematology", unit: "fL",
    male: "80–100", female: "80–100", critical_low: "—", critical_high: "—",
    low: "Iron deficiency, thalassemia, chronic disease (late), sideroblastic",
    high: "B12/folate deficiency, alcohol, hypothyroidism, liver disease, reticulocytosis, MDS",
    note: "Micro + normal/high RDW → iron deficiency; micro + normal RBC count → thalassemia (Mentzer index <13).",
    numeric: { lo: 80, hi: 100 } },
  { parameter: "MCHC", aliases: [], category: "hematology", unit: "g/dL",
    male: "32–36", female: "32–36", critical_low: "—", critical_high: "—",
    low: "Iron deficiency (hypochromic cells), thalassemia",
    high: "Hereditary spherocytosis, severe hemolysis",
    note: "MCHC >36 with anemia → check for spherocytes on film.", numeric: { lo: 32, hi: 36 } },
  { parameter: "RDW", aliases: ["Red Cell Distribution Width"], category: "hematology", unit: "%",
    male: "11.5–14.5", female: "11.5–14.5", critical_low: "—", critical_high: "—",
    low: "—", high: "Iron deficiency (early), mixed deficiency, recent transfusion, reticulocytosis",
    note: "High RDW + low MCV → iron deficiency over thalassemia.", numeric: { lo: 11.5, hi: 14.5 } },
  { parameter: "Reticulocyte Count", aliases: ["Retic"], category: "hematology", unit: "%",
    male: "0.5–2.5", female: "0.5–2.5", critical_low: "—", critical_high: "—",
    low: "Marrow failure/aplastic anemia, B12/folate deficiency (untreated), chronic disease",
    high: "Hemolysis, acute blood loss, response to anemia treatment",
    note: "Anemia + high retic = losing cells (bleed/hemolysis); anemia + low retic = not making cells.",
    numeric: { lo: 0.5, hi: 2.5 } },
  { parameter: "ESR", aliases: ["Erythrocyte Sedimentation Rate", "Sed rate"], category: "hematology", unit: "mm/h",
    male: "<(age÷2)", female: "<(age+10)÷2", critical_low: "—", critical_high: ">100 (giant cell arteritis, myeloma)",
    low: "Polycythemia, low fibrinogen (not clinically used)",
    high: "Infection, inflammation, malignancy, giant cell arteritis, myeloma, anemia, pregnancy",
    note: "ESR >100 strongly suggests GCA, myeloma, or metastatic disease.", numeric: null },
  { parameter: "D-dimer", aliases: [], category: "coag", unit: "mg/L (FEU)",
    male: "<0.5", female: "<0.5", critical_low: "—", critical_high: "—",
    low: "—",
    high: "VTE (DVT/PE), DIC, infection, malignancy, pregnancy, post-op, age (age-adjusted cutoffs exist)",
    note: "HIGH NEGATIVE predictive value — a normal d-dimer rules out VTE in low/moderate pretest probability. Never a rule-in test.",
    numeric: null },
  { parameter: "PT / INR", aliases: ["Prothrombin Time", "INR"], category: "coag", unit: "seconds / ratio",
    male: "PT 11–13.5s · INR 0.9–1.1", female: "same", critical_low: "—", critical_high: "INR >5 (bleeding risk)",
    low: "Not clinically used",
    high: "Warfarin (target 2–3 or 2.5–3.5 mechanical valves), liver disease, vitamin K deficiency, DIC, factor deficiency",
    note: "INR standardizes PT across labs — used for warfarin monitoring only (not DOACs).",
    numeric: null },
  { parameter: "aPTT", aliases: ["Activated Partial Thromboplastin Time", "PTT"], category: "coag", unit: "seconds",
    male: "25–35", female: "25–35", critical_low: "—", critical_high: ">100 (on heparin → bleeding risk)",
    low: "Not clinically used",
    high: "Heparin, hemophilia A/B (factor VIII/IX), vWD, lupus anticoagulant, DIC, liver disease",
    note: "Prolonged aPTT + bleeding → factor deficiency; prolonged aPTT + clotting → lupus anticoagulant.",
    numeric: { lo: 25, hi: 35 } },
  { parameter: "Fibrinogen", aliases: [], category: "coag", unit: "g/L",
    male: "2.0–4.0", female: "2.0–4.0", critical_low: "<1.0", critical_high: "—",
    conv: "mg/dL: ×100",
    low: "DIC (consumption), liver failure, massive transfusion",
    high: "Acute phase response (inflammation), pregnancy",
    note: "Falls in DIC while PT/aPTT rise — key differentiator from liver disease alone.",
    numeric: { lo: 2, hi: 4 } },
  { parameter: "Bleeding Time", aliases: [], category: "coag", unit: "minutes",
    male: "2–9", female: "2–9", critical_low: "—", critical_high: "—",
    low: "—",
    high: "Platelet dysfunction (aspirin, uremia), vWD",
    note: "Largely replaced by PFA-100/200; still asked in exams for aspirin/vWD.",
    numeric: null },

  // ─── Basic chemistry & electrolytes ───────────────────────
  { parameter: "Sodium", aliases: ["Na", "Na+"], category: "biochem", unit: "mmol/L",
    male: "135–145", female: "135–145", critical_low: "<120", critical_high: ">160",
    low: "SIADH, diuretics (thiazide!), vomiting/diarrhea, heart failure, hypothyroidism, psychogenic polydipsia, pseudohyponatremia (high lipids/protein)",
    high: "Dehydration, diabetes insipidus, osmotic diuresis, excess saline/aldosteronism",
    note: "Symptomatic/severe hypoNa: hypertonic saline — correct ≤8–10 mmol/L per 24h (osmotic demyelination risk).",
    numeric: { lo: 135, hi: 145 } },
  { parameter: "Potassium", aliases: ["K", "K+"], category: "biochem", unit: "mmol/L",
    male: "3.5–5.0", female: "3.5–5.0", critical_low: "<2.5", critical_high: ">6.0",
    low: "Diuretics, vomiting/diarrhea, alkalosis (shifts in), insulin, β-agonists, hyperaldosteronism, poor intake",
    high: "Renal failure, ACEi/ARB/K-sparing diuretics, acidosis (shifts out), cell lysis (tumor, rhabdo, hemolysis — check sample!), Addison's",
    note: "Hemolysed sample falsely elevates K+. K≥6 with ECG changes = emergency: calcium gluconate first.",
    numeric: { lo: 3.5, hi: 5 } },
  { parameter: "Chloride", aliases: ["Cl", "Cl-"], category: "biochem", unit: "mmol/L",
    male: "98–107", female: "98–107", critical_low: "<80", critical_high: ">120",
    low: "Vomiting (with metabolic alkalosis), diuretics",
    high: "Diarrhea (NAGMA), renal tubular acidosis, hyperchloremic acidosis (excess saline)",
    note: "Follows sodium; chloride-bicarbonate inverse relationship in acid-base.",
    numeric: { lo: 98, hi: 107 } },
  { parameter: "Bicarbonate", aliases: ["HCO3", "Total CO2", "TCO2"], category: "biochem", unit: "mmol/L",
    male: "22–29", female: "22–29", critical_low: "<10", critical_high: ">40",
    low: "Metabolic acidosis (DKA, lactic acidosis, renal failure), chronic respiratory alkalosis compensation",
    high: "Metabolic alkalosis (vomiting, diuretics), compensation for chronic respiratory acidosis (COPD)",
    note: "Anion gap = Na – (Cl + HCO3); normal 8–12.",
    numeric: { lo: 22, hi: 29 } },
  { parameter: "Anion Gap", aliases: ["AG"], category: "biochem", unit: "mmol/L",
    male: "8–12 (without K)", female: "8–12", critical_low: "—", critical_high: ">20",
    low: "Hypoalbuminemia, paraproteinemia, lithium",
    high: "MUDPILES: Methanol, Uremia, DKA, Propylene glycol/Paraldehyde, Isoniazid/Iron, Lactate, Ethylene glycol, Salicylates",
    note: "Correct for albumin: AG falls ~2.5 per 10g/L albumin drop.",
    numeric: { lo: 8, hi: 12 } },
  { parameter: "Calcium (total)", aliases: ["Ca", "Ca2+"], category: "biochem", unit: "mmol/L",
    male: "2.2–2.6", female: "2.2–2.6", critical_low: "<1.9", critical_high: ">3.0",
    conv: "mg/dL: ×4.0 (2.2–2.6 mmol/L ≈ 8.8–10.4 mg/dL)",
    low: "Hypoparathyroidism, vitamin D deficiency, CKD, pancreatitis, magnesium deficiency",
    high: "Hyperparathyroidism, malignancy (PTHrP, bone mets, myeloma), vitamin D excess, thiazides, granulomatous disease (sarcoid)",
    note: "Always correct for albumin: corrected Ca = measured + 0.02×(40−albumin g/L). Or check ionized Ca.",
    numeric: { lo: 2.2, hi: 2.6 } },
  { parameter: "Ionized Calcium", aliases: ["iCa"], category: "biochem", unit: "mmol/L",
    male: "1.12–1.32", female: "1.12–1.32", critical_low: "<0.9", critical_high: ">1.6",
    low: "As total calcium — but independent of albumin",
    high: "As total calcium", note: "The physiologically active fraction; preferred in critical illness.",
    numeric: { lo: 1.12, hi: 1.32 } },
  { parameter: "Magnesium", aliases: ["Mg", "Mg2+"], category: "biochem", unit: "mmol/L",
    male: "0.7–1.0", female: "0.7–1.0", critical_low: "<0.5", critical_high: ">2.0",
    conv: "mg/dL: ×2.43",
    low: "Diuretics, PPIs, alcoholism, diarrhea, poor intake, refeeding syndrome",
    high: "Renal failure, excess Mg (antacids, eclampsia treatment — monitor reflexes!)",
    note: "Low Mg causes refractory hypokalemia and hypocalcemia — replete Mg first.",
    numeric: { lo: 0.7, hi: 1 } },
  { parameter: "Phosphate", aliases: ["PO4", "Phos"], category: "biochem", unit: "mmol/L",
    male: "0.8–1.5", female: "0.8–1.5", critical_low: "<0.3", critical_high: "—",
    conv: "mg/dL: ×3.1",
    low: "Refeeding syndrome, hyperparathyroidism, DKA recovery, respiratory alkalosis, alcoholism",
    high: "CKD (early sign), hypoparathyroidism, rhabdomyolysis, tumor lysis",
    note: "Refreefeeding in starved patients → phosphate crash → respiratory/cardiac failure.",
    numeric: { lo: 0.8, hi: 1.5 } },
  { parameter: "Lactate", aliases: ["Lactic acid"], category: "gas", unit: "mmol/L",
    male: "0.5–2.2", female: "0.5–2.2", critical_low: "—", critical_high: ">4 (sepsis marker)",
    low: "—",
    high: "Type A (tissue hypoxia): sepsis, shock, seizures, ischemia. Type B (no hypoxia): metformin, liver failure, thiamine deficiency, malignancy",
    note: "Lactate >2 = elevated; >4 = high-risk in sepsis (Sepsis-3, qSOFA + lactate).",
    numeric: { lo: 0.5, hi: 2.2 } },
  { parameter: "Glucose (fasting)", aliases: ["FBS", "FPG", "Blood sugar"], category: "endocrine", unit: "mmol/L",
    male: "3.9–5.5", female: "3.9–5.5", critical_low: "<2.8", critical_high: ">20",
    conv: "mg/dL: ×18 (3.9–5.5 mmol/L ≈ 70–100 mg/dL)",
    low: "Excess insulin/oral hypoglycemics, alcohol, liver failure, sepsis, adrenal insufficiency, insulinoma",
    high: "Diabetes mellitus, stress hyperglycemia, steroids, pancreatitis",
    note: "DM diagnosis: fasting ≥7.0, random ≥11.1 with symptoms, or HbA1c ≥6.5% — confirm on repeat unless symptomatic.",
    numeric: { lo: 3.9, hi: 5.5 } },
  { parameter: "HbA1c", aliases: ["A1c", "Glycated hemoglobin"], category: "endocrine", unit: "%",
    male: "<5.7", female: "<5.7", critical_low: "—", critical_high: ">9 (poor control)",
    conv: "mmol/mol (IFCC): (HbA1c% − 2.15) × 10.93; e.g. 7% ≈ 53 mmol/mol",
    low: "Not clinically meaningful",
    high: "Diabetes (≥6.5% diagnostic); prediabetes 5.7–6.4%; target usually <7%",
    note: "Falsely low: hemolysis, recent transfusion, CKD, hemoglobinopathies (use fructosamine instead).",
    numeric: { lo: 4, hi: 5.6 } },
  { parameter: "Urea (BUN)", aliases: ["Blood Urea Nitrogen"], category: "renal", unit: "mmol/L (urea)",
    male: "2.5–7.1", female: "2.5–7.1", critical_low: "—", critical_high: ">30",
    conv: "BUN mg/dL: urea mmol/L × 2.8 (2.5–7.1 ≈ 7–20 mg/dL BUN)",
    low: "Low protein intake, liver failure, overhydration, pregnancy",
    high: "Dehydration, renal impairment, GI bleed, high protein intake/catabolism",
    note: "BUN:creatinine ratio (mg/dL) >20:1 suggests prerenal/GI bleed.",
    numeric: { lo: 2.5, hi: 7.1 } },
  { parameter: "Creatinine", aliases: ["Cr", "SCr"], category: "renal", unit: "µmol/L",
    male: "62–115", female: "53–97", critical_low: "—", critical_high: ">400 (or rising rapidly)",
    conv: "mg/dL: ÷88.4 (62–115 µmol/L ≈ 0.7–1.3 mg/dL)",
    low: "Low muscle mass, pregnancy (falls)",
    high: "Renal impairment (AKI/CKD), muscle mass, rhabdomyolysis, drugs (TMP, cimetidine block secretion)",
    note: "Small rise = large GFR loss (non-linear). eGFR more informative. AKI (KDIGO): ↑≥26.5µmol/L in 48h or ×1.5 baseline in 7d.",
    numeric: { lo: 62, hi: 115 } },
  { parameter: "eGFR", aliases: ["Estimated GFR"], category: "renal", unit: "mL/min/1.73m²",
    male: ">90", female: ">90", critical_low: "<15 (dialysis territory)", critical_high: "—",
    low: "CKD staging: G2 60–89, G3a 45–59, G3b 30–44, G4 15–29, G5 <15",
    high: "Not pathological (pregnancy, early diabetes hyperfiltration)",
    note: "CKD = G3+ or markers of damage for ≥3 months. Adjust drug doses below 60; nephrology referral <30.",
    numeric: null },
  { parameter: "Uric Acid", aliases: ["Urate"], category: "renal", unit: "mmol/L",
    male: "0.20–0.43", female: "0.14–0.36", critical_low: "—", critical_high: ">0.7 (tumor lysis risk)",
    conv: "mg/dL: ×16.8 (0.20–0.43 ≈ 3.5–7.2 mg/dL)",
    low: "Allopurinol treatment, SIADH, Fanconi",
    high: "Gout risk, tumor lysis, renal impairment, diuretics, metabolic syndrome, alcohol",
    note: "Asymptomatic hyperuricemia ≠ gout; treat gout diagnosis/clinical picture not the number.",
    numeric: { lo: 0.2, hi: 0.43 } },

  // ─── Liver ─────────────────────────────────────────────────
  { parameter: "ALT", aliases: ["Alanine aminotransferase", "SGPT"], category: "liver", unit: "U/L",
    male: "10–50", female: "7–35", critical_low: "—", critical_high: ">1000 (acute hepatitis, ischemia, paracetamol)",
    low: "—",
    high: "Hepatocellular injury: viral hepatitis, NAFLD, alcohol, drugs (paracetamol, statins), ischemic hepatitis",
    note: "ALT more liver-specific than AST. ALT >1000: viral, ischemia, toxin/paracetamol.",
    numeric: { lo: 10, hi: 50 } },
  { parameter: "AST", aliases: ["Aspartate aminotransferase", "SGOT"], category: "liver", unit: "U/L",
    male: "10–40", female: "9–32", critical_low: "—", critical_high: ">1000",
    low: "—",
    high: "Liver injury, muscle injury (rhabdo), MI (historic), hemolysis",
    note: "AST:ALT >2 suggests alcoholic hepatitis; AST less liver-specific (muscle, RBC).",
    numeric: { lo: 10, hi: 40 } },
  { parameter: "ALP", aliases: ["Alkaline phosphatase"], category: "liver", unit: "U/L",
    male: "40–129", female: "35–104", critical_low: "—", critical_high: "—",
    low: "Hypothyroidism, zinc deficiency, hypophosphatasia (rare)",
    high: "Cholestasis (obstruction, PBC, PSC), bone disease (Paget's, mets, healing fracture), pregnancy (placental), adolescents",
    note: "Isolated ALP↑: check GGT — ↑GGT = liver source; normal GGT = bone/placenta.",
    numeric: { lo: 40, hi: 129 } },
  { parameter: "GGT", aliases: ["Gamma-GT", "Gamma glutamyl transferase"], category: "liver", unit: "U/L",
    male: "8–61", female: "5–36", critical_low: "—", critical_high: "—",
    low: "—",
    high: "Alcohol use, cholestasis, drugs (enzyme inducers — phenytoin, carbamazepine), NAFLD",
    note: "Confirms hepatic origin of raised ALP; sensitive alcohol/steatosis marker but non-specific.",
    numeric: { lo: 8, hi: 61 } },
  { parameter: "Bilirubin (total)", aliases: ["TBili", "Bili"], category: "liver", unit: "µmol/L",
    male: "3–21", female: "3–21", critical_low: "—", critical_high: ">50 (visible jaundice) / neonatal thresholds differ",
    conv: "mg/dL: ÷17.1 (3–21 µmol/L ≈ 0.2–1.2 mg/dL)",
    low: "—",
    high: "Pre-hepatic (hemolysis, Gilbert — unconjugated), hepatocellular (hepatitis), post-hepatic (obstruction — conjugated)",
    note: "Unconjugated + normal LFTs = Gilbert's (common, benign). Conjugated + ↑ALP = obstruction — image.",
    numeric: { lo: 3, hi: 21 } },
  { parameter: "Direct Bilirubin", aliases: ["Conjugated bilirubin"], category: "liver", unit: "µmol/L",
    male: "0–5", female: "0–5", critical_low: "—", critical_high: "—",
    low: "—",
    high: "Hepatocellular disease, obstruction (stones, stricture, tumor), Dubin-Johnson/Rotor",
    note: "Conjugated bilirubin is water-soluble → bilirubinuria → dark urine.",
    numeric: { lo: 0, hi: 5 } },
  { parameter: "Albumin", aliases: ["Alb"], category: "liver", unit: "g/L",
    male: "35–50", female: "35–50", critical_low: "<20 (edema risk)", critical_high: "—",
    conv: "g/dL: ÷10 (3.5–5.0 g/dL)",
    low: "Liver disease, nephrotic syndrome, malnutrition, inflammation (negative acute phase), protein-losing enteropathy",
    high: "Dehydration (only cause — not overproduction)",
    note: "t½ ~20 days — marker of chronic, not acute, synthesis. Use for anion gap & calcium correction.",
    numeric: { lo: 35, hi: 50 } },
  { parameter: "Total Protein", aliases: ["TP"], category: "liver", unit: "g/L",
    male: "60–83", female: "60–83", critical_low: "—", critical_high: "—",
    low: "Malnutrition, nephrotic syndrome, liver disease, overhydration",
    high: "Dehydration, paraproteinemia (myeloma — do protein electrophoresis)",
    note: "High TP + normal albumin → globulin gap → SPEP for myeloma.",
    numeric: { lo: 60, hi: 83 } },
  { parameter: "Ammonia", aliases: ["NH3"], category: "liver", unit: "µmol/L",
    male: "11–35", female: "11–35", critical_low: "—", critical_high: ">100 (encephalopathy)",
    low: "—",
    high: "Hepatic encephalopathy, liver failure, urea cycle disorders, valproate toxicity, portosystemic shunt",
    note: "Handle on ice, analyze fast (false elevation). TREAT the patient, not the number — lactulose to stool count.",
    numeric: { lo: 11, hi: 35 } },
  { parameter: "Lipase", aliases: [], category: "liver", unit: "U/L",
    male: "13–60", female: "13–60", critical_low: "—", critical_high: ">3× ULN (pancreatitis)",
    low: "—",
    high: "Acute pancreatitis (≥3× ULN diagnostic), pancreatic duct obstruction, renal impairment (mild)",
    note: "More specific and longer-elevated than amylase for pancreatitis.",
    numeric: { lo: 13, hi: 60 } },
  { parameter: "Amylase", aliases: [], category: "liver", unit: "U/L",
    male: "28–100", female: "28–100", critical_low: "—", critical_high: ">3× ULN",
    low: "—",
    high: "Pancreatitis (rises fast, falls fast — misses late presentations), salivary disease, macroamylasemia, renal failure",
    note: "Less specific than lipase; normal amylase doesn't exclude pancreatitis after day 2–3.",
    numeric: { lo: 28, hi: 100 } },

  // ─── Cardiac ───────────────────────────────────────────────
  { parameter: "Troponin I/T", aliases: ["cTnI", "cTnT", "hs-TnT"], category: "cardiac", unit: "ng/L (hs assays)",
    male: "<14 (hs-cTnT 99th percentile)", female: "<14", critical_low: "—", critical_high: "Any rise+delta = myocardial injury",
    conv: "Varies by assay — use lab-specific 99th percentile",
    low: "—",
    high: "MI (rise and/or fall pattern), myocarditis, PE, sepsis, renal failure, HF, tachyarrhythmia (Type 2 MI vs Type 1)",
    note: "Interpret the DELTA (0h/1h or 0h/3h) not a single value. Elevated troponin ≠ always ACS — think demand ischemia.",
    numeric: null },
  { parameter: "CK-MB", aliases: [], category: "cardiac", unit: "U/L",
    male: "<25 (or <5% of total CK)", female: "<25", critical_low: "—", critical_high: "—",
    low: "—",
    high: "MI (falls in 48–72h → useful for re-infarction), myocarditis, muscle injury",
    note: "Largely replaced by troponin; niche role for detecting re-infarction (returns to baseline faster).",
    numeric: null },
  { parameter: "CK (total)", aliases: ["Creatine kinase", "CPK"], category: "cardiac", unit: "U/L",
    male: "39–308", female: "26–192", critical_low: "—", critical_high: ">5000 (rhabdo — AKI risk)",
    low: "—",
    high: "Rhabdomyolysis, statins/exercise (mild), muscular dystrophy, hypothyroidism, seizures, IM injections",
    note: "Rhabdo: CK >5× ULN + symptoms; check creatinine, K+, Ca, urine for myoglobin.",
    numeric: { lo: 39, hi: 308 } },
  { parameter: "BNP", aliases: ["B-type natriuretic peptide"], category: "cardiac", unit: "pg/mL",
    male: "<100", female: "<100", critical_low: "—", critical_high: ">400 supports HF",
    low: "—",
    high: "Heart failure, AF, renal impairment, age, PE (mild), sepsis",
    note: "BNP <100 → HF unlikely (high NPV). NT-proBNP higher cutoffs (<300 rule-out acute, age-adjusted rule-in). Obesity lowers BNP.",
    numeric: null },
  { parameter: "NT-proBNP", aliases: [], category: "cardiac", unit: "pg/mL",
    male: "Age-adjusted: <450 (<50y), <900 (50–75y), <1800 (>75y)", female: "same",
    critical_low: "—", critical_high: ">1800 strongly suggests HF",
    low: "—",
    high: "Heart failure, renal impairment (accumulates), AF, age",
    note: "<300 pg/mL rules out acute HF (99% NPV). Not on ARNI? Entresto raises BNP but not NT-proBNP — prefer NT-proBNP.",
    numeric: null },
  { parameter: "LDH", aliases: ["Lactate dehydrogenase"], category: "cardiac", unit: "U/L",
    male: "140–280", female: "140–280", critical_low: "—", critical_high: "—",
    low: "—",
    high: "Hemolysis, tissue turnover (tumor lysis, lymphoma), liver injury, MI (historic), megaloblastic anemia (very high)",
    note: "Very non-specific; pattern + context (e.g. B12/folate deficiency can give LDH >1000).",
    numeric: { lo: 140, hi: 280 } },
  { parameter: "Homocysteine", aliases: [], category: "cardiac", unit: "µmol/L",
    male: "5–15", female: "5–15", critical_low: "—", critical_high: ">100 (homocystinuria)",
    low: "—",
    high: "B12/folate deficiency, renal impairment, genetic (MTHFR, CBS deficiency), hypothyroidism",
    note: "Mild elevations common; very high in homocystinuria — thrombosis + lens dislocation + marfanoid.",
    numeric: { lo: 5, hi: 15 } },

  // ─── Lipids ────────────────────────────────────────────────
  { parameter: "Total Cholesterol", aliases: ["TC"], category: "lipid", unit: "mmol/L",
    male: "<5.0 desirable", female: "<5.0", critical_low: "—", critical_high: ">7.5 (familial hypercholesterolemia workup)",
    conv: "mg/dL: ×38.7 (5.0 mmol/L ≈ 194 mg/dL)",
    low: "Malnutrition, hyperthyroidism, liver failure",
    high: "Primary dyslipidemia, diet, hypothyroidism, nephrotic syndrome, cholestasis",
    note: "Non-fasting acceptable for screening; interpret via cardiovascular risk score (QRISK/ASCVD).",
    numeric: null },
  { parameter: "LDL Cholesterol", aliases: ["LDL-C"], category: "lipid", unit: "mmol/L",
    male: "<3.0 (targets lower by risk)", female: "<3.0", critical_low: "—", critical_high: ">4.9 (likely FH)",
    conv: "mg/dL: ×38.7 (3.0 ≈ 116 mg/dL)",
    low: "Overtreatment, malnutrition, hyperthyroidism",
    high: "Familial hypercholesterolemia (≥4.9 → cascade screen), diet, hypothyroidism, nephrotic syndrome",
    note: "Targets: <1.4 very high risk, <1.8 high risk, <2.6 moderate (ESC). Calculated LDL invalid when TG >4.5.",
    numeric: null },
  { parameter: "HDL Cholesterol", aliases: ["HDL-C"], category: "lipid", unit: "mmol/L",
    male: ">1.0", female: ">1.2", critical_low: "—", critical_high: "—",
    conv: "mg/dL: ×38.7 (1.0 ≈ 39 mg/dL)",
    low: "Metabolic syndrome, smoking, diabetes, sedentary — CV risk factor",
    high: "Not harmful; very high HDL does not offset LDL risk",
    note: "Don't chase HDL — treat LDL.",
    numeric: null },
  { parameter: "Triglycerides", aliases: ["TG"], category: "lipid", unit: "mmol/L",
    male: "<1.7", female: "<1.7", critical_low: "—", critical_high: ">10 (pancreatitis risk)",
    conv: "mg/dL: ×88.5 (1.7 mmol/L ≈ 150 mg/dL)",
    low: "—",
    high: "Diabetes/metabolic syndrome, alcohol, obesity, drugs (steroids, retinoids), familial",
    note: ">10 mmol/L → acute pancreatitis risk — fibrates + strict control; fast 8–12h for accuracy.",
    numeric: null },
  { parameter: "Non-HDL Cholesterol", aliases: ["non-HDL-C"], category: "lipid", unit: "mmol/L",
    male: "<3.8", female: "<3.8", critical_low: "—", critical_high: "—",
    conv: "TC minus HDL",
    low: "—",
    high: "Captures all atherogenic particles (LDL+VLDL+remnants) — useful when TG elevated",
    note: "Secondary target; roughly LDL target + 0.8 mmol/L.",
    numeric: null },

  // ─── Endocrine / metabolic ────────────────────────────────
  { parameter: "TSH", aliases: ["Thyroid stimulating hormone"], category: "endocrine", unit: "mIU/L",
    male: "0.4–4.0", female: "0.4–4.0", critical_low: "—", critical_high: ">10 (treatment threshold varies)",
    low: "Hyperthyroidism (Graves, toxic nodules), pituitary failure, excess levothyroxine",
    high: "Primary hypothyroidism (Hashimoto's), recovery from illness, inadequate levothyroxine/adherence",
    note: "TSH first-line screen. Pregnancy trimester-specific ranges apply. Central hypothyroidism: low T4 with inappropriately normal TSH.",
    numeric: { lo: 0.4, hi: 4 } },
  { parameter: "Free T4", aliases: ["fT4", "FT4"], category: "endocrine", unit: "pmol/L",
    male: "9–22", female: "9–22", critical_low: "—", critical_high: "—",
    conv: "ng/dL: ÷12.87 (9–22 pmol/L ≈ 0.7–1.7 ng/dL)",
    low: "Hypothyroidism, severe illness (sick euthyroid)",
    high: "Hyperthyroidism, excess levothyroxine",
    note: "TSH↑+fT4↓ = primary hypo; TSH↓+fT4↑ = primary hyper; discordant → central causes or interference.",
    numeric: { lo: 9, hi: 22 } },
  { parameter: "Free T3", aliases: ["fT3", "FT3"], category: "endocrine", unit: "pmol/L",
    male: "2.6–5.7", female: "2.6–5.7", critical_low: "—", critical_high: "—",
    low: "Hypothyroidism, sick euthyroid (low T3 syndrome)",
    high: "Hyperthyroidism (T3 toxicosis — T3 high with normal T4)",
    note: "Not used to monitor hypothyroid treatment (T4→T3 conversion is peripheral).",
    numeric: { lo: 2.6, hi: 5.7 } },
  { parameter: "Cortisol (8am)", aliases: ["Morning cortisol"], category: "endocrine", unit: "nmol/L",
    male: "138–690 (9am peak)", female: "same", critical_low: "<100 (adrenal crisis risk)", critical_high: "—",
    conv: "µg/dL: ÷27.6 (138–690 ≈ 5–25 µg/dL)",
    low: "Adrenal insufficiency (primary: autoimmune, TB; secondary: pituitary, steroids)",
    high: "Cushing's syndrome, stress, depression, OCPs (↑CBG — falsely high)",
    note: "Random cortisol unhelpful — do 9am or short Synacthen test. <85 = adrenal insufficiency until proven otherwise.",
    numeric: { lo: 138, hi: 690 } },
  { parameter: "PTH", aliases: ["Parathyroid hormone"], category: "endocrine", unit: "pmol/L",
    male: "1.6–6.9", female: "1.6–6.9", critical_low: "—", critical_high: "—",
    conv: "pg/mL: ×9.4 (≈15–65 pg/mL)",
    low: "Primary hypoparathyroidism, post-surgical, hypomagnesemia",
    high: "Primary hyperparathyroidism (with high Ca), secondary (CKD, vit D deficiency — low/normal Ca)",
    note: "Always interpret against simultaneous calcium: high Ca + high/inappropriate PTH = primary hyperparathyroidism.",
    numeric: { lo: 1.6, hi: 6.9 } },
  { parameter: "Vitamin D (25-OH)", aliases: ["25(OH)D", "Calcidiol"], category: "endocrine", unit: "nmol/L",
    male: ">50 sufficient (>75 optimal by some)", female: "same", critical_low: "<25 (deficiency)", critical_high: "—",
    conv: "ng/mL: ÷2.5 (50 nmol/L = 20 ng/mL)",
    low: "Deficiency: low sun, malabsorption, CKD conversion issues, obesity",
    high: "Supplementation excess — hypercalcemia",
    note: "<25 deficient, 25–50 insufficient. Deficiency → ↓Ca/↓phosphate, ↑PTH (secondary hyperparathyroidism).",
    numeric: { lo: 50, hi: 250 } },
  { parameter: "Prolactin", aliases: ["PRL"], category: "endocrine", unit: "mIU/L",
    male: "<400", female: "<500", critical_low: "—", critical_high: ">5000 (macroprolactinoma likely)",
    conv: "ng/mL: ÷21.2 (400 mIU/L ≈ 19 ng/mL)",
    low: "—",
    high: "Prolactinoma, drugs (antipsychotics, metoclopramide), pregnancy, hypothyroidism, stress, macroprolactin (benign)",
    note: "Stress/stimulation raises it — repeat with cannula/rest if mildly elevated. Check TSH & macroprolactin first.",
    numeric: { lo: 0, hi: 500 } },
  { parameter: "Testosterone (8am)", aliases: ["T"], category: "endocrine", unit: "nmol/L",
    male: "10–30", female: "0.5–2.4", critical_low: "—", critical_high: "—",
    conv: "ng/dL: ×28.8 (10–30 nmol/L ≈ 290–860 ng/dL)",
    low: "Primary testicular failure, pituitary/hypothalamic disease, opioids, age",
    high: "PCOS (women), exogenous androgens, congenital adrenal hyperplasia, tumors",
    note: "Morning sample (diurnal); confirm low result twice with LH/FSH to localize.",
    numeric: { lo: 10, hi: 30 } },
  { parameter: "FSH", aliases: ["Follicle stimulating hormone"], category: "endocrine", unit: "IU/L",
    male: "1.5–12", female: "Follicular 3–9 · midcycle 6–25 · postmeno 30–120", critical_low: "—", critical_high: "—",
    low: "Hypothalamic/pituitary failure (secondary hypogonadism)",
    high: "Primary gonadal failure (menopause, Turner syndrome, testicular failure)",
    note: "Interpret with LH + estradiol/testosterone; contraceptives suppress.",
    numeric: null },
  { parameter: "LH", aliases: ["Luteinizing hormone"], category: "endocrine", unit: "IU/L",
    male: "1.7–8.6", female: "Follicular 2–10 · midcycle peak 20–100", critical_low: "—", critical_high: "—",
    low: "Pituitary/hypothalamic failure",
    high: "Primary gonadal failure, PCOS (LH:FSH >2 historically)",
    note: "PCOS diagnosis now Rotterdam criteria — LH ratio supportive only.",
    numeric: null },
  { parameter: "Estradiol (E2)", aliases: ["Oestradiol"], category: "endocrine", unit: "pmol/L",
    male: "<150", female: "Follicular 70–530 · midcycle 400–1700 · postmeno <130", critical_low: "—", critical_high: "—",
    low: "Menopause, hypogonadism, ovarian failure",
    high: "Ovarian hyperstimulation, granulosa cell tumors, exogenous",
    note: "Highly cycle-dependent — note cycle day when sampling.",
    numeric: null },
  { parameter: "β-hCG", aliases: ["HCG", "hCG"], category: "endocrine", unit: "IU/L",
    male: "<5", female: "<5 non-pregnant (pregnancy ranges by week)", critical_low: "—", critical_high: "—",
    low: "—",
    high: "Pregnancy (doubles ~q48h early — plateau ~10wk), molar pregnancy, choriocarcinoma/germ cell tumors (men too)",
    note: "Sub-optimal rise or plateau → ectopic/miscarriage workup. Men with raised hCG → testicular tumor screen.",
    numeric: null },
  { parameter: "Insulin (fasting)", aliases: [], category: "endocrine", unit: "pmol/L",
    male: "14–140", female: "14–140", critical_low: "—", critical_high: "—",
    conv: "µIU/mL: ÷6.94 (≈2–20 µIU/mL)",
    low: "Type 1 diabetes (with high glucose)",
    high: "Insulin resistance, insulinoma (inappropriately high during hypoglycemia — with C-peptide)",
    note: "Hypoglycemia + high insulin + high C-peptide = endogenous (insulinoma/sulfonylurea); low C-peptide = exogenous insulin.",
    numeric: { lo: 14, hi: 140 } },
  { parameter: "C-peptide", aliases: [], category: "endocrine", unit: "nmol/L",
    male: "0.27–1.2 (fasting)", female: "same", critical_low: "—", critical_high: "—",
    low: "Type 1 diabetes (low/absent endogenous insulin), exogenous insulin use",
    high: "Insulinoma, sulfonylurea use, insulin resistance",
    note: "The T1 vs T2 discriminator; detectable C-peptide years post-Dx suggests T2/LADA reconsideration.",
    numeric: { lo: 0.27, hi: 1.2 } },

  // ─── Inflammation & immunology ────────────────────────────
  { parameter: "CRP", aliases: ["C-reactive protein"], category: "inflammation", unit: "mg/L",
    male: "<5", female: "<5", critical_low: "—", critical_high: ">200 (severe infection/inflammation)",
    conv: "mg/dL: ÷10",
    low: "—",
    high: "Bacterial infection, inflammation, tissue necrosis, malignancy; chronic mild ↑ with obesity/smoking",
    note: "Rises/falls fast (t½ ~19h) — good for tracking treatment response. Viral infections usually mild/moderate rise.",
    numeric: null },
  { parameter: "Procalcitonin", aliases: ["PCT"], category: "inflammation", unit: "ng/mL",
    male: "<0.05", female: "<0.05", critical_low: "—", critical_high: ">2 (high sepsis likelihood)",
    low: "—",
    high: "Bacterial sepsis (correlates with severity), meningitis; NOT elevated much in viral/local inflammation",
    note: "Supports antibiotic de-escalation protocols; <0.25 argues against systemic bacterial infection.",
    numeric: { lo: 0, hi: 0.05 } },
  { parameter: "Ferritin", aliases: [], category: "iron", unit: "µg/L",
    male: "30–300", female: "15–150", critical_low: "—", critical_high: ">1000 (hemochromatosis, HLH, Still's)",
    conv: "ng/mL: same number (µg/L = ng/mL)",
    low: "Iron deficiency (earliest marker — <30 diagnostic even with normal Hb)",
    high: "Iron overload (hemochromatosis), inflammation/infection (acute phase!), liver disease, malignancy",
    note: "Acute phase reactant — 'normal' ferritin can hide deficiency during inflammation; check CRP + transferrin sat.",
    numeric: { lo: 30, hi: 300 } },
  { parameter: "Serum Iron", aliases: ["Fe"], category: "iron", unit: "µmol/L",
    male: "11–30", female: "9–27", critical_low: "—", critical_high: "—",
    conv: "µg/dL: ×5.6 (11–30 µmol/L ≈ 60–170 µg/dL)",
    low: "Iron deficiency, inflammation (sequestration)",
    high: "Iron overload, hemolysis, recent iron infusion",
    note: "Diurnal + variable — never interpret alone; use with TIBC (transferrin sat).",
    numeric: { lo: 11, hi: 30 } },
  { parameter: "Transferrin Saturation", aliases: ["TSAT"], category: "iron", unit: "%",
    male: "20–45", female: "15–40", critical_low: "—", critical_high: ">50 (hemochromatosis screen)",
    low: "Iron deficiency (<15% diagnostic even with normal ferritin during inflammation)",
    high: "Hemochromatosis (>45–50% → HFE gene test), iron overload, hemolysis",
    note: "Best single screen for hemochromatosis: TSAT >45% + ↑ferritin → HFE testing.",
    numeric: { lo: 20, hi: 45 } },
  { parameter: "Vitamin B12", aliases: ["Cobalamin"], category: "iron", unit: "pmol/L",
    male: "140–700", female: "140–700", critical_low: "—", critical_high: "—",
    conv: "ng/L ≈ same scale (140–700 ng/L)",
    low: "Pernicious anemia, vegan diet, metformin, PPIs, post-gastrectomy, malabsorption",
    high: "Supplementation, liver disease, myeloproliferative (binding proteins)",
    note: "Borderline → check MMA/homocysteine. Treat before folate repletion (neuro risk). Neuro signs need IM replacement.",
    numeric: { lo: 140, hi: 700 } },
  { parameter: "Folate (serum)", aliases: ["Folic acid"], category: "iron", unit: "nmol/L",
    male: "7–45", female: "7–45", critical_low: "—", critical_high: "—",
    low: "Poor diet, alcohol, malabsorption (celiac), drugs (MTX, TMP, phenytoin), pregnancy demand",
    high: "Supplementation",
    note: "Red cell folate better reflects body stores. Check B12 first — treating folate alone can worsen B12 neuropathy.",
    numeric: { lo: 7, hi: 45 } },

  // ─── Blood gas & acid-base ─────────────────────────────────
  { parameter: "pH (arterial)", aliases: ["ABG pH"], category: "gas", unit: "",
    male: "7.35–7.45", female: "7.35–7.45", critical_low: "<7.2", critical_high: ">7.6",
    low: "Acidemia: respiratory acidosis (↑PaCO2) or metabolic acidosis (↓HCO3)",
    high: "Alkalemia: respiratory alkalosis (↓PaCO2) or metabolic alkalosis (↑HCO3)",
    note: "Read in order: pH → PaCO2 → HCO3 → compensation (Winter's formula: expected PaCO2 = 1.5×HCO3 + 8 ±2).",
    numeric: { lo: 7.35, hi: 7.45 } },
  { parameter: "PaCO2", aliases: ["pCO2"], category: "gas", unit: "kPa",
    male: "4.7–6.0", female: "4.7–6.0", critical_low: "—", critical_high: ">8.0 (respiratory failure T2)",
    conv: "mmHg: ×7.5 (4.7–6.0 kPa ≈ 35–45 mmHg)",
    low: "Hyperventilation (anxiety, PE, sepsis, asthma early), compensation for metabolic acidosis",
    high: "Hypoventilation (COPD, opioids, fatigue), compensation for metabolic alkalosis",
    note: "Type 2 respiratory failure = PaCO2 >6.5 with hypoxemia.",
    numeric: { lo: 4.7, hi: 6 } },
  { parameter: "PaO2", aliases: ["pO2"], category: "gas", unit: "kPa",
    male: "10.6–13.3 (on air)", female: "same", critical_low: "<8.0 (type 1 resp failure)", critical_high: "—",
    conv: "mmHg: ×7.5 (10.6–13.3 ≈ 80–100 mmHg)",
    low: "Hypoxemia: V/Q mismatch, shunt, hypoventilation, diffusion limitation, low FiO2 (altitude)",
    high: "Supplemental oxygen (over-oxygenation harms in COPD/STEMI/stroke)",
    note: "Interpret against FiO2 — P/F ratio (PaO2/FiO2) <40 kPa ≈ severe ARDS.",
    numeric: { lo: 10.6, hi: 13.3 } },
  { parameter: "SpO2 (target)", aliases: ["Oxygen saturation"], category: "gas", unit: "%",
    male: "94–98 (88–92 if CO2 retainer risk)", female: "same", critical_low: "<90", critical_high: "—",
    low: "Hypoxemia causes as PaO2; false lows: poor perfusion, nail polish, motion",
    high: "—",
    note: "Target 94–98%; 88–92% in COPD/CO2 retention risk pending ABG.",
    numeric: { lo: 94, hi: 98 } },
  { parameter: "Base Excess", aliases: ["BE"], category: "gas", unit: "mmol/L",
    male: "−2 to +2", female: "−2 to +2", critical_low: "—", critical_high: "—",
    low: "Metabolic acidosis (negative BE)",
    high: "Metabolic alkalosis (positive BE)",
    note: "Isolates the metabolic component independent of CO2.",
    numeric: { lo: -2, hi: 2 } },

  // ─── Urine & CSF ───────────────────────────────────────────
  { parameter: "Urine Specific Gravity", aliases: ["SG", "USG"], category: "urine", unit: "",
    male: "1.005–1.030", female: "1.005–1.030", critical_low: "—", critical_high: "—",
    low: "Diabetes insipidus (dilute), diuretics, excessive fluid intake, renal tubular damage",
    high: "Dehydration, glycosuria, SIADH, contrast media",
    note: "Isosthenuria (fixed ~1.010) = loss of concentrating ability — renal parenchymal disease.",
    numeric: { lo: 1.005, hi: 1.03 } },
  { parameter: "Urinalysis — Protein", aliases: ["Proteinuria dipstick"], category: "urine", unit: "",
    male: "Negative–trace", female: "Negative–trace", critical_low: "—", critical_high: "—",
    low: "—",
    high: "UTI, exercise/fever (transient), glomerulonephritis, nephrotic syndrome (≥3+ → ACR/PCR), orthostatic",
    note: "Quantify persistent proteinuria with ACR (<3 mg/mmol normal; >30 = macroalbuminuria).",
    numeric: null },
  { parameter: "Urinalysis — Blood", aliases: ["Hematuria dipstick"], category: "urine", unit: "",
    male: "Negative", female: "Negative", critical_low: "—", critical_high: "—",
    low: "—",
    high: "UTI, stones, malignancy (painless hematuria → cystoscope), glomerulonephritis (dysmorphic RBCs), trauma, menstruation",
    note: "Dipstick +ve but no RBCs on microscopy → hemoglobinuria/myoglobinuria (hemolysis/rhabdo).",
    numeric: null },
  { parameter: "Urinalysis — Glucose", aliases: ["Glycosuria"], category: "urine", unit: "",
    male: "Negative", female: "Negative", critical_low: "—", critical_high: "—",
    low: "—",
    high: "Diabetes (glucose >10 renal threshold), SGLT2 inhibitors (expected!), pregnancy (low threshold), Fanconi",
    note: "SGLT2i users normally glycosuric — don't use dipstick for control monitoring.",
    numeric: null },
  { parameter: "Urinalysis — Leukocytes/Nitrites", aliases: ["WBC esterase", "Nitrites"], category: "urine", unit: "",
    male: "Negative", female: "Negative", critical_low: "—", critical_high: "—",
    low: "—",
    high: "UTI (nitrites = gram-negative bacteria convert nitrate; leukocytes = pyuria)",
    note: "Nitrite-negative doesn't exclude UTI (some organisms don't produce nitrate). Sterile pyuria → think TB, STI, interstitial nephritis.",
    numeric: null },
  { parameter: "Urinalysis — Ketones", aliases: ["Ketonuria"], category: "urine", unit: "",
    male: "Negative", female: "Negative", critical_low: "—", critical_high: "—",
    low: "—",
    high: "DKA, starvation/fasting, alcohol, vomiting, ketogenic diet, pregnancy (mild)",
    note: "DKA: glucose + ketones + acidosis — serum β-hydroxybutyrate preferred over urine.",
    numeric: null },
  { parameter: "Urine ACR", aliases: ["Albumin:creatinine ratio"], category: "urine", unit: "mg/mmol",
    male: "<2.5", female: "<3.5", critical_low: "—", critical_high: ">30 (macroalbuminuria)",
    conv: "mg/g: ×8.84",
    low: "—",
    high: "Diabetic nephropathy, hypertension, glomerular disease, transient (UTI, exercise, fever — repeat)",
    note: "A1 <3, A2 3–30, A3 >30 — persistent elevation needed for CKD staging.",
    numeric: { lo: 0, hi: 2.5 } },
  { parameter: "CSF — Cell Count", aliases: ["CSF WCC"], category: "urine", unit: "cells/µL",
    male: "0–5 (lymphocytes)", female: "0–5", critical_low: "—", critical_high: ">1000 suggests bacterial",
    low: "—",
    high: "Bacterial meningitis (neutrophils, 100s–1000s), viral (lymphocytes, 10s–100s), TB/fungal (lymphocytes), SAH (RBCs)",
    note: "Patterns: bacterial = ↑PMN + ↑protein + ↓glucose; viral = ↑lymphocytes + mild ↑protein + normal glucose.",
    numeric: { lo: 0, hi: 5 } },
  { parameter: "CSF — Protein", aliases: [], category: "urine", unit: "g/L",
    male: "0.15–0.45", female: "0.15–0.45", critical_low: "—", critical_high: ">1.0",
    low: "—",
    high: "Bacterial/TB/fungal meningitis (high), viral (mild), Guillain-Barré (very high albuminocytologic dissociation), SAH",
    note: "GBS classic: high protein with normal cell count.",
    numeric: { lo: 0.15, hi: 0.45 } },
  { parameter: "CSF — Glucose", aliases: [], category: "urine", unit: "mmol/L",
    male: "2.2–4.4 (≥60% of serum)", female: "same", critical_low: "—", critical_high: "—",
    low: "Bacterial/TB/fungal meningitis (<40–60% of serum — always pair with simultaneous serum glucose)",
    high: "—",
    note: "CSF:serum ratio <0.4 = bacterial until proven otherwise.",
    numeric: { lo: 2.2, hi: 4.4 } },
  { parameter: "CSF — Opening Pressure", aliases: ["OP"], category: "urine", unit: "cmH₂O",
    male: "10–20", female: "10–20", critical_low: "—", critical_high: ">25",
    low: "CSF leak, dehydration",
    high: "Idiopathic intracranial hypertension (BMI-related), meningitis, mass lesions, SAH",
    note: "Measure in lateral decubitus, legs extended. IIH therapeutic tap aims to close ~10–15.",
    numeric: { lo: 10, hi: 20 } },

  // ─── Tumor markers ─────────────────────────────────────────
  { parameter: "PSA", aliases: ["Prostate specific antigen"], category: "tumor", unit: "µg/L",
    male: "<4 (age-adjusted: <3 at 50–59, <5 at 70+)", female: "—", critical_low: "—", critical_high: ">10 (higher cancer likelihood)",
    low: "—",
    high: "Prostate cancer, BPH, prostatitis, urinary retention, ejaculation/cycling/DRE (transient), post-biopsy",
    note: "Screening test with shared decision-making; rising velocity matters more than single value. 4–10 = grey zone (use %free PSA).",
    numeric: null },
  { parameter: "CA-125", aliases: [], category: "tumor", unit: "U/mL",
    male: "<35", female: "<35", critical_low: "—", critical_high: ">200",
    low: "—",
    high: "Ovarian cancer, endometriosis, PID, menstruation, ascites, liver disease, heart failure — very non-specific",
    note: "Better for monitoring known ovarian cancer than screening; RMI score combines CA-125 + USS + menopause status.",
    numeric: { lo: 0, hi: 35 } },
  { parameter: "CEA", aliases: ["Carcinoembryonic antigen"], category: "tumor", unit: "µg/L",
    male: "<3 (smokers <5)", female: "same", critical_low: "—", critical_high: ">10",
    low: "—",
    high: "Colorectal cancer (monitoring/recurrence), other GI cancers, lung, smoking, inflammation, liver disease",
    note: "Not a screening test — used for CRC recurrence surveillance and treatment response.",
    numeric: { lo: 0, hi: 3 } },
  { parameter: "AFP", aliases: ["Alpha-fetoprotein"], category: "tumor", unit: "µg/L",
    male: "<10", female: "<10 (non-pregnant)", critical_low: "—", critical_high: ">400 strongly suggests HCC/germ cell tumor",
    low: "—",
    high: "Hepatocellular carcinoma, germ cell tumors (testicular/ovarian), pregnancy (normal — but screens neural tube defects), hepatitis/cirrhosis",
    note: "HCC surveillance marker in cirrhosis; pregnancy levels interpreted by gestational week (MSAFP).",
    numeric: { lo: 0, hi: 10 } },
  { parameter: "CA 19-9", aliases: [], category: "tumor", unit: "U/mL",
    male: "<37", female: "<37", critical_low: "—", critical_high: ">1000 (advanced disease)",
    low: "—",
    high: "Pancreatic cancer, cholangiocarcinoma, cholestasis (false high — normalize bilirubin first), pancreatitis, smokers",
    note: "Lewis-antigen negative patients (~10%) produce none. Monitoring > diagnosis.",
    numeric: { lo: 0, hi: 37 } },
  { parameter: "LDH (tumor context)", aliases: [], category: "tumor", unit: "U/L",
    male: "140–280", female: "140–280", critical_low: "—", critical_high: "—",
    low: "—",
    high: "Lymphoma burden/prognosis (IPI), germ cell tumor staging, melanoma, tumor lysis",
    note: "Prognostic marker in lymphoma (international prognostic index component).",
    numeric: { lo: 140, hi: 280 } },

  // ─── Therapeutic drug levels ──────────────────────────────
  { parameter: "Digoxin Level", aliases: [], category: "therapeutic", unit: "nmol/L",
    male: "1.0–2.6 therapeutic (aim 0.6–1.2 for HF)", female: "same", critical_low: "—", critical_high: ">2.6 (toxicity risk; >3.9 dangerous)",
    conv: "ng/mL: ÷1.28 (1.0–2.6 nmol/L ≈ 0.8–2.0 ng/mL)",
    low: "Subtherapeutic",
    high: "Toxicity: nausea/anorexia, xanthopsia (yellow vision), any arrhythmia (esp. PAT with block), bradycardia — worsened by ↓K+/↓Mg, renal failure",
    note: "Sample ≥6h post dose (distribution). Toxicity can occur at 'therapeutic' levels with low K+ — treat the patient not the level.",
    numeric: { lo: 1, hi: 2.6 } },
  { parameter: "Lithium", aliases: ["Li"], category: "therapeutic", unit: "mmol/L",
    male: "0.6–0.8 (up to 1.0 mania)", female: "same", critical_low: "—", critical_high: ">1.5 (toxicity)",
    low: "Subtherapeutic",
    high: "Toxicity: coarse tremor, vomiting, confusion → seizures/coma. Precipitated by NSAIDs, ACEi, diuretics, dehydration",
    note: "12h post-dose level. Monitor TFTs + renal q6mo (hypothyroidism, diabetes insipidus). Chronic toxicity may need dialysis.",
    numeric: { lo: 0.6, hi: 1 } },
  { parameter: "Phenytoin", aliases: [], category: "therapeutic", unit: "µmol/L",
    male: "40–80", female: "40–80", critical_low: "—", critical_high: ">80",
    conv: "µg/mL: ÷4 (40–80 µmol/L ≈ 10–20 µg/mL)",
    low: "Subtherapeutic (seizures)",
    high: "Toxicity: nystagmus → ataxia → diplopia → encephalopathy",
    note: "Non-linear kinetics — small dose change, big level change. Correct for low albumin (hypoalbuminemia → high free fraction).",
    numeric: { lo: 40, hi: 80 } },
  { parameter: "Valproate", aliases: ["VPA"], category: "therapeutic", unit: "µmol/L",
    male: "350–700", female: "350–700", critical_low: "—", critical_high: ">700",
    conv: "µg/mL: ÷6.93 (≈50–100 µg/mL)",
    low: "Subtherapeutic",
    high: "Toxicity: sedation, hyperammonemic encephalopathy (check ammonia!), thrombocytopenia",
    note: "Trough level. Free fraction rises in hypoalbuminemia/pregnancy.",
    numeric: { lo: 350, hi: 700 } },
  { parameter: "Carbamazepine", aliases: ["CBZ"], category: "therapeutic", unit: "µmol/L",
    male: "17–50", female: "17–50", critical_low: "—", critical_high: ">50",
    conv: "µg/mL: ÷4.2 (≈4–12 µg/mL)",
    low: "Subtherapeutic",
    high: "Toxicity: diplopia, ataxia, hyponatremia (SIADH)",
    note: "Trough. Autoinduction — levels fall weeks 1–4; recheck after changes. HLA-B*1502 (SJS risk) screening in at-risk ethnicities.",
    numeric: { lo: 17, hi: 50 } },
  { parameter: "Vancomycin (trough)", aliases: ["Vanc level"], category: "therapeutic", unit: "mg/L",
    male: "10–20 (severe MRSA 15–20)", female: "same", critical_low: "—", critical_high: ">20 (nephrotoxicity risk)",
    low: "Subtherapeutic — resistance risk",
    high: "Nephrotoxicity, ototoxicity",
    note: "Trough just before 4th dose (or AUC-guided dosing where available). Dose by renal function.",
    numeric: { lo: 10, hi: 20 } },
  { parameter: "Theophylline", aliases: [], category: "therapeutic", unit: "µmol/L",
    male: "55–110", female: "55–110", critical_low: "—", critical_high: ">110",
    conv: "µg/mL: ÷5.5 (55–110 µmol/L ≈ 10–20 µg/mL)",
    low: "Subtherapeutic",
    high: "Toxicity: arrhythmias, seizures (can occur without warning signs)",
    note: "Narrow window; levels ↑ by ciprofloxacin, macrolides, smoking cessation.",
    numeric: { lo: 55, hi: 110 } },
];

/** Category lookup helper. */
export const CATEGORY_MAP = Object.fromEntries(LAB_CATEGORIES.map((c) => [c.id, c]));

/**
 * Parse a display range like "13.0–17.0", "<5", ">90", "4.5–11.0" into
 * {lo, hi} numbers (null bound = unbounded). Returns null if unparseable.
 */
export function parseRange(str) {
  if (!str) return null;
  const s = String(str).replace(/[–—−]/g, "-").trim();
  let m = s.match(/^([<>≤≥]=?)\s*([\d.]+)/);
  if (m) {
    const v = parseFloat(m[2]);
    if (Number.isNaN(v)) return null;
    if (m[1][0] === "<" || m[1] === "≤") return { lo: null, hi: v };
    return { lo: v, hi: null };
  }
  m = s.match(/^(-?[\d.]+)\s*-\s*([\d.]+)/);
  if (m) {
    const lo = parseFloat(m[1]);
    const hi = parseFloat(m[2]);
    if (!Number.isNaN(lo) && !Number.isNaN(hi) && hi > lo) return { lo, hi };
  }
  return null;
}

/**
 * Check a patient value against a lab's range.
 * sex: "male" | "female" | null (uses male/female range, or generic numeric).
 * Returns { verdict, range, inRange } or null if value/range unparseable.
 */
export function checkValue(lab, rawValue, sex) {
  const v = parseFloat(String(rawValue).trim());
  if (Number.isNaN(v)) return null;
  const rangeStr = sex === "female" && lab.female && lab.female !== "same" && lab.female !== "—"
    ? lab.female
    : lab.male;
  // Sex-specific display range parses first; `numeric` is only a fallback
  // for labs whose display string isn't a simple range (e.g. "<0.5").
  const r = parseRange(rangeStr) || lab.numeric || parseRange(lab.male);
  if (!r) return null;
  // Only absolute thresholds are auto-checkable — relative ones like
  // ">3× ULN" need the lab's own ULN and are left as display badges.
  const absolute = (s) =>
    s && !/uln/i.test(String(s)) && !/\d\s*[x×]/.test(String(s)) ? s : null;
  const loM = absolute(lab.critical_low)?.match(/^[<≤]\s*([\d.]+)/);
  const hiM = absolute(lab.critical_high)?.match(/^[>≥]\s*([\d.]+)/);
  const critLow = loM ? parseFloat(loM[1]) : null;
  const critHigh = hiM ? parseFloat(hiM[1]) : null;
  let verdict = "in-range";
  if (critLow != null && v <= critLow) verdict = "critical-low";
  else if (critHigh != null && v >= critHigh) verdict = "critical-high";
  else if (r.lo != null && v < r.lo) verdict = "low";
  else if (r.hi != null && v > r.hi) verdict = "high";
  return { verdict, value: v, range: r, sex: sex || "any" };
}
