// All PdfReader inline styles in one parameterized factory — extracted from
// PdfReader.jsx so the reader component stays navigable. Pure: same inputs,
// same styles; no React or app state touched here.
export function buildStyles({ T, isMobile, theme, scrollMode, showThumbs, tool, circleMode, chatOpen, chatExpanded, dockMode, dockW, userZoomed, pinchActive, fullscreen, showSearch, annotatePopOpen }) {
  return {
    container: {
      height: "100%",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
      background: T.bg,
      borderRadius: "10px",
      position: "relative",
      ...(fullscreen && {
        position: "fixed",
        inset: 0,
        zIndex: 9999,
        borderRadius: 0,
        height: "100dvh",
        paddingTop: "env(safe-area-inset-top)",
        paddingBottom: "env(safe-area-inset-bottom)",
        paddingLeft: "env(safe-area-inset-left)",
        paddingRight: "env(safe-area-inset-right)",
      }),
    },
    toolbar: {
      background: T.toolbar,
      borderBottom: `1px solid ${T.border}`,
      display: "flex",
      flexDirection: "column",
      flexShrink: 0,
    },
    toolbarRow: {
      display: "flex",
      alignItems: "center",
      gap: isMobile ? "2px" : "6px",
      padding: isMobile ? "6px max(8px, env(safe-area-inset-left))" : "8px max(14px, env(safe-area-inset-left))",
      paddingRight: isMobile ? "max(8px, env(safe-area-inset-right))" : "max(14px, env(safe-area-inset-right))",
      width: "100%",
      boxSizing: "border-box",
      overflow: isMobile ? "hidden" : "visible",
      overflowX: isMobile ? "hidden" : "auto",
    },
    docTitle: {
      fontFamily: "Georgia, serif",
      fontSize: isMobile ? 12 : 15,
      fontWeight: 600,
      color: T.text,
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
      flex: 1,
      minWidth: 0,
    },
    iconBtn: {
      width: isMobile ? "36px" : "40px",
      height: isMobile ? "36px" : "40px",
      borderRadius: "8px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: T.muted,
      border: "none",
      background: "none",
      cursor: "pointer",
      flexShrink: 0,
    },
    sep: { width: "1px", height: "24px", background: T.border, margin: isMobile ? "0 1px" : "0 2px", flexShrink: 0 },
    pageIndicator: {
      fontFamily: "ui-monospace, monospace",
      fontSize: isMobile ? 12 : 14,
      color: T.muted,
      whiteSpace: "nowrap",
      flexShrink: 0,
    },
    pageInput: {
      width: isMobile ? "32px" : "40px",
      textAlign: "center",
      border: `1px solid ${T.border}`,
      borderRadius: "5px",
      padding: isMobile ? "3px 2px" : "4px 2px",
      fontFamily: "ui-monospace, monospace",
      fontSize: isMobile ? 12 : 14,
      background: T.inputBg,
      color: T.text,
      flexShrink: 0,
    },
    zoomLabel: {
      fontFamily: "ui-monospace, monospace",
      fontSize: isMobile ? 11 : 13,
      color: T.muted,
      minWidth: isMobile ? "38px" : "44px",
      textAlign: "center",
      flexShrink: 0,
    },
    spacer: { flex: 1 },
    workspace: { flex: 1, display: "flex", overflow: "hidden", minHeight: 0 },
    thumbsAside: {
      width: showThumbs ? (isMobile ? "0" : "132px") : "0",
      overflow: "hidden",
      background: T.thumbBg,
      borderRight: `1px solid ${T.border}`,
      transition: "width 0.18s ease",
      flexShrink: 0,
    },
    thumbRail: {
      width: "132px",
      height: "100%",
      overflowY: "auto",
      padding: "0 8px 10px",
      display: "flex",
      flexDirection: "column",
      gap: "10px",
    },
    pageFilterRow: {
      display: "flex",
      gap: 4,
      padding: "8px 8px 6px",
      flexWrap: "wrap",
      flexShrink: 0,
    },
    pageFilterTab: {
      fontSize: 10.5,
      fontWeight: 600,
      padding: "3px 8px",
      borderRadius: 999,
      border: `1px solid ${T.border}`,
      background: "none",
      color: T.muted,
      cursor: "pointer",
      whiteSpace: "nowrap",
    },
    thumb: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "4px",
      padding: "5px",
      borderRadius: "6px",
      border: "1.5px solid transparent",
      background: "none",
      cursor: "pointer",
      position: "relative",
    },
    thumbLabel: {
      fontFamily: "ui-monospace, monospace",
      fontSize: 10,
      color: T.muted,
    },
    viewer: scrollMode === "single" || scrollMode === "book" ? {
      flex: 1,
      overflow: "auto",
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      padding: isMobile ? "8px 4px 40px" : "24px 32px 40px",
      position: "relative",
      // "auto" when zoomed so one finger pans natively; "none" at fit so swipe
      // gestures are ours. Pinch is always handled by the non-passive listener.
      touchAction: userZoomed ? "auto" : "none",
    } : scrollMode === "vertical" ? {
      flex: 1,
      overflowY: "auto",
      overflowX: "auto",
      position: "relative",
      // "auto" — horizontal pan is only possible when content overflows
      // (wider-than-median pages at fit, zoomed pages), and native pinch is
      // blocked by user-scalable=no + our non-passive pinch handlers.
      touchAction: "auto",
    } : {
      flex: 1,
      overflowX: "auto",
      overflowY: "auto",
      position: "relative",
      scrollSnapType: pinchActive ? "none" : "x mandatory",
      touchAction: "auto",
    },
    pageShadow: {
      position: "relative",
      background: (theme === "dark" || theme === "dim") ? "#2a2a3e" : "white",
      boxShadow: `0 2px 10px ${T.shadow}, 0 14px 34px ${T.shadow}`,
      lineHeight: 0,
      flexShrink: 0,
      // Centers the page when it fits; aligns start when it overflows so the
      // left edge stays reachable via scroll (justify-content:center would clip it)
      margin: "0 auto",
    },
    continuousPageItem: {
      position: "relative",
      background: (theme === "dark" || theme === "dim") ? "#2a2a3e" : "white",
      boxShadow: `0 2px 10px ${T.shadow}, 0 14px 34px ${T.shadow}`,
      lineHeight: 0,
      flexShrink: 0,
      // Size to the canvas so a zoomed page overflows (and pans) instead of
      // being clamped to the column width
      width: "max-content",
      scrollSnapAlign: scrollMode === "horizontal" ? "center" : "unset",
    },
    pageLabel: {
      position: "absolute",
      bottom: 4,
      right: 8,
      fontFamily: "ui-monospace, monospace",
      fontSize: 10,
      color: T.muted,
      background: theme === "dark" ? "rgba(0,0,0,0.5)" : "rgba(255,255,255,0.7)",
      borderRadius: 4,
      padding: "1px 5px",
      pointerEvents: "none",
    },
    scrollModeToggle: {
      display: "flex",
      gap: 2,
      alignItems: "center",
      flexShrink: 0,
    },
    // Two facing pages sharing a row in book mode
    spreadRow: {
      display: "flex",
      flexDirection: "row",
      alignItems: "stretch",
      gap: 10,
      flexShrink: 0,
      margin: "0 auto",
      lineHeight: 0,
    },
    scrollModeBtn: {
      width: isMobile ? 26 : 30,
      height: isMobile ? 26 : 30,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      border: `1px solid ${T.border}`,
      borderRadius: 6,
      background: "none",
      color: T.muted,
      cursor: "pointer",
      flexShrink: 0,
    },
    loadingOverlay: {
      position: "absolute",
      inset: 0,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: T.bg,
      fontSize: 13,
      color: T.muted,
      gap: 8,
    },
    spinner: {
      width: 14,
      height: 14,
      border: `2px solid ${T.border}`,
      borderTopColor: T.accent,
      borderRadius: "50%",
      animation: "spin 0.7s linear infinite",
    },
    // Search panel
    searchWrap: { position: "relative" },
    searchPanel: {
      position: isMobile ? "fixed" : "absolute",
      top: isMobile ? 96 : "44px",
      left: isMobile ? 8 : "auto",
      right: isMobile ? 8 : 0,
      width: isMobile ? "auto" : "280px",
      maxHeight: "320px",
      background: T.toolbar,
      border: `1px solid ${T.border}`,
      borderRadius: "10px",
      boxShadow: `0 10px 30px ${T.shadow}`,
      display: showSearch ? "flex" : "none",
      flexDirection: "column",
      overflow: "hidden",
      zIndex: 200,
    },
    searchRow: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      padding: "8px 10px",
      borderBottom: `1px solid ${T.border}`,
    },
    searchInput: {
      flex: 1,
      border: "none",
      outline: "none",
      fontSize: 13,
      background: "transparent",
      color: T.text,
    },
    searchCount: {
      fontFamily: "ui-monospace, monospace",
      fontSize: 10.5,
      color: T.muted,
      whiteSpace: "nowrap",
    },
    searchResults: { overflowY: "auto", maxHeight: "270px" },
    searchItem: {
      display: "block",
      width: "100%",
      textAlign: "left",
      padding: "8px 12px",
      borderBottom: `1px solid ${T.border}`,
      background: "none",
      border: "none",
      cursor: "pointer",
    },
    matchNavBtn: {
      background: "none",
      border: "none",
      color: T.muted,
      cursor: "pointer",
      fontSize: 15,
      padding: "2px 6px",
      borderRadius: 4,
      lineHeight: 1,
    },
    searchPage: {
      display: "inline-block",
      fontFamily: "ui-monospace, monospace",
      fontSize: 10,
      color: T.accent,
      marginBottom: 2,
    },
    searchSnip: {
      display: "block",
      fontSize: 12.5,
      lineHeight: 1.4,
      color: T.muted,
    },
    askBtn: {
      display: "inline-block",
      marginTop: 4,
      fontSize: 10.5,
      fontWeight: 600,
      color: T.accent,
      background: T.hover,
      border: "none",
      borderRadius: "4px",
      padding: "2px 8px",
      cursor: "pointer",
    },
    // Lasso / highlight overlay
    lassoOverlay: {
      maxWidth: "none",
      position: "absolute",
      inset: 0,
      width: "100%",
      height: "100%",
      pointerEvents: tool !== "none" ? "auto" : "none",
      touchAction: "none",
      cursor: tool === "highlight" || tool === "pen" ? "crosshair" : tool === "erase" ? "pointer" : tool === "circle" ? "crosshair" : "default",
    },
    lassoPath: {
      fill: "rgba(194,59,59,0.12)",
      stroke: T.accent,
      strokeWidth: 3,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    },
    // Circle bubble
    circleBubble: {
      position: "absolute",
      bottom: 16,
      right: 16,
      width: 54,
      height: 54,
      borderRadius: "50%",
      background: circleMode ? T.text : T.accent,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      boxShadow: `0 6px 18px ${T.shadow}`,
      zIndex: 30,
      border: "none",
      cursor: "pointer",
      transition: "transform 0.12s ease, background 0.15s ease",
    },
    // Chat popup — mobile bottom sheet / desktop side panel
    chatBackdrop: {
      position: "fixed",
      inset: 0,
      background: "rgba(0,0,0,0.45)",
      zIndex: 90,
      touchAction: "manipulation",
    },
    chatPopup: isMobile ? {
      position: "fixed",
      bottom: 0,
      left: 0,
      right: 0,
      height: chatExpanded ? "92dvh" : "72dvh",
      transition: "height 0.22s ease",
      background: T.toolbar,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      boxShadow: `0 -4px 24px ${T.shadow}`,
      zIndex: 100,
      display: "flex",
      flexDirection: "column",
      animation: "slideUp 0.2s ease",
      touchAction: "auto",
      WebkitOverflowScrolling: "touch",
    } : dockMode ? {
      // Docked right-hand panel inside the workspace row — pushes the
      // document aside instead of floating over it (NotebookLM-style)
      position: "relative",
      width: dockW,
      flexShrink: 0,
      minHeight: 0,
      background: T.toolbar,
      borderLeft: `1px solid ${T.border}`,
      display: "flex",
      flexDirection: "column",
      touchAction: "auto",
    } : {
      // Portrait tablets: not enough width to dock — floating card
      position: "fixed",
      top: "50%",
      right: 16,
      transform: "translate3d(0, -50%, 0)",
      width: 380,
      maxWidth: "calc(100vw - 32px)",
      maxHeight: "calc(100dvh - 100px)",
      background: T.toolbar,
      border: `1px solid ${T.border}`,
      borderRadius: 12,
      boxShadow: `0 12px 36px ${T.shadow}`,
      zIndex: 100,
      display: "flex",
      flexDirection: "column",
      touchAction: "auto",
    },
    sheetHandle: {
      width: 40,
      height: 4,
      background: T.border,
      borderRadius: 2,
      margin: "8px auto 4px",
      flexShrink: 0,
      // Generous touch zone — the visual bar is tiny but the tap area isn't
      padding: "6px 0",
      backgroundClip: "content-box",
      cursor: "grab",
      touchAction: "none",
    },
    chatHead: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: isMobile ? "6px 14px 8px" : "10px 14px",
      borderBottom: `1px solid ${T.border}`,
      flexShrink: 0,
    },
    chatTag: {
      fontFamily: "ui-monospace, monospace",
      fontSize: isMobile ? 11 : 12,
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      color: T.accent,
      fontWeight: 600,
    },
    chatClose: {
      color: T.muted,
      fontSize: 13,
      background: "none",
      border: "none",
      cursor: "pointer",
    },
    chatThread: {
      overflowY: "auto",
      WebkitOverflowScrolling: "touch",
      touchAction: "pan-y",
      padding: isMobile ? 12 : 14,
      display: "flex",
      flexDirection: "column",
      gap: 10,
      flex: 1,
      minHeight: 60,
    },
    msgUser: {
      alignSelf: "flex-end",
      maxWidth: "85%",
      background: T.accent,
      color: "white",
      borderRadius: "10px 10px 2px 10px",
      padding: "8px 12px",
      fontSize: isMobile ? 13 : 14,
      lineHeight: 1.5,
      animation: "sc-msg-in 0.25s ease-out",
    },
    msgAssistant: {
      alignSelf: "stretch",
      maxWidth: "100%",
      color: T.text,
      fontSize: isMobile ? 13 : 14,
      lineHeight: 1.6,
      animation: "sc-msg-in 0.25s ease-out",
    },
    msgImage: {
      maxWidth: "100%",
      maxHeight: isMobile ? 120 : 100,
      borderRadius: 6,
      border: `1px solid ${T.border}`,
      display: "block",
    },
    msgImageWrap: {
      position: "relative",
      display: "block",
      border: "none",
      background: "none",
      padding: 0,
      marginBottom: 6,
      cursor: "pointer",
      maxWidth: "100%",
    },
    imgPageBadge: {
      position: "absolute",
      right: 6,
      bottom: 6,
      fontSize: 10,
      fontWeight: 700,
      background: "rgba(0,0,0,0.68)",
      color: "#fff",
      borderRadius: 999,
      padding: "2px 7px",
      pointerEvents: "none",
    },
    aiMark: {
      fontSize: 9.5,
      fontWeight: 700,
      letterSpacing: "0.06em",
      textTransform: "uppercase",
      color: T.accent,
      marginBottom: 2,
      opacity: 0.85,
    },
    msgActions: {
      display: "flex",
      gap: 4,
      marginTop: 7,
      flexWrap: "wrap",
    },
    msgActionBtn: {
      fontSize: 11,
      fontWeight: 600,
      color: T.muted,
      background: "none",
      border: `1px solid ${T.border}`,
      borderRadius: 999,
      padding: "3px 9px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    srcRow: {
      display: "flex",
      alignItems: "center",
      flexWrap: "wrap",
      gap: 5,
      marginTop: 7,
      paddingTop: 6,
      borderTop: `0.5px solid ${T.border}`,
    },
    srcLabel: { fontSize: 10.5, color: T.muted, fontWeight: 600 },
    srcChip: {
      fontSize: 10.5,
      fontWeight: 700,
      color: T.accent,
      background: "none",
      border: `1px solid ${T.accent}55`,
      borderRadius: 999,
      padding: "1px 8px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    streamCursor: {
      display: "inline-block",
      width: 7,
      height: 13,
      marginLeft: 2,
      background: "currentColor",
      opacity: 0.7,
      verticalAlign: "text-bottom",
      animation: "sc-cursor-blink 0.9s steps(1) infinite",
    },
    jumpLatest: {
      position: "absolute",
      bottom: 118,
      left: "50%",
      transform: "translateX(-50%)",
      fontSize: 11.5,
      fontWeight: 700,
      color: "#fff",
      background: T.accent,
      border: "none",
      borderRadius: 999,
      padding: "6px 14px",
      cursor: "pointer",
      boxShadow: `0 4px 12px ${T.shadow}`,
      zIndex: 5,
      fontFamily: "inherit",
      animation: "sc-fade-in-up 0.2s ease forwards",
    },
    emptyWrap: {
      textAlign: "center",
      padding: "26px 16px",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: 5,
    },
    emptyGlyph: { fontSize: 26 },
    emptyTitle: { fontSize: 14.5, fontWeight: 700, color: T.text },
    emptyText: { fontSize: 12.5, color: T.muted, lineHeight: 1.6, maxWidth: 300 },
    creditsChip: {
      fontSize: 11,
      fontWeight: 700,
      padding: "3px 9px",
      borderRadius: 999,
      background: "rgba(250,204,21,0.12)",
      border: "1px solid rgba(250,204,21,0.35)",
      color: "#eab308",
      cursor: "pointer",
      fontFamily: "inherit",
      flexShrink: 0,
    },
    chatMiniBtn: {
      color: T.muted,
      fontSize: 13,
      background: "none",
      border: "none",
      cursor: "pointer",
      padding: "2px 7px",
      borderRadius: 6,
      fontWeight: 700,
      minWidth: 30,
      fontFamily: "inherit",
    },
    msgLoading: {
      alignSelf: "flex-start",
      display: "flex",
      alignItems: "center",
      gap: 7,
      fontSize: isMobile ? 13 : 14,
      color: T.muted,
      background: T.chatBot,
      borderRadius: "10px 10px 10px 2px",
      padding: "8px 12px",
    },
    msgError: {
      alignSelf: "flex-start",
      background: theme === "dark" ? "rgba(233,69,96,0.15)" : "#FFF0F0",
      color: T.accent,
      borderRadius: "10px 10px 10px 2px",
      padding: "7px 11px",
      fontSize: 12.5,
      display: "flex",
      flexDirection: "column",
      gap: 4,
    },
    retryBtn: {
      fontSize: 11,
      fontWeight: 600,
      color: T.accent,
      background: "none",
      border: `1px solid ${T.accent}`,
      borderRadius: 4,
      padding: "2px 8px",
      cursor: "pointer",
      alignSelf: "flex-start",
    },
    chipsRow: {
      display: "flex",
      gap: 6,
      padding: isMobile ? "8px 12px" : "8px 14px",
      // Small screens: one scrollable row (scrollbar hidden via .sc-chips-row)
      // so 4+ chips never wrap into a tall stack; larger screens keep wrapping.
      flexWrap: isMobile ? "nowrap" : "wrap",
      overflowX: isMobile ? "auto" : "visible",
      WebkitOverflowScrolling: "touch",
      scrollbarWidth: "none",
      flexShrink: 0,
    },
    chip: {
      fontSize: isMobile ? 12 : 12.5,
      fontWeight: 500,
      color: T.text,
      background: T.chipBg,
      border: `1px solid ${T.border}`,
      borderRadius: "999px",
      padding: isMobile ? "5px 12px" : "4px 11px",
      cursor: "pointer",
      whiteSpace: "nowrap",
    },
    chatInputRow: {
      display: "flex",
      gap: 6,
      padding: isMobile ? "8px 12px 12px" : "8px 14px 10px",
      borderTop: `1px solid ${T.border}`,
      flexShrink: 0,
      touchAction: "auto",
    },
    chatTextarea: {
      flex: 1,
      border: `1px solid ${T.border}`,
      borderRadius: 18,
      padding: isMobile ? "8px 12px" : "7px 10px",
      fontSize: isMobile ? 16 : 13,
      color: T.text,
      background: T.inputBg,
      outline: "none",
      resize: "none",
      minHeight: 36,
      maxHeight: 96,
      fontFamily: "inherit",
      lineHeight: 1.4,
    },
    chatSendBtn: {
      width: 36,
      height: 36,
      borderRadius: "50%",
      background: T.accent,
      color: "white",
      border: "none",
      fontSize: isMobile ? 15 : 14,
      fontWeight: 700,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      alignSelf: "flex-end",
      transition: "opacity 0.15s ease",
    },

    // Color picker popup
    colorPicker: {
      position: "fixed",
      top: "auto",
      left: isMobile ? 8 : "auto",
      right: isMobile ? 8 : "auto",
      display: "flex",
      gap: 6,
      padding: "10px 12px",
      background: T.toolbar,
      border: `1px solid ${T.border}`,
      borderRadius: 10,
      boxShadow: `0 6px 18px ${T.shadow}`,
      zIndex: 200,
      flexWrap: "wrap",
      maxWidth: "calc(100vw - 16px)",
    },
    colorDot: {
      width: 24,
      height: 24,
      borderRadius: "50%",
      border: "2px solid transparent",
      cursor: "pointer",
      flexShrink: 0,
    },
    // Bookmark panel
    bookmarkPanel: {
      position: isMobile ? "fixed" : "absolute",
      top: isMobile ? 96 : 44,
      right: isMobile ? 8 : 0,
      width: isMobile ? 200 : 220,
      maxHeight: "300px",
      background: T.toolbar,
      border: `1px solid ${T.border}`,
      borderRadius: 10,
      boxShadow: `0 6px 18px ${T.shadow}`,
      zIndex: 200,
      overflowY: "auto",
      padding: "8px",
    },
    bookmarkItem: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      padding: "6px 8px",
      borderRadius: 6,
      border: "none",
      background: "none",
      cursor: "pointer",
      color: T.text,
      fontSize: 13,
      width: "100%",
      textAlign: "left",
    },
    bookmarkMiniBtn: {
      background: "none",
      border: "none",
      color: T.muted,
      cursor: "pointer",
      fontSize: 11,
      padding: "2px 4px",
      borderRadius: 4,
      flexShrink: 0,
    },
    bookmarkRename: {
      flex: 1,
      minWidth: 0,
      background: T.inputBg,
      border: `1px solid ${T.border}`,
      borderRadius: 6,
      color: T.text,
      fontSize: 12,
      padding: "4px 6px",
      fontFamily: "inherit",
    },
    selPopBtn: {
      background: "none",
      border: "none",
      color: T.text,
      cursor: "pointer",
      fontSize: 12,
      fontWeight: 600,
      padding: "5px 8px",
      borderRadius: 8,
      fontFamily: "inherit",
      whiteSpace: "nowrap",
      flexShrink: 0,
    },
    selMenuItem: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      width: "100%",
      textAlign: "left",
      background: "none",
      border: "none",
      color: T.text,
      cursor: "pointer",
      fontSize: 12.5,
      fontWeight: 500,
      padding: "7px 8px",
      borderRadius: 7,
      fontFamily: "inherit",
    },
    // Overflow menu (mobile)
    overflowMenu: {
      position: "fixed",
      top: isMobile ? 56 : "auto",
      bottom: isMobile ? "auto" : 60,
      right: 8,
      background: T.toolbar,
      border: `1px solid ${T.border}`,
      borderRadius: 10,
      boxShadow: `0 6px 18px ${T.shadow}`,
      zIndex: 200,
      padding: "4px",
      display: "flex",
      flexDirection: "column",
      gap: 2,
      minWidth: 170,
      maxHeight: "80vh",
      overflowY: "auto",
    },
    overflowItem: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      padding: "8px 10px",
      borderRadius: 6,
      border: "none",
      background: "none",
      cursor: "pointer",
      color: T.text,
      fontSize: 13,
      width: "100%",
      textAlign: "left",
    },
    // ── Annotate popover (mobile) ──────────────────────────────────────────────
    annotatePop: {
      position: "absolute",
      top: 56,
      left: "50%",
      transform: annotatePopOpen ? "translateX(-50%) translateY(0) scale(1)" : "translateX(-50%) translateY(-6px) scale(0.97)",
      width: 264,
      background: T.toolbar,
      border: `1px solid ${T.border}`,
      borderRadius: 16,
      padding: 12,
      boxShadow: `0 16px 40px ${T.shadow}`,
      opacity: annotatePopOpen ? 1 : 0,
      pointerEvents: annotatePopOpen ? "auto" : "none",
      transition: "opacity 0.15s ease, transform 0.15s ease",
      transformOrigin: "top center",
      zIndex: 90,
    },
    toolTabs: {
      display: "flex",
      gap: 6,
      background: T.hover,
      borderRadius: 11,
      padding: 4,
      marginBottom: 10,
    },
    toolTab: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: 4,
      padding: "10px 4px 9px",
      borderRadius: 9,
      cursor: "pointer",
      color: T.muted,
      background: "none",
      border: "none",
      fontFamily: "'JetBrains Mono', ui-monospace, monospace",
      fontSize: 9,
      letterSpacing: "0.02em",
      minHeight: 44,
      justifyContent: "center",
      transition: "all 0.15s ease",
    },
    toolTabActive: {
      background: T.hover,
      color: T.text,
    },
    popRowLabel: {
      fontFamily: "'JetBrains Mono', ui-monospace, monospace",
      fontSize: 9,
      letterSpacing: "0.08em",
      color: T.muted,
      textTransform: "uppercase",
      margin: "8px 0 6px",
    },
    swatchRow: {
      display: "flex",
      gap: 7,
      alignItems: "center",
    },
    swatchDot: {
      width: 22,
      height: 22,
      borderRadius: "50%",
      cursor: "pointer",
      border: "2px solid transparent",
      flexShrink: 0,
      position: "relative",
    },
    swatchDotActive: {
      // active ring rendered via boxShadow
    },
    widthRow: {
      display: "flex",
      gap: 6,
      marginTop: 10,
    },
    widthChip: {
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      height: 30,
      borderRadius: 8,
      background: T.hover,
      border: `1px solid ${T.border}`,
      cursor: "pointer",
      transition: "all 0.15s ease",
    },
    widthChipActive: {
      background: "rgba(79,142,247,0.16)",
      borderColor: "rgba(79,142,247,0.45)",
    },
    clearBtn: {
      width: "100%",
      marginTop: 10,
      padding: 9,
      borderRadius: 9,
      background: "rgba(255,84,112,0.12)",
      border: "1px solid rgba(255,84,112,0.35)",
      color: "#FF5470",
      fontSize: 12,
      fontWeight: 600,
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    // ── Overflow backdrop (mobile) ─────────────────────────────────────────────
    overflowBackdrop: {
      position: "fixed",
      inset: 0,
      background: "rgba(0,0,0,0.55)",
      backdropFilter: "blur(2px)",
      zIndex: 80,
    },
    // ── Theme swatches in overflow ─────────────────────────────────────────────
    themeSwatchRow: {
      display: "flex",
      gap: 6,
      padding: "6px 10px 4px",
    },
    themeSwatch: {
      flex: 1,
      height: 34,
      borderRadius: 8,
      border: `1.5px solid ${T.border}`,
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontFamily: "'JetBrains Mono', ui-monospace, monospace",
      fontSize: 9.5,
      fontWeight: 600,
      transition: "all 0.15s ease",
    },
    // ── Floating nav pill (mobile) ─────────────────────────────────────────────
    navDock: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 20,
      display: "flex",
      justifyContent: "center",
      zIndex: 50,
    },
    navPill: {
      display: "flex",
      alignItems: "center",
      gap: 2,
      background: `${T.toolbar}F0`,
      backdropFilter: "blur(18px)",
      border: `1px solid ${T.border}`,
      borderRadius: 999,
      padding: "6px 8px",
      boxShadow: `0 10px 26px ${T.shadow}`,
    },
    navBtn: {
      width: 30,
      height: 30,
      borderRadius: "50%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: T.muted,
      cursor: "pointer",
      background: "transparent",
      border: "none",
    },
    pageChip: {
      fontFamily: "'JetBrains Mono', ui-monospace, monospace",
      fontSize: 12,
      color: T.text,
      background: T.chipBg,
      borderRadius: 999,
      padding: "6px 12px",
      margin: "0 2px",
      border: "none",
    },
    navDivider: {
      width: 1,
      height: 20,
      background: T.border,
      margin: "0 6px",
    },
    zoomChip: {
      fontFamily: "'JetBrains Mono', ui-monospace, monospace",
      fontSize: 11,
      color: T.muted,
      padding: "0 4px",
      minWidth: 34,
      textAlign: "center",
    },
    // ── AI FAB (mobile) ────────────────────────────────────────────────────────
    aiFab: {
      position: "absolute",
      right: 16,
      bottom: 88,
      width: 52,
      height: 52,
      borderRadius: "50%",
      background: "linear-gradient(145deg, #F5A623, #d98a12)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      boxShadow: "0 8px 22px rgba(245,166,35,0.4), 0 2px 0 rgba(255,255,255,0.15) inset",
      zIndex: 55,
      cursor: "pointer",
      border: "none",
      color: "#1a1200",
      transition: "transform 0.15s ease",
    },
    // Progress bar
    progressBar: {
      height: 3,
      background: T.border,
      flexShrink: 0,
      position: "relative",
    },
    progressFill: {
      height: "100%",
      background: T.accent,
      transition: "width 0.2s ease",
      borderRadius: "0 2px 2px 0",
    },
    // Resume toast
    resumeToast: {
      position: "absolute",
      top: 12,
      left: "50%",
      transform: "translateX(-50%)",
      maxWidth: "calc(100vw - 32px)",
      whiteSpace: "nowrap",
      background: T.toolbar,
      border: `1px solid ${T.border}`,
      borderRadius: 20,
      padding: "4px 14px",
      fontSize: 12,
      color: T.text,
      boxShadow: `0 4px 14px ${T.shadow}`,
      zIndex: 25,
      display: "flex",
      alignItems: "center",
      gap: 8,
    },
    resumeBtn: {
      background: T.accent,
      color: "white",
      border: "none",
      borderRadius: 12,
      padding: "2px 10px",
      fontSize: 11,
      fontWeight: 600,
      cursor: "pointer",
    },
    // ── AI Study Tools styles ────────────────────────────────────────────────
    studyFab: {
      position: "absolute",
      bottom: isMobile ? "calc(16px + env(safe-area-inset-bottom))" : 20,
      // Docked chat occupies the right 400px — shift the FAB left of it
      right: chatOpen && dockMode ? dockW + 16 : isMobile ? 16 : 20,
      width: 48,
      height: 48,
      borderRadius: "50%",
      background: T.accent,
      color: "white",
      border: "none",
      cursor: "pointer",
      boxShadow: `0 4px 16px ${T.shadow}`,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 80,
      transition: "transform 0.15s ease, opacity 0.15s ease",
      touchAction: "manipulation",
      WebkitTapHighlightColor: "transparent",
    },
    studyBackdrop: {
      position: "fixed",
      inset: 0,
      background: "rgba(0,0,0,0.45)",
      zIndex: 90,
      touchAction: "manipulation",
    },
    studyPanel: isMobile ? {
      position: "fixed",
      bottom: 0,
      left: 0,
      right: 0,
      height: "82dvh",
      background: `${T.toolbar}F5`,
      backdropFilter: "blur(20px)",
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      border: `1px solid ${T.border}`,
      boxShadow: `0 -10px 30px ${T.shadow}`,
      zIndex: 100,
      display: "flex",
      flexDirection: "column",
      animation: "slideUp 0.2s ease",
      touchAction: "auto",
      WebkitOverflowScrolling: "touch",
    } : {
      position: "fixed",
      top: "50%",
      right: 16,
      transform: "translate3d(0, -50%, 0)",
      width: 440,
      maxWidth: "calc(100vw - 32px)",
      maxHeight: "calc(100dvh - 100px)",
      background: T.toolbar,
      border: `1px solid ${T.border}`,
      borderRadius: 12,
      boxShadow: `0 12px 36px ${T.shadow}`,
      zIndex: 100,
      display: "flex",
      flexDirection: "column",
      touchAction: "auto",
    },
    studyHead: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: isMobile ? "6px 14px 8px" : "10px 14px",
      borderBottom: `1px solid ${T.border}`,
      flexShrink: 0,
    },
    studyTitle: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: 700,
      color: T.text,
      display: "flex",
      alignItems: "center",
      gap: 6,
    },
    studyClose: {
      color: T.muted,
      fontSize: 13,
      background: "none",
      border: "none",
      cursor: "pointer",
    },
    studyBody: {
      overflowY: "auto",
      WebkitOverflowScrolling: "touch",
      touchAction: "pan-y",
      padding: isMobile ? 14 : 16,
      flex: 1,
      display: "flex",
      flexDirection: "column",
      gap: 14,
    },
    studyLabel: {
      fontSize: 11,
      fontWeight: 600,
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      color: T.muted,
      marginBottom: 6,
    },
    studyGenerateBtn: {
      width: "100%",
      padding: "12px 16px",
      background: T.accent,
      color: "white",
      border: "none",
      borderRadius: 10,
      fontSize: 14,
      fontWeight: 700,
      cursor: "pointer",
      transition: "opacity 0.15s ease",
    },
    studyErrorBox: {
      background: theme === "dark" ? "rgba(233,69,96,0.15)" : "#FFF0F0",
      color: T.accent,
      borderRadius: 8,
      padding: "10px 12px",
      fontSize: 12.5,
      lineHeight: 1.5,
      display: "flex",
      flexDirection: "column",
      gap: 4,
    },
  };
}
