export const SUBJECTS = [
  {
    id: "anatomy",
    label: "Anatomy",
    icon: "🦴",
    accent: "#ef4444",
    image: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Upper Limb Anatomy", content: "The upper limb consists of the shoulder, arm, forearm, and hand. Key bones: clavicle, scapula, humerus, radius, ulna, carpals, metacarpals, phalanges. Major muscles: deltoid, biceps brachii, triceps, brachioradialis, flexor/extensor groups. The brachial plexus (C5-T1) innervates the upper limb." },
      { title: "Thoracic Cavity", content: "The thoracic cavity contains the heart, lungs, esophagus, and trachea. The mediastinum is the central compartment. The diaphragm separates thoracic and abdominal cavities. Rib pairs 1-7 are true ribs, 8-10 are false ribs, 11-12 are floating ribs." },
      { title: "Cranial Nerves", content: "There are 12 pairs of cranial nerves: I (Olfactory), II (Optic), III (Oculomotor), IV (Trochlear), V (Trigeminal), VI (Abducens), VII (Facial), VIII (Vestibulocochlear), IX (Glossopharyngeal), X (Vagus), XI (Accessory), XII (Hypoglossal). Mnemonic: 'On Old Olympus Towering Tops A Finn And German Viewed Some Hops'." },
    ],
    questions: [
      { q: "Which cranial nerve is responsible for taste sensation from the anterior two-thirds of the tongue?", options: ["Glossopharyngeal (IX)", "Facial (VII)", "Vagus (X)", "Trigeminal (V)"], answer: 1, explanation: "The facial nerve (CN VII) provides taste sensation to the anterior two-thirds of the tongue via the chorda tympani branch.", difficulty: "medium" },
      { q: "The biceps brachii muscle is primarily innervated by which nerve?", options: ["Radial nerve", "Ulnar nerve", "Musculocutaneous nerve", "Median nerve"], answer: 2, explanation: "The musculocutaneous nerve (C5-C7) innervates the biceps brachii, brachialis, and coracobrachialis muscles.", difficulty: "easy" },
      { q: "Which structure passes through the foramen magnum?", options: ["Optic nerve", "Spinal cord", "Internal carotid artery", "Facial nerve"], answer: 1, explanation: "The spinal cord transitions to the medulla oblongata as it passes through the foramen magnum, along with the vertebral arteries and accessory nerves.", difficulty: "easy" },
      { q: "The true ribs are ribs:", options: ["1-5", "1-7", "1-10", "1-12"], answer: 1, explanation: "Ribs 1-7 are true ribs (vertebrosternal) — they connect directly to the sternum via their own costal cartilages.", difficulty: "easy" },
      { q: "Which muscle separates the thoracic and abdominal cavities?", options: ["External intercostal", "Diaphragm", "Rectus abdominis", "Pectoralis major"], answer: 1, explanation: "The diaphragm is the dome-shaped muscle separating the thoracic and abdominal cavities, innervated by the phrenic nerve (C3-C5).", difficulty: "easy" },
    ],
  },
  {
    id: "physiology",
    label: "Physiology",
    icon: "🫀",
    accent: "#3b82f6",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Cardiac Cycle", content: "The cardiac cycle consists of systole (contraction) and diastole (relaxation). Phases: atrial systole, isovolumetric contraction, rapid ejection, reduced ejection, isovolumetric relaxation, rapid filling, reduced filling. Normal heart sounds: S1 (mitral/tricuspid closure) and S2 (aortic/pulmonary closure)." },
      { title: "Renal Physiology", content: "The nephron filters blood at the glomerulus, then reabsorbs and secretes along the PCT, loop of Henle, DCT, and collecting duct. GFR is approximately 125 mL/min. Key hormones: ADH (water reabsorption), aldosterone (Na+ reabsorption), ANP (Na+ excretion)." },
      { title: "Action Potential", content: "Neuronal action potential: resting potential (-70mV), depolarization (Na+ influx), repolarization (K+ efflux), hyperpolarization. The absolute refractory period prevents re-excitation during depolarization. Threshold is approximately -55mV." },
    ],
    questions: [
      { q: "Normal resting membrane potential of a neuron is approximately:", options: ["-90 mV", "-70 mV", "-55 mV", "+30 mV"], answer: 1, explanation: "The resting membrane potential of a typical neuron is approximately -70 mV, maintained by the Na+/K+ ATPase pump and K+ leak channels.", difficulty: "easy" },
      { q: "Which hormone increases water reabsorption in the collecting duct?", options: ["Aldosterone", "ADH (Vasopressin)", "ANP", "Renin"], answer: 1, explanation: "ADH (antidiuretic hormone) increases water permeability of the collecting duct by inserting aquaporin-2 channels, promoting water reabsorption.", difficulty: "medium" },
      { q: "The first heart sound (S1) is caused by:", options: ["Closure of aortic and pulmonary valves", "Closure of mitral and tricuspid valves", "Opening of mitral valve", "Atrial contraction"], answer: 1, explanation: "S1 ('lub') is produced by closure of the atrioventricular valves (mitral and tricuspid) at the beginning of ventricular systole.", difficulty: "easy" },
      { q: "Glomerular filtration rate (GFR) is normally approximately:", options: ["50 mL/min", "80 mL/min", "125 mL/min", "200 mL/min"], answer: 2, explanation: "Normal GFR is approximately 125 mL/min (180 L/day). It can be estimated using creatinine clearance or eGFR formulas.", difficulty: "medium" },
      { q: "During the rapid ejection phase of the cardiac cycle:", options: ["AV valves are open", "Semilunar valves are open", "All valves are closed", "Only mitral valve is open"], answer: 1, explanation: "During rapid ejection, the semilunar valves (aortic and pulmonary) are open as blood is ejected from the ventricles into the aorta and pulmonary artery.", difficulty: "medium" },
    ],
  },
  {
    id: "pharmacology",
    label: "Pharmacology",
    icon: "💊",
    accent: "#a855f7",
    image: "https://images.unsplash.com/photo-1587854692152-cbe611db5902?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Pharmacokinetics", content: "Pharmacokinetics describes ADME: Absorption (drug entry), Distribution (drug movement), Metabolism (biotransformation, mainly hepatic via CYP450), and Excretion (mainly renal). Bioavailability is the fraction of drug reaching systemic circulation. First-pass metabolism reduces oral bioavailability." },
      { title: "Autonomic Pharmacology", content: "Sympathetic: adrenergic receptors (alpha-1 vasoconstriction, alpha-2 inhibition, beta-1 cardiac, beta-2 bronchodilation). Parasympathetic: cholinergic receptors (muscarinic and nicotinic). Acetylcholine is the parasympathetic neurotransmitter; noradrenaline is the sympathetic neurotransmitter." },
      { title: "Antibiotic Classes", content: "Beta-lactams (penicillins, cephalosporins) inhibit cell wall synthesis. Macrolides (erythromycin, azithromycin) inhibit 50S ribosome. Aminoglycosides (gentamicin) inhibit 30S ribosome. Fluoroquinolones (ciprofloxacin) inhibit DNA gyrase. Sulfonamides inhibit folate synthesis." },
    ],
    questions: [
      { q: "First-pass metabolism primarily occurs in the:", options: ["Kidneys", "Liver", "Lungs", "Small intestine"], answer: 1, explanation: "First-pass (pre-systemic) metabolism mainly occurs in the liver, where orally administered drugs are partially metabolized before reaching systemic circulation.", difficulty: "easy" },
      { q: "Which receptor does salbutamol primarily act on?", options: ["Alpha-1", "Beta-1", "Beta-2", "Muscarinic"], answer: 2, explanation: "Salbutamol is a selective beta-2 agonist that causes bronchodilation, used in asthma and COPD management.", difficulty: "easy" },
      { q: "Beta-lactam antibiotics exert their bactericidal effect by inhibiting:", options: ["Protein synthesis", "Cell wall synthesis", "DNA replication", "Folate synthesis"], answer: 1, explanation: "Beta-lactams (penicillins, cephalosporins) inhibit bacterial cell wall (peptidoglycan) synthesis by binding to penicillin-binding proteins (PBPs).", difficulty: "medium" },
      { q: "Which enzyme system is primarily responsible for drug metabolism in the liver?", options: ["CYP450", "ACE", "MAO", "COMT"], answer: 0, explanation: "The cytochrome P450 (CYP450) enzyme system is the primary hepatic drug-metabolizing system, responsible for phase I metabolism of most drugs.", difficulty: "medium" },
      { q: "Gentamicin belongs to which class of antibiotics?", options: ["Beta-lactams", "Macrolides", "Aminoglycosides", "Fluoroquinolones"], answer: 2, explanation: "Gentamicin is an aminoglycoside that inhibits the 30S ribosomal subunit, causing misreading of mRNA. It is nephrotoxic and ototoxic.", difficulty: "easy" },
    ],
  },
  {
    id: "pathology",
    label: "Pathology",
    icon: "🔬",
    accent: "#f97316",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Inflammation", content: "Acute inflammation: vascular response (vasodilation, increased permeability), cellular response (neutrophil margination, emigration, chemotaxis). Chemical mediators: histamine, bradykinin, prostaglandins, leukotrienes. Five cardinal signs: rubor (redness), calor (heat), tumor (swelling), dolor (pain), functio laesa (loss of function)." },
      { title: "Neoplasia", content: "Benign tumors: well-differentiated, slow-growing, encapsulated, no metastasis. Malignant tumors: anaplasia, rapid growth, invasion, metastasis. Carcinogenesis: initiation (mutation), promotion (clonal expansion), progression (malignant transformation). Hallmarks: sustained proliferation, evading growth suppressors, resisting apoptosis, angiogenesis, invasion/metastasis." },
      { title: "Cell Injury", content: "Causes of cell injury: ischemia, toxins, infections, autoimmune. Reversible injury: cellular swelling, fatty change. Irreversible injury: mitochondrial failure, membrane damage, nuclear condensation (pyknosis), fragmentation (karyorrhexis), dissolution (karyolysis). Necrosis vs apoptosis: necrosis is pathological, apoptosis is programmed." },
    ],
    questions: [
      { q: "Which of the following is NOT a cardinal sign of inflammation?", options: ["Rubor", "Calor", "Nausea", "Dolor"], answer: 2, explanation: "The five cardinal signs of inflammation are rubor (redness), calor (heat), tumor (swelling), dolor (pain), and functio laesa (loss of function). Nausea is not a cardinal sign.", difficulty: "easy" },
      { q: "Pyknosis refers to:", options: ["Nuclear dissolution", "Nuclear condensation", "Nuclear fragmentation", "Cell swelling"], answer: 1, explanation: "Pyknosis is irreversible nuclear condensation — one of the hallmarks of irreversible cell injury, preceding karyorrhexis (fragmentation) and karyolysis (dissolution).", difficulty: "medium" },
      { q: "Which cell type is predominant in acute inflammation?", options: ["Lymphocytes", "Neutrophils", "Macrophages", "Eosinophils"], answer: 1, explanation: "Neutrophils (PMNs) are the predominant cell type in acute inflammation (first 24-48 hours). Monocytes/macrophages dominate in chronic inflammation.", difficulty: "easy" },
      { q: "A well-differentiated, encapsulated tumor that does not metastasize is:", options: ["Malignant", "Benign", "Premalignant", "Metastatic"], answer: 1, explanation: "Benign tumors are typically well-differentiated, slow-growing, encapsulated, and do not metastasize. Malignant tumors show anaplasia, invasion, and metastasis.", difficulty: "easy" },
      { q: "Apoptosis is best described as:", options: ["Pathological cell death with inflammation", "Programmed cell death without inflammation", "Cellular swelling due to ischemia", "Nuclear dissolution"], answer: 1, explanation: "Apoptosis is programmed cell death characterized by cell shrinkage, chromatin condensation, apoptotic bodies, and no inflammation. Necrosis is pathological cell death with inflammation.", difficulty: "medium" },
    ],
  },
  {
    id: "microbiology",
    label: "Microbiology",
    icon: "🦠",
    accent: "#22c55e",
    image: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Bacterial Structure", content: "Bacteria are prokaryotes: no nucleus, no membrane-bound organelles. Gram-positive: thick peptidoglycan, teichoic acids. Gram-negative: thin peptidoglycan, outer membrane with LPS (endotoxin). Shapes: cocci (spherical), bacilli (rod-shaped), spirochetes (spiral). Common stains: Gram stain, Ziehl-Neelsen (acid-fast for TB)." },
      { title: "Pathogenic Bacteria", content: "Staphylococcus aureus: skin infections, abscesses, food poisoning. Streptococcus pyogenes: pharyngitis, cellulitis, rheumatic fever. Escherichia coli: UTI, diarrhea. Mycobacterium tuberculosis: tuberculosis. Salmonella typhi: typhoid fever. Neisseria meningitidis: meningococcal meningitis." },
      { title: "Medical Parasitology", content: "Plasmodium species cause malaria (P. falciparum most severe). Entamoeba histolytica causes amoebic dysentery. Ascaris lumbricoides is the commonest intestinal nematode. Schistosoma species cause schistosomiasis. Trypanosoma causes sleeping sickness. Leishmania causes leishmaniasis." },
    ],
    questions: [
      { q: "Which staining technique is used to identify Mycobacterium tuberculosis?", options: ["Gram stain", "Ziehl-Neelsen stain", "Giemsa stain", "India ink"], answer: 1, explanation: "Ziehl-Neelsen (acid-fast) stain is used for Mycobacterium species because their cell walls contain mycolic acid, which resists decolorization by acid-alcohol.", difficulty: "easy" },
      { q: "Gram-negative bacteria differ from Gram-positive bacteria by having:", options: ["Thick peptidoglycan layer", "Outer membrane with lipopolysaccharide", "Teichoic acids", "No cell wall"], answer: 1, explanation: "Gram-negative bacteria have a thin peptidoglycan layer and an outer membrane containing lipopolysaccharide (LPS/endotoxin). Gram-positive bacteria have thick peptidoglycan and teichoic acids.", difficulty: "medium" },
      { q: "Which Plasmodium species causes the most severe form of malaria?", options: ["P. vivax", "P. falciparum", "P. malariae", "P. ovale"], answer: 1, explanation: "Plasmodium falciparum causes the most severe form of malaria, with potential for cerebral malaria, severe anemia, and multi-organ failure.", difficulty: "easy" },
      { q: "The commonest cause of non-nosocomial urinary tract infection is:", options: ["Staphylococcus aureus", "Escherichia coli", "Pseudomonas aeruginosa", "Enterococcus faecalis"], answer: 1, explanation: "E. coli is the commonest cause of community-acquired UTI, responsible for 80-90% of cases, due to its uropathogenic virulence factors (fimbriae, hemolysin).", difficulty: "easy" },
      { q: "Which bacterium causes rheumatic fever following untreated pharyngitis?", options: ["Staphylococcus aureus", "Streptococcus pyogenes", "Streptococcus pneumoniae", "Haemophilus influenzae"], answer: 1, explanation: "Streptococcus pyogenes (Group A Streptococcus) causes pharyngitis that can lead to acute rheumatic fever via molecular mimicry (antibodies cross-react with heart tissue).", difficulty: "medium" },
    ],
  },
  {
    id: "medicine",
    label: "Internal Medicine",
    icon: "🩺",
    accent: "#06b6d4",
    image: "https://images.unsplash.com/photo-1576091160399-7ba3828c9d23?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Hypertension Management", content: "Hypertension: BP >140/90. Stages: Stage 1 (140-159/90-99), Stage 2 (>160/>100). First-line: thiazides, ACE inhibitors, ARBs, CCBs. Complications: stroke, MI, heart failure, CKD, retinopathy. Lifestyle: salt reduction, weight loss, exercise, DASH diet." },
      { title: "Diabetes Mellitus", content: "Type 1: autoimmune beta-cell destruction, absolute insulin deficiency. Type 2: insulin resistance + relative deficiency. Diagnosis: FPG >7.0 mmol/L, OGTT >11.1, HbA1c >6.5%. Complications: retinopathy, nephropathy, neuropathy, cardiovascular disease. DKA: high glucose, ketones, acidosis (pH <7.3, HCO3 <15)." },
      { title: "Approach to Chest Pain", content: "Differential: ACS (MI), PE, aortic dissection, pericarditis, pneumothorax, GERD, musculoskeletal. Red flags: crushing pain, radiation to arm/jaw, diaphoresis, dyspnea, syncope. ECG within 10 minutes. Troponin at 0 and 3-6 hours. MONA for ACS: Morphine, Oxygen, Nitrates, Aspirin." },
    ],
    questions: [
      { q: "What is the diagnostic cutoff for fasting blood glucose in diabetes mellitus?", options: [">5.6 mmol/L", ">6.1 mmol/L", ">7.0 mmol/L", ">11.1 mmol/L"], answer: 2, explanation: "Fasting plasma glucose >7.0 mmol/L (126 mg/dL) on two separate occasions is diagnostic of diabetes mellitus. HbA1c >6.5% or OGTT >11.1 mmol/L are also diagnostic.", difficulty: "easy" },
      { q: "First-line drug for a 55-year-old with Stage 1 hypertension and no comorbidities:", options: ["Furosemide", "Lisinopril", "Hydralazine", "Methyldopa"], answer: 1, explanation: "ACE inhibitors (e.g., lisinopril), thiazides, ARBs, or CCBs are first-line for uncomplicated hypertension. Choice depends on comorbidities and patient demographics.", difficulty: "medium" },
      { q: "In diabetic ketoacidosis, the arterial pH is typically:", options: [">7.35", "7.30-7.35", "<7.3", "<7.0"], answer: 2, explanation: "DKA is defined by pH <7.3, serum bicarbonate <15 mmol/L, ketonemia, and hyperglycemia. Treatment: IV fluids, insulin infusion, potassium replacement, and treating the precipitant.", difficulty: "medium" },
      { q: "Which ECG finding is most specific for acute STEMI?", options: ["T wave inversion", "ST elevation", "Q waves", "Prolonged QT"], answer: 1, explanation: "ST elevation in two or more contiguous leads is diagnostic of STEMI and requires urgent reperfusion (PCI or thrombolysis) within 12 hours of symptom onset.", difficulty: "easy" },
      { q: "The target HbA1c for most patients with Type 2 diabetes is:", options: ["<5.7%", "<6.0%", "<7.0%", "<8.0%"], answer: 2, explanation: "The general HbA1c target for most adults with diabetes is <7.0%. Targets may be individualized (tighter <6.5% in some, looser <8.0% in elderly/frail patients).", difficulty: "easy" },
    ],
  },
  {
    id: "surgery",
    label: "Surgery",
    icon: "🔪",
    accent: "#ec4899",
    image: "https://images.unsplash.com/photo-1579684385121-2964842c3e8a?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Asepsis and Sterility", content: "Aseptic technique prevents surgical site infections. Principles: sterile field, sterile instruments, sterile personnel, proper gowning and gloving, skin preparation (chlorhexidine/povidone-iodine), draping. WHO surgical safety checklist: sign in, time out, sign out." },
      { title: "Acute Abdomen", content: "Causes by location: RUQ (cholecystitis, hepatitis), LUQ (splenic rupture, perforated ulcer), RLQ (appendicitis, ectopic), LLQ (diverticulitis). Generalized (perforation, peritonitis). Key signs: guarding, rigidity, rebound tenderness. Imaging: upright CXR (free air), CT abdomen." },
      { title: "Fluid Management", content: "Maintenance: 30 mL/kg/day (approx 2500 mL for 70kg). Hartmann's (lactated Ringer's) is balanced crystalloid. Normal saline (0.9% NaCl) for resuscitation. Blood products for hemorrhage. NBM patients need maintenance fluids + electrolyte replacement." },
    ],
    questions: [
      { q: "Which sign is most suggestive of peritonitis on abdominal examination?", options: ["Borborygmi", "Rebound tenderness", "Hepatomegaly", "Ascites"], answer: 1, explanation: "Rebound tenderness (Blumberg's sign) indicates peritoneal inflammation. Guarding and rigidity are also key signs of peritonitis.", difficulty: "easy" },
      { q: "The most common cause of acute appendicitis is:", options: ["Viral infection", "Lymphoid hyperplasia/fecalith obstruction", "Bacterial infection alone", "Parasitic infection"], answer: 1, explanation: "Acute appendicitis is most commonly caused by obstruction of the appendiceal lumen by a fecalith or lymphoid hyperplasia, leading to bacterial overgrowth, inflammation, and potential perforation.", difficulty: "medium" },
      { q: "Which fluid is preferred for initial resuscitation in hemorrhagic shock?", options: ["5% Dextrose", "Normal saline or Hartmann's", "Colloid only", "Potassium chloride"], answer: 1, explanation: "Isotonic crystalloids (normal saline or Hartmann's/lactated Ringer's) are first-line for fluid resuscitation in hemorrhagic shock, followed by blood products as needed.", difficulty: "easy" },
      { q: "The WHO Surgical Safety Checklist is performed at which three critical points?", options: ["Pre-op, intra-op, post-op", "Sign in, time out, sign out", "Anesthesia, incision, closure", "Admission, surgery, discharge"], answer: 1, explanation: "The WHO Surgical Safety Checklist has three phases: Sign in (before anesthesia), Time out (before skin incision), and Sign out (before patient leaves OR).", difficulty: "medium" },
      { q: "A 25-year-old female with RLQ pain and a positive pregnancy test likely has:", options: ["Appendicitis", "Ectopic pregnancy", "Ovarian cyst", "PID"], answer: 1, explanation: "In any female of reproductive age with abdominal pain and a positive pregnancy test, ectopic pregnancy must be ruled out urgently with ultrasound and serum beta-hCG.", difficulty: "medium" },
    ],
  },
  {
    id: "obgyn",
    label: "Obstetrics & Gynaecology",
    icon: "🤰",
    accent: "#f59e0b",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Pre-eclampsia", content: "Pre-eclampsia: new-onset hypertension (>140/90) after 20 weeks with proteinuria or end-organ damage. Severe features: BP >160/110, platelets <100k, elevated LFTs, headache, visual disturbance. Management: magnesium sulfate for seizure prophylaxis, antihypertensives (labetalol, nifedipine), delivery is definitive treatment." },
      { title: "Normal Labour", content: "Three stages: first (dilation 3-10cm), second (delivery), third (placenta). Cardinal movements: engagement, descent, flexion, internal rotation, extension, external rotation, expulsion. Partograph monitors labour progress. Prolonged labour: >18 hours (primigravida) or >12 hours (multigravida)." },
      { title: "Antenatal Care", content: "Four visits (focused ANC): booking (first trimester), 20-24 weeks, 28-32 weeks, 36-38 weeks. Routine: BP, weight, fundal height, fetal heart rate, urine (protein, glucose). Supplements: folic acid (pre-conception to 12 weeks), iron, tetanus immunization. HIV testing is essential." },
    ],
    questions: [
      { q: "Magnesium sulfate is used in pre-eclampsia to:", options: ["Lower blood pressure", "Prevent seizures (eclampsia prophylaxis)", "Induce labor", "Reduce proteinuria"], answer: 1, explanation: "Magnesium sulfate is the drug of choice for eclampsia prophylaxis and treatment. It acts as a CNS depressant and vasodilator. Antihypertensives (labetalol, nifedipine) are used separately for BP control.", difficulty: "medium" },
      { q: "The first stage of labor is defined as:", options: ["Delivery of the baby", "Cervical dilation from 3 to 10 cm", "Expulsion of the placenta", "From engagement to delivery"], answer: 1, explanation: "The first stage of labor is cervical dilation from 3 cm (latent phase) to 10 cm (full dilation). The second stage is delivery of the baby, and the third stage is delivery of the placenta.", difficulty: "easy" },
      { q: "Folic acid supplementation in pregnancy should ideally begin:", options: ["After the first trimester", "Pre-conception and continue to 12 weeks", "Only in the third trimester", "Only if anemia is present"], answer: 1, explanation: "Folic acid (400-4000 mcg depending on risk) should be started pre-conception and continued until 12 weeks gestation to prevent neural tube defects (spina bifida, anencephaly).", difficulty: "easy" },
      { q: "Severe pre-eclampsia is diagnosed when blood pressure is:", options: [">130/85", ">140/90", ">160/110", ">180/120"], answer: 2, explanation: "Severe pre-eclampsia is defined by BP >160/110 mmHg, or end-organ dysfunction (platelets <100k, elevated LFTs, creatinine >1.1, pulmonary edema, headache/visual symptoms).", difficulty: "medium" },
      { q: "The partograph is used to monitor:", options: ["Fetal growth", "Labor progress", "Maternal nutrition", "Postpartum recovery"], answer: 1, explanation: "The partograph is a graphical record of labor progress, including cervical dilation, fetal heart rate, uterine contractions, maternal vital signs, and alert/action lines.", difficulty: "easy" },
    ],
  },
  {
    id: "paediatrics",
    label: "Paediatrics",
    icon: "👶",
    accent: "#10b981",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "IMCI Approach", content: "Integrated Management of Childhood Illness (IMCI) assesses children 0-5 years. Color triage: Pink (urgent referral), Yellow (treatment at health facility), Green (home management). Key assessments: danger signs (unable to drink, convulsions, lethargy, vomiting everything), cough, diarrhea, fever, ear problems, malnutrition, anemia." },
      { title: "Neonatal Resuscitation", content: "Steps: dry, warm, position, stimulate. Assess: breathing, heart rate, color. If not breathing: PPV with bag-mask (21% O2 for term, 30% for preterm). HR <60: chest compressions with ventilation (3:1 ratio). HR <60 after 60 seconds: intubate, medications (adrenaline, volume)." },
      { title: "Childhood Immunization", content: "Birth: BCG, OPV-0, HepB-0. 6 weeks: OPV-1, Penta-1 (DPT-HepB-Hib), PCV-1, Rota-1. 10 weeks: OPV-2, Penta-2, PCV-2, Rota-2. 14 weeks: OPV-3, Penta-3, PCV-3. 9 months: Measles-1. 15-18 months: Measles-2, OPV booster." },
    ],
    questions: [
      { q: "In IMCI, a child classified as 'PINK' requires:", options: ["Home management", "Treatment at health facility", "Urgent referral to hospital", "Observation only"], answer: 2, explanation: "In IMCI, PINK classification means the child has severe disease and requires urgent referral to hospital for treatment before referral if possible.", difficulty: "easy" },
      { q: "During neonatal resuscitation, chest compressions are indicated when:", options: ["The baby is not crying", "Heart rate is <60 bpm despite effective ventilation", "The baby is cyanosed", "APGAR score is <7"], answer: 1, explanation: "Chest compressions are started when heart rate remains <60 bpm after at least 30 seconds of effective positive pressure ventilation. Ratio is 3:1 (compressions:ventilations).", difficulty: "medium" },
      { q: "Which vaccine is given at birth in the Nigerian immunization schedule?", options: ["Pentavalent vaccine", "BCG", "Measles vaccine", "Pneumococcal vaccine"], answer: 1, explanation: "At birth, BCG (tuberculosis), OPV-0 (polio), and HepB-0 (hepatitis B) are given. Pentavalent, pneumococcal, and rotavirus vaccines start at 6 weeks.", difficulty: "easy" },
      { q: "The most common cause of febrile convulsions in children under 5 in malaria-endemic areas is:", options: ["Epilepsy", "Malaria", "Meningitis", "Hypoglycemia"], answer: 1, explanation: "In malaria-endemic areas, Plasmodium falciparum malaria is the commonest cause of fever and febrile convulsions in children under 5. Always check blood glucose and malaria smear.", difficulty: "medium" },
      { q: "A dehydrated child (5% dehydration) weighing 10kg has a fluid deficit of:", options: ["250 mL", "500 mL", "1000 mL", "1500 mL"], answer: 1, explanation: "Fluid deficit = weight (kg) x dehydration (%) x 10. For 10kg at 5%: 10 x 5 x 10 = 500 mL. Give half in first 8 hours, remainder over next 16 hours, plus maintenance.", difficulty: "medium" },
    ],
  },
  {
    id: "nursing",
    label: "Nursing Science",
    icon: "💉",
    accent: "#8b5cf6",
    image: "https://images.unsplash.com/photo-1579684385121-2964842c3e8a?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Nursing Process", content: "The nursing process has 5 steps: Assessment (data collection), Diagnosis (NANDA diagnoses), Planning (goals and interventions), Implementation (executing care), Evaluation (assessing outcomes). Documentation should be accurate, timely, and legal." },
      { title: "Vital Signs", content: "Normal ranges: Temperature 36.5-37.5°C, Pulse 60-100 bpm, Respiration 12-20/min, BP 120/80 mmHg, SpO2 >95%. Pediatric vitals differ by age. Abnormal findings require prompt intervention and documentation." },
      { title: "Infection Control", content: "Standard precautions: hand hygiene (WHO 5 moments), PPE (gloves, gown, mask, eye protection), safe injection practices, sharps disposal. Transmission-based precautions: contact, droplet, airborne. Hand washing: 40-60 seconds (soap), 20-30 seconds (alcohol-based)." },
    ],
    questions: [
      { q: "The correct order of the nursing process is:", options: ["Diagnosis, Assessment, Planning, Implementation, Evaluation", "Assessment, Diagnosis, Planning, Implementation, Evaluation", "Planning, Assessment, Diagnosis, Evaluation, Implementation", "Assessment, Planning, Diagnosis, Implementation, Evaluation"], answer: 1, explanation: "The nursing process follows ADPIE: Assessment, Diagnosis, Planning, Implementation, Evaluation. It is a systematic, patient-centered approach to nursing care.", difficulty: "easy" },
      { q: "WHO recommends hand washing with soap and water for at least:", options: ["10 seconds", "20 seconds", "40-60 seconds", "2 minutes"], answer: 2, explanation: "WHO recommends hand washing with soap and water for 40-60 seconds. Alcohol-based hand rub takes 20-30 seconds. The WHO 'My 5 Moments for Hand Hygiene' guides when to perform hand hygiene.", difficulty: "easy" },
      { q: "Normal adult respiratory rate is:", options: ["8-12/min", "12-20/min", "20-30/min", "30-40/min"], answer: 1, explanation: "Normal adult respiratory rate is 12-20 breaths per minute. Tachypnea (>20) may indicate respiratory distress, fever, anxiety, or metabolic acidosis.", difficulty: "easy" },
      { q: "Which PPE should be worn for droplet precautions (e.g., meningococcal meningitis)?", options: ["Only gloves", "Gloves and gown", "Surgical mask, gloves, gown, eye protection", "N95 respirator only"], answer: 2, explanation: "Droplet precautions require surgical mask, gloves, gown, and eye protection. Airborne precautions (e.g., TB) require N95 respirator in addition to standard PPE.", difficulty: "medium" },
      { q: "When taking a blood pressure, the cuff should cover approximately what percentage of the upper arm?", options: ["40%", "60%", "80%", "100%"], answer: 2, explanation: "The BP cuff bladder should cover approximately 80% of the arm circumference and 40% of the arm length. An improperly sized cuff gives inaccurate readings.", difficulty: "medium" },
    ],
  },
  {
    id: "biochemistry",
    label: "Biochemistry",
    icon: "🧬",
    accent: "#6366f1",
    image: "https://images.unsplash.com/photo-1532187843-6f69f042f836?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Carbohydrate Metabolism", content: "Glycolysis: glucose to pyruvate (cytoplasm, net 2 ATP). Krebs cycle: acetyl-CoA oxidation (mitochondria, 2 ATP, NADH, FADH2). ETC: oxidative phosphorylation (inner mitochondrial membrane, ~32 ATP). Gluconeogenesis: non-carbohydrate to glucose (liver, kidney). Glycogenesis/glycogenolysis: glycogen storage/breakdown." },
      { title: "Enzymes", content: "Enzymes are biological catalysts that lower activation energy. Factors: temperature, pH, substrate concentration, inhibitors. Competitive inhibitors bind active site (increase Km, Vmax unchanged). Non-competitive inhibitors bind allosteric site (decrease Vmax, Km unchanged). Michaelis-Menten kinetics." },
      { title: "Lipid Metabolism", content: "Fatty acid oxidation (beta-oxidation): in mitochondria, produces acetyl-CoA. Ketogenesis: in liver during fasting, produces ketone bodies (acetoacetate, beta-hydroxybutyrate, acetone). Cholesterol synthesis: HMG-CoA reductase rate-limiting enzyme (target of statins). Lipoproteins: chylomicrons, VLDL, LDL, HDL." },
    ],
    questions: [
      { q: "The net ATP yield from glycolysis of one glucose molecule is:", options: ["2 ATP", "4 ATP", "32 ATP", "36 ATP"], answer: 0, explanation: "Glycolysis produces 4 ATP (substrate-level phosphorylation) but consumes 2 ATP (hexokinase, PFK-1), giving a net yield of 2 ATP per glucose molecule in the cytoplasm.", difficulty: "easy" },
      { q: "Which enzyme is the rate-limiting step in cholesterol synthesis?", options: ["Lipoprotein lipase", "HMG-CoA reductase", "Lecithin cholesterol acyltransferase", "Carnitine palmitoyltransferase"], answer: 1, explanation: "HMG-CoA reductase is the rate-limiting enzyme in cholesterol synthesis. Statins (e.g., atorvastatin, simvastatin) inhibit this enzyme to lower LDL cholesterol.", difficulty: "medium" },
      { q: "Competitive enzyme inhibitors:", options: ["Decrease Vmax, no effect on Km", "Increase Km, no effect on Vmax", "Decrease both Km and Vmax", "Increase both Km and Vmax"], answer: 1, explanation: "Competitive inhibitors compete with substrate for the active site, increasing apparent Km (more substrate needed for half-maximal velocity) but Vmax remains unchanged at high substrate concentrations.", difficulty: "hard" },
      { q: "Ketone bodies are produced during:", options: ["Fed state", "Fasting/starvation", "High carbohydrate diet", "Insulin excess"], answer: 1, explanation: "Ketone bodies (acetoacetate, beta-hydroxybutyrate, acetone) are produced by the liver during fasting/starvation when glucose is scarce and fatty acid oxidation increases. Excessive production causes ketoacidosis (e.g., DKA).", difficulty: "medium" },
      { q: "The final electron acceptor in the electron transport chain is:", options: ["NAD+", "FAD", "Oxygen", "ATP synthase"], answer: 2, explanation: "Oxygen is the final electron acceptor in the ETC, accepting electrons and combining with protons to form water. Without oxygen, oxidative phosphorylation stops (e.g., cyanide poisoning).", difficulty: "easy" },
    ],
  },
  {
    id: "radiography",
    label: "Radiography",
    icon: "📡",
    accent: "#0ea5e9",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "X-ray Production", content: "X-rays are produced when high-energy electrons strike a target (tungsten). Bremsstrahlung radiation: deceleration of electrons. Characteristic radiation: inner shell electron ejection. X-ray tube components: cathode (filament), anode (target), glass envelope, cooling system." },
      { title: "Radiation Protection", content: "ALARA principle: As Low As Reasonably Achievable. Time, Distance, Shielding. Lead aprons (0.5mm Pb), thyroid shields, gonadal shields. Personnel monitoring: film badges, TLDs. Pregnant patients: avoid if possible, shield abdomen." },
      { title: "Imaging Modalities", content: "X-ray: bone, chest. CT: cross-sectional, trauma, stroke. MRI: soft tissue, CNS, musculoskeletal (no ionizing radiation). Ultrasound: obstetrics, abdomen, no radiation. Fluoroscopy: real-time imaging, GI studies. Nuclear medicine: functional imaging (PET, SPECT)." },
    ],
    questions: [
      { q: "The ALARA principle in radiography stands for:", options: ["As Low As Randomly Achieved", "As Low As Reasonably Achievable", "Always Leave Area Radiation-free", "Acceptable Levels And Radiation Amounts"], answer: 1, explanation: "ALARA (As Low As Reasonably Achievable) is the core radiation protection principle, achieved through minimizing time, maximizing distance, and using shielding.", difficulty: "easy" },
      { q: "Which imaging modality does NOT use ionizing radiation?", options: ["X-ray", "CT scan", "MRI", "Fluoroscopy"], answer: 2, explanation: "MRI uses magnetic fields and radio waves, not ionizing radiation. X-ray, CT, and fluoroscopy all use ionizing radiation. Ultrasound also does not use ionizing radiation.", difficulty: "easy" },
      { q: "The target material most commonly used in X-ray tubes is:", options: ["Copper", "Tungsten", "Lead", "Aluminum"], answer: 1, explanation: "Tungsten is the most common target material in X-ray tubes due to its high atomic number (74), high melting point (3422°C), and efficient X-ray production.", difficulty: "medium" },
      { q: "For a pregnant patient requiring imaging, the preferred modality is:", options: ["CT abdomen", "X-ray abdomen", "Ultrasound", "Fluoroscopy"], answer: 2, explanation: "Ultrasound is preferred in pregnancy as it uses no ionizing radiation. MRI may also be used. CT and X-ray should be avoided unless absolutely necessary, with abdominal shielding.", difficulty: "easy" },
      { q: "The minimum lead thickness for protective aprons in radiography is:", options: ["0.1 mm", "0.25 mm", "0.5 mm", "1.0 mm"], answer: 2, explanation: "Lead aprons should have a minimum lead equivalence of 0.5 mm to provide adequate protection from scattered radiation during fluoroscopic and radiographic procedures.", difficulty: "medium" },
    ],
  },
  {
    id: "dentistry",
    label: "Dentistry",
    icon: "🦷",
    accent: "#fbbf24",
    image: "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Tooth Anatomy", content: "A tooth has a crown (clinical) and root(s). Tissues: enamel (hardest, 96% inorganic), dentin (makes up bulk), cementum (root surface), pulp (vascular/nerve). Periodontal ligament attaches tooth to alveolar bone. Primary dentition: 20 teeth. Permanent: 32 teeth." },
      { title: "Dental Caries", content: "Caries is caused by acid-producing bacteria (Streptococcus mutans) fermenting carbohydrates. Stages: white spot to enamel caries to dentin caries to pulpitis to periapical abscess. Prevention: fluoride, oral hygiene, diet modification, sealants. Treatment: restoration (fillings), RCT, extraction." },
      { title: "Oral Examination", content: "Extraoral: facial symmetry, lymph nodes, TMJ. Intraoral: soft tissues (mucosa, tongue, palate), teeth (charting: restorations, caries, missing), periodontal (probing depths, mobility, bleeding). Investigations: periapical X-rays, OPG, vitality tests (cold, EPT)." },
    ],
    questions: [
      { q: "The hardest tissue in the human body is:", options: ["Dentin", "Enamel", "Cementum", "Bone"], answer: 1, explanation: "Enamel is the hardest tissue in the human body, composed of 96% inorganic hydroxyapatite crystals. It covers the crown of the tooth.", difficulty: "easy" },
      { q: "Which bacterium is primarily responsible for dental caries?", options: ["Streptococcus mutans", "Lactobacillus acidophilus", "Porphyromonas gingivalis", "Candida albicans"], answer: 0, explanation: "Streptococcus mutans is the primary cariogenic bacterium, metabolizing carbohydrates to produce acid that demineralizes enamel and dentin.", difficulty: "easy" },
      { q: "How many teeth are in the permanent dentition?", options: ["20", "28", "32", "36"], answer: 2, explanation: "The permanent dentition has 32 teeth: 8 incisors, 4 canines, 8 premolars, and 12 molars (including 4 wisdom teeth).", difficulty: "easy" },
      { q: "Pulpitis is best described as:", options: ["Inflammation of the gums", "Inflammation of the dental pulp", "Decay of enamel", "Loss of periodontal attachment"], answer: 1, explanation: "Pulpitis is inflammation of the dental pulp, usually caused by deep caries. Symptoms range from sensitivity to severe spontaneous pain. Irreversible pulpitis requires root canal treatment.", difficulty: "medium" },
      { q: "An OPG (orthopantomogram) is a type of:", options: ["CT scan", "MRI scan", "Panoramic X-ray", "Ultrasound"], answer: 2, explanation: "An OPG (orthopantomogram) is a panoramic dental X-ray that shows all teeth, jaws, and surrounding structures in a single image, useful for general assessment and surgical planning.", difficulty: "easy" },
    ],
  },
  {
    id: "dermatology",
    label: "Dermatology",
    icon: "🧴",
    accent: "#f43f5e",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Common Skin Lesions", content: "Primary lesions: macule (flat, <1cm), patch (flat, >1cm), papule (raised, <1cm), plaque (raised, >1cm), nodule (solid, >1cm), vesicle (fluid <1cm), bulla (fluid >1cm), pustule (pus), wheal (edema). Secondary lesions: scale, crust, erosion, ulcer, fissure, atrophy, lichenification." },
      { title: "Eczema vs Psoriasis", content: "Eczema (atopic dermatitis): pruritic, erythematous, vesicular, oozing, crusting, lichenification. Flexural areas. Treatment: emollients, topical steroids, antihistamines. Psoriasis: well-demarcated erythematous plaques with silvery scales. Extensor surfaces, scalp. Treatment: topical steroids, vitamin D analogs, phototherapy, biologics." },
      { title: "Skin Infections", content: "Bacterial: impetigo (Staph/Strep), cellulitis, erysipelas. Viral: herpes simplex, herpes zoster, warts (HPV). Fungal: tinea (ringworm), candidiasis, pityriasis versicolor. Parasitic: scabies (Sarcoptes scabiei), pediculosis. Recognize patterns and prescribe appropriate antimicrobials." },
    ],
    questions: [
      { q: "A raised, fluid-filled lesion greater than 1cm in diameter is called a:", options: ["Vesicle", "Bulla", "Pustule", "Wheal"], answer: 1, explanation: "A bulla is a fluid-filled blister greater than 1cm in diameter. A vesicle is the same but less than 1cm. A pustule contains pus, and a wheal is an edematous papule.", difficulty: "easy" },
      { q: "Psoriasis is characterized by:", options: ["Flexural distribution with oozing", "Well-demarcated plaques with silvery scales", "Honey-colored crusts", "Burrows in finger webs"], answer: 1, explanation: "Psoriasis presents with well-demarcated erythematous plaques covered with silvery-white scales, typically on extensor surfaces (elbows, knees), scalp, and lower back.", difficulty: "medium" },
      { q: "The causative organism of impetigo is most commonly:", options: ["Streptococcus pyogenes and Staphylococcus aureus", "Candida albicans", "Herpes simplex virus", "Sarcoptes scabiei"], answer: 0, explanation: "Impetigo is most commonly caused by Staphylococcus aureus and/or Streptococcus pyogenes. It presents with honey-colored crusts (non-bullous) or flaccid bullae (bullous type).", difficulty: "easy" },
      { q: "Scabies is caused by which parasite?", options: ["Pediculus humanus", "Sarcoptes scabiei", "Demodex folliculorum", "Ixodes tick"], answer: 1, explanation: "Scabies is caused by Sarcoptes scabiei mite. It burrows into the epidermis causing intense pruritus, worse at night. Burrows are seen in finger webs, wrists, and genitalia.", difficulty: "easy" },
      { q: "First-line treatment for mild atopic eczema:", options: ["Oral steroids", "Topical steroids and emollients", "Phototherapy", "Systemic immunosuppressants"], answer: 1, explanation: "Mild atopic eczema is treated with regular emollients and topical corticosteroids (e.g., hydrocortisone 1%) for flares. Avoid triggers and use soap substitutes.", difficulty: "medium" },
    ],
  },
  {
    id: "physiotherapy",
    label: "Physiotherapy",
    icon: "🏃",
    accent: "#14b8a6",
    image: "https://images.unsplash.com/photo-1576091160399-7ba3828c9d23?auto=format&fit=crop&w=1200&q=80",
    courseOutlines: { sem1: [], sem2: [] },
    lessons: [
      { title: "Range of Motion", content: "ROM is the full movement potential of a joint. Active ROM (AROM): patient moves joint independently. Passive ROM (PROM): therapist moves joint. Active-Assisted ROM (AAROM): patient moves with assistance. Normal ROM varies by joint. Limitations indicate contracture, pain, or neurological deficit." },
      { title: "Gait Analysis", content: "Normal gait cycle: stance (60%) and swing (40%) phases. Stance: heel strike, foot flat, midstance, heel off, toe off. Swing: acceleration, midswing, deceleration. Common abnormalities: antalgic gait (pain), Trendelenburg (hip abductor weakness), ataxic (cerebellar), hemiplegic (stroke)." },
      { title: "Therapeutic Exercise", content: "Types: strengthening (isometric, isotonic, isokinetic), stretching (static, dynamic, PNF), endurance (aerobic), balance/proprioception. Principles: overload, specificity, progression, reversibility. Prescribe based on assessment findings, patient goals, and tissue healing stage." },
    ],
    questions: [
      { q: "In a normal gait cycle, the stance phase constitutes approximately:", options: ["30%", "40%", "60%", "80%"], answer: 2, explanation: "The stance phase constitutes approximately 60% of the gait cycle, and the swing phase approximately 40%. This ratio changes with speed and pathology.", difficulty: "easy" },
      { q: "A Trendelenburg gait is caused by weakness of which muscle?", options: ["Quadriceps", "Hip abductors (gluteus medius)", "Hamstrings", "Gastrocnemius"], answer: 1, explanation: "Trendelenburg gait is caused by weakness of the hip abductors (gluteus medius/minimus), resulting in the pelvis dropping on the contralateral side during stance phase.", difficulty: "medium" },
      { q: "Isometric exercise is characterized by:", options: ["Muscle contraction with movement", "Muscle contraction without movement", "Constant velocity movement", "Stretching beyond normal range"], answer: 1, explanation: "Isometric exercise involves muscle contraction without joint movement or change in muscle length (e.g., pushing against a wall). Useful when ROM is restricted.", difficulty: "easy" },
      { q: "PNF stretching stands for:", options: ["Passive Neuromuscular Facilitation", "Proprioceptive Neuromuscular Facilitation", "Progressive Neurological Flexibility", "Peripheral Nerve Function"], answer: 1, explanation: "PNF (Proprioceptive Neuromuscular Facilitation) stretching uses muscle reflexes to achieve greater flexibility. Common technique: contract-relax (hold-relax) using autogenic inhibition.", difficulty: "medium" },
      { q: "The principle of specificity in exercise means:", options: ["Exercise must be painful to be effective", "Training effects are specific to the muscle and movement trained", "All exercises produce the same results", "Only high-intensity exercise works"], answer: 1, explanation: "The principle of specificity states that training adaptations are specific to the type, intensity, and pattern of exercise performed. Training should match the desired functional outcome.", difficulty: "easy" },
    ],
  },
];

export const XP_PER_CORRECT = 10;
export const COINS_PER_SESSION = 5;

export const STREAK_BONUS = {
  3: 5,
  5: 10,
  7: 20,
  10: 50,
};

export const MODE_MULTIPLIERS = {
  adaptive: 1.2,
  spaced: 1.3,
  weak: 1.25,
  exam: 1.0,
};
